gravitystorm/openstreetmap-carto

roads.mss

Increase text-spacing for paths

---

project.mml
project.yaml

Don't render waterway names in culverts

---

placenames.mss

This looks prettier, and without compromising legibility as far as I see.

Add transparency to halo placename labels

---

amenity-points.mss

fix dy for leisure=water_park

---

project.mml
project.yaml
water.mss

With 100 uses on ways, this tag has fallen into disuse and rendering
encourages mis-tagging with it.

Remove natural=lake

---

project.mml
project.yaml

**For discussion**
I had to manually compute min/max zooms for layers and ended up storing them as if it were a TM2 style YAML file. Is this something that would be generally useful?
cc @yohanboniface

Manually add max/min zoom to layers

---

project.mml
project.yaml

Restore railways on z12 and roads and aeroways on z10/z11

---

roads.mss

Widths on z11/12/13/14/15/16:
* Runway old: 2/4/7/18/18/18
* Runway new: 2/4/6/12/18/24
* Taxiway old: 1/1/1/1/6/6
* Taxiway new: 1/1/2/4/6/8

Improve widths aeroway

---

roads.mss

This includes footway, highway, bridleway, track, and steps tunnels.
This resolves #728.

Move casing and background of path tunnels to correct attachment

---

project.mml
project.yaml

Sql cleanup

---

roads.mss

Always render road area names from z17 independent of size

---

amenity-points.mss
stations.mss

This resolves #1292.
This resolves #1356.

Add missing text-placement and marker-clip tags

---

amenity-points.mss

This brings the color of kindergarten text in line with the color of
school text.

Fix color text kindergarten

---

roads.mss

Make living street casing darker to increase contrast

---

amenity-points.mss

This brings the code in line with the coding standard

Use >= rather than >

---

amenity-points.mss

Match the color of the following labels to their respective icons:
* natural=peak
* natural=volcano
* natural=saddle
* natural=cave_entrance
* historic=memorial
* historic=archaeological_site
* man_made=lighthouse

Match label colors to icons

---

README.md

I renamed my Github account to unify it with my primary e-mail username.

@mkoniecz -> @matkoniecz

---

amenity-points.mss

When changing icons to SVG I failed to introduce colour variables for often used colours. Doing that now.

use colour variables for often used POI colours

---

addressing.mss

This resolves #320 and resolves #1120

Slightly lighten colour of house names and numbers

---

.travis.yml
scripts/travis_check_project_files

Also, some improvements to `travis_check_project_files`

Shorten travis config

---

amenity-points.mss

it will allow easier 
- adding labels
- customization
- keeping style of similar labels synchronized
It is also preparation for #459 and part of #710
Rendering is not affected (except elements of exactly the same area).

unify some label definitions, closes #1231

---

amenity-points.mss

https://cloud.githubusercontent.com/assets/899988/6761158/6cd110b0-cf50-11e4-96ac-1471942e878f.png

 Add label for tourism=viewpoint, fixes #459

---

landcover.mss

Move @scrub to green things

---

amenity-points.mss

Allow icons to overlap trees

---

landcover.mss
project.mml
project.yaml

Add label to cliff and embankment

---

amenity-points.mss

In addition to refactoring label rendering for guest houses and alpine huts are now more readable.
https://cloud.githubusercontent.com/assets/899988/6769679/0b597a8c-d0a6-11e4-901b-41af9f964d18.png
https://cloud.githubusercontent.com/assets/899988/6769680/0b5bf622-d0a6-11e4-9e1b-a81cdec86260.png
https://cloud.githubusercontent.com/assets/899988/6769682/0b60d0f2-d0a6-11e4-8e85-486b311003b8.png
https://cloud.githubusercontent.com/assets/899988/6769683/0b60be6e-d0a6-11e4-9153-c4a90beda548.png
https://cloud.githubusercontent.com/assets/899988/6769684/0b60bb6c-d0a6-11e4-9e61-790980b853fa.png
https://cloud.githubusercontent.com/assets/899988/6769685/0b709d84-d0a6-11e4-98d7-559f8733af8d.png
https://cloud.githubusercontent.com/assets/899988/6769686/0b7997ae-d0a6-11e4-89b9-2c50a53ad7d9.png …

unify label styling for various hotel-like objects

---

project.mml
project.yaml

fix missing _

---

project.mml
project.yaml

Don't exclude supermarket and station from building name rendering

---

amenity-points.mss
symbols/shop_clothes.16.svg
symbols/shop_clothes.svg

...by adding a neckline.
before
after

Make clothes shop icon more distinct

---

project.mml
project.yaml
roads.mss

Add turning circles for tracks

---

water-features.mss

Make weir, dam, and lock_gate slightly larger on z>18

---

project.mml
project.yaml

Fixes #1549
admin_level ordered:
reverse admin_level ordered:

Order placenames to place lower levels first, then by area

---

project.mml
project.yaml

Only names are rendered from these layers, so there's no change in rendering.

Add name IS NULL to placename layers

---

citywalls.mss
project.mml
project.yaml

Remove castle_walls as per #1598.

---

INSTALL.md

Still some minor bugs to fix on our side.

Note mapnik3 support is not yet here

---

.travis.yml

These are faster to run and have more resources.
Closes #1552

Switch to container-based Travis builds

---

admin.mss
landcover.mss
roads.mss
water.mss

No changes to 2.2 rendering, but fixes an issue with 3.0

Mapnik 3 vertical alignment

---

roads.mss

https://cloud.githubusercontent.com/assets/899988/8813099/f8e37f64-3000-11e5-9eac-5de74a124bce.png
https://cloud.githubusercontent.com/assets/899988/8813474/1a8745bc-3004-11e5-90dc-2b6030ec524e.png

make turning circles on highway=track smaller. Fixes #1554

---

landcover.mss

change in rendering is minor - but it still one of the most popular tags.
https://cloud.githubusercontent.com/assets/899988/8894338/b2699162-33b2-11e5-80cd-9ff45beefdee.png
https://cloud.githubusercontent.com/assets/899988/8894339/b26ab682-33b2-11e5-92ea-4dc770d96314.png
https://cloud.githubusercontent.com/assets/899988/8894340/b26e7aec-33b2-11e5-8356-836adf80a305.png
https://cloud.githubusercontent.com/assets/899988/8894341/b27295fa-33b2-11e5-8101-90b73b35bc6c.png

fix mismatch between code and comment, fixes #1686

---

landcover.mss

implements https://github.com/gravitystorm/openstreetmap-carto/pull/1667#issuecomment-125291551 by @HolgerJeromin

stop hiding the hospital between the education stuff

---

roads.mss

inherit fill for living street and pedestrian

---

roads.mss

reduces impact of #1307, reduces prominence of steps but keeps visibility of this feature at the same time
https://cloud.githubusercontent.com/assets/899988/9025849/caceacc8-3917-11e5-9707-e21e1f7b721c.png
https://cloud.githubusercontent.com/assets/899988/9025847/cacc18b4-3917-11e5-914a-a4c9b4c0848e.png
https://cloud.githubusercontent.com/assets/899988/9025848/cace0e9e-3917-11e5-8ef0-34f0a7c11fea.png
https://cloud.githubusercontent.com/assets/899988/9025850/cad1b184-3917-11e5-804e-ee209bcb8da8.png
https://cloud.githubusercontent.com/assets/899988/9025852/cad8ba7e-3917-11e5-9bcb-358f26735729.png
https://cloud.githubusercontent.com/assets/899988/9025851/cad64280-3917-11e5-8662-123e4018a48c.png
https://cloud.githubusercontent.com/assets/899988/9025853/cae358f8-3917-11e5-8369-e27eff87b8f3.png …

less wide steps - fixes #1307

---

project.mml
project.yaml

extracted from #1242 and submitted separately as an independent change (I will submit rebased #1242 as a new PR once it will be tested).

remove unneded part of SQL

---

roads.mss

Nothing ground-breaking but overall it improves rendering.
https://cloud.githubusercontent.com/assets/899988/9023352/c13ba38e-3898-11e5-93e0-0f9da1a632c3.png
https://cloud.githubusercontent.com/assets/899988/9023354/c1647912-3898-11e5-8df0-fb0c59f3664f.png
https://cloud.githubusercontent.com/assets/899988/9023355/c167dc60-3898-11e5-8fca-2ffc3063a590.png
https://cloud.githubusercontent.com/assets/899988/9023353/c155299e-3898-11e5-9c0b-3d256bbab48e.png
https://cloud.githubusercontent.com/assets/899988/9023356/c16cb3c0-3898-11e5-9f15-2a3d5a524acc.png
https://cloud.githubusercontent.com/assets/899988/9023358/c170959e-3898-11e5-940c-aebb6d96fc36.png
https://cloud.githubusercontent.com/assets/899988/9023359/c17120f4-3898-11e5-9e3b-7b53f26d93a3.png …

tweak highway=raceway width

---

amenity-points.mss
landcover.mss
project.mml
project.yaml

Small prison and military areas rendered later, huge military areas may be rendered earlier.
https://cloud.githubusercontent.com/assets/899988/9227266/f193eabe-4112-11e5-86a3-200bb75c27fb.png
https://cloud.githubusercontent.com/assets/899988/9227264/f193208e-4112-11e5-9053-0e56f19f07ba.png
https://cloud.githubusercontent.com/assets/899988/9227268/f19623ce-4112-11e5-8ae8-8deaaa55f5c4.png
https://cloud.githubusercontent.com/assets/899988/9227269/f19857a2-4112-11e5-8afa-0cc678f88787.png
https://cloud.githubusercontent.com/assets/899988/9227267/f1952384-4112-11e5-98f4-3730628c9e6b.png
https://cloud.githubusercontent.com/assets/899988/9227273/f1ade1bc-4112-11e5-8962-59b7421724ee.png
https://cloud.githubusercontent.com/assets/899988/9227270/f1ac6c2e-4112-11e5-8014-14137cd6d1f9.png …

make display threshold of landuse=military and amenity=prison areas based on way_pixels

---

landcover.mss

Should not result in any changes in rendering

merge definitions of grass landcovers

---

amenity-points.mss

Move car sharing to zoom 18

---

amenity-points.mss

Move car rental to zoom level 17

---

amenity-points.mss

introduce variable for shop names

---

amenity-points.mss

fixes yet another part of #710 
https://cloud.githubusercontent.com/assets/899988/9667840/8c88b6c2-527e-11e5-96f6-5288e2629967.png
https://cloud.githubusercontent.com/assets/899988/9667838/8c88560a-527e-11e5-8213-12761780f061.png
https://cloud.githubusercontent.com/assets/899988/9667839/8c885916-527e-11e5-81bb-d878743a0d48.png
https://cloud.githubusercontent.com/assets/899988/9667841/8c8926e8-527e-11e5-8717-04629424de7c.png
https://cloud.githubusercontent.com/assets/899988/9667837/8c879544-527e-11e5-9d64-eb0885545d6d.png
https://cloud.githubusercontent.com/assets/899988/9667842/8c8c78ac-527e-11e5-802e-c25bb5f6fbd6.png
https://cloud.githubusercontent.com/assets/899988/9667846/8ca55372-527e-11e5-97db-b78ad6f6427e.png
https://cloud.githubusercontent.com/assets/899988/9667844/8ca2d7be-527e-11e …

rework halos and lighthouse label

---

amenity-points.mss

fixes part of #710 
Minor change in rendering

use @amenity-brown for minor amenities

---

scripts/generate_road_colours.py

Make scripts/generate_road_colours.py executable

---

amenity-points.mss

fixes part of #710 (closing section for introducing variables as other colours are used once).
No change in rendering.

variable instead of repeated hardcoding

---

symbols/generating_patterns/quarry.md
symbols/generating_patterns/quarry.svg

Documentation for generating new quarry pattern (https://github.com/gravitystorm/openstreetmap-carto/pull/1696).

Adding documentation for quarry pattern

---

amenity-points.mss

next part of #710 (and final part of standardizing halos)
https://cloud.githubusercontent.com/assets/899988/9971072/87019fd4-5e59-11e5-8b9f-5e105d032959.png
https://cloud.githubusercontent.com/assets/899988/9971073/8722a184-5e59-11e5-92d9-d49d761bf8a3.png
https://cloud.githubusercontent.com/assets/899988/9971075/872dfc00-5e59-11e5-81c9-28138281c1ba.png
https://cloud.githubusercontent.com/assets/899988/9971076/872e1d0c-5e59-11e5-9ec9-91e6c6535046.png
https://cloud.githubusercontent.com/assets/899988/9971074/872c10b6-5e59-11e5-866f-8e1d592f6dde.png

standard halo also for shops

---

CONTRIBUTING.md
INSTALL.md
README.md

* Reference Kosmtik
* Rework yaml->mml
* Fix some caps

Doc improvements

---

project.mml
project.yaml

railway=station will be no longer blocked by railway=tram_stop
https://cloud.githubusercontent.com/assets/899988/10119865/af0633f0-64a3-11e5-85a6-bcc951799a87.png
https://cloud.githubusercontent.com/assets/899988/10121728/beacadd2-64fa-11e5-8e01-f57eec0213d7.png

special priority for railway=station and railway=subway_entrance

---

CONTRIBUTING.md
scripts/travis_check_project_files
scripts/yaml2mml.py

Since I was at writing Python scripts I tried to fix #1866.

refactor yaml2mml.py (fixes #1866)

---

amenity-points.mss

Move minimum zoomlevel for taxi stands from z16 to z17.

Move taxi to z17

---

amenity-points.mss

Render marina labels like other landuse labels, including font size

---

admin.mss
placenames.mss
project.mml
project.yaml
shapefiles.mss

Reverts gravitystorm/openstreetmap-carto#1938
The query has really bad performance.

Revert "rework admin boundaries and admin labels on lower zooms"

---

project.mml
project.yaml

This column is not used in the .mss.

Drop 'disused' from stations SQL

---

scripts/README.md

starts fixing #2080 
should reduce confusion documented at http://gis.stackexchange.com/questions/183459/styling-osm-data-with-osm-carto

explain purpose of scripts in /scripts

---

scripts/shop_values.rb

attempt to clarify purpose of shop_values.rb

---

openstreetmap-carto.style

These are all minor fixes which are backwards compatible

Pull in upstream default.style changes

---

amenity-points.mss

drop dead shop=fishmonger code

---

scripts/shop_values.rb

partial fix for #2090 
No rendering change, it is merely minor change to helper script.

exclude shop values that should no be rendered

---

roads.mss

fixes #1903 
https://cloud.githubusercontent.com/assets/899988/15866659/e50f675a-2cdf-11e6-9879-753c871a57e6.png

wider rails on z18, wider service rail at z18+

---

amenity-points.mss

partial fix for #710
Some (rather rare) cases have labels reduced with minor readability loss, but most are unaffected or label got larger and noticeably more readable (why hospitals had 8 sized labels?).
https://cloud.githubusercontent.com/assets/899988/15878252/c404cc3c-2d19-11e6-955a-364d02620fdf.png
https://cloud.githubusercontent.com/assets/899988/15878256/c4082ec2-2d19-11e6-926a-b72b3c73d0a3.png
https://cloud.githubusercontent.com/assets/899988/15878254/c4070cae-2d19-11e6-8fb5-141ad4ffc46f.png
https://cloud.githubusercontent.com/assets/899988/15878257/c408995c-2d19-11e6-9292-11b4dd451026.png
https://cloud.githubusercontent.com/assets/899988/15878253/c406ee04-2d19-11e6-97ea-8f28e5f8c1d3.png
https://cloud.githubusercontent.com/assets/899988/15878255/c4081c0c-2d19-11e6-8453-5934d5aaffb6 …

introduce @standard-text-size, resize 11, 9, 8 sized POI text labels to 10

---

roads.mss

- simplify code, old one was too complex and failed for small road widths
- note that tracks are special and sizes are hardcoded
- render turning circle on minor service from z18
- fix too large casing for z16 tertiary turning circle
old size of turning circle with casing:
(road-size - 2 * casing-width) * 1.8 + 2 * casing-width
what may be reduced to
road-size * 1.8 - 1.6 * casing-width
old size of turning circle without casing:
(road-size - 2 * casing-width) * 1.8
what may be reduced to
road-size * 1.8 - 3.6 * casing-width
This worked poorly for cases of small road-size. New sizes are:
for full size, with casing:
road-size * 1.6 + 2 * casing-width
inner size, without casing:
road-size * 1.6
https://cloud.githubusercontent.com/assets/899988/16024603/25126fb8-31c3-11e6-82b3-3711742b85ef.png …

resize turning circles automagically, make customization easier, fixes #1931

---

project.mml
project.yaml

AFAIK description in Github repo was changed some time ago without changing description in project file. I am assuming that it was unintentional.

synchronise description in Github repo and project file

---

project.mml
project.yaml

The style only shows large placenames, and this allows partial index usage
Fixes #2184

Filter placenames-large based on way_area

---

project.mml
project.yaml

no special rendering as this case is extremely rare (one known place where this is valid tagging)
fixes #2187

show bus_guideway tunnels

---

amenity-points.mss

fixes #710 (yet, it is the final part!)
https://cloud.githubusercontent.com/assets/899988/16176415/215deece-360f-11e6-9f0a-d6274986a06d.png
https://cloud.githubusercontent.com/assets/899988/16176416/2160c0b8-360f-11e6-81c2-ea4034bc25d7.png
https://cloud.githubusercontent.com/assets/899988/16176417/2161001e-360f-11e6-856b-0bdf30279c57.png
https://cloud.githubusercontent.com/assets/899988/16176419/2161b6a8-360f-11e6-947d-72ba4c7bdd37.png
https://cloud.githubusercontent.com/assets/899988/16176418/21610186-360f-11e6-8fa3-4887c9aba5ba.png
https://cloud.githubusercontent.com/assets/899988/16176420/2161ea4c-360f-11e6-9729-7f8d5485cf25.png
https://cloud.githubusercontent.com/assets/899988/16176421/2174a06a-360f-11e6-8b2c-3b6e89769b58.png …

switch to book font for POI labels

---

RELEASES.md

See https://github.com/pnorman/openstreetmap-carto/blob/releasing/RELEASES.md for markdown rendered version

Add information on how to make a release

---

placenames.mss

Simplify placenames (font size code): cleanup.
Should not make any rendering change.

simplify placenames (font size)

---

amenity-points.mss

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2262.
Small fixes in amenity-points.mss.

Fix spacing and zoom in syntax

---

CARTOGRAPHY.md
style.mss

Add some comments about fonts. Implements part of #2209 
No rendering change.

Comments about fonts

---

addressing.mss
admin.mss
amenity-points.mss
ferry-routes.mss
landcover.mss
placenames.mss
roads.mss
stations.mss
style.mss
water-features.mss
water.mss

Since we use the same values for text halos in a lot of places it made sense to use variables for it. Extends the use of variables beyond amenity-points and adds a variable for halo-fill.
Found using a simple search and replace. No rendering change.

variables for commonly used halo values

---

scripts/yaml2mml.py

Fixes #2221 . The other scripts are space ok, but do not conform PEP-8 so much.

Modified so it conforms more Python's PEP-8.

---

indexes.sql
indexes.yml

Fixes #2309, cross-ref openstreetmap/operations#104

Add an index for water polygons

---

scripts/generate_road_colours.py

Fix whitespace in generate_road_colours

---

CHANGELOG.md
RELEASES.md

Fixes #1430
An automated changelog has some advantages, but we have to do a bunch of the work already for the list announcements

Add a changelog

---

project.mml
project.yaml

Another layer without `minzoom` when it doesn't start rendering from ZL0.

Add minzoom to admin-low-zoom.

---

project.mml
project.yaml

Set minimum zoom for layer landcover_low_zoom.

---

get-shapefiles.sh

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/49.

Check the apps used in get-shapefiles.sh

---

.travis.yml

Use pipefail in travis

---

INSTALL.md

Document the requirements for good non-latin rendering

---

project.mml
project.yaml

Add back captial-name WHERE conditions

---

INSTALL.md

Add text on unpackaged Noto fonts

---

CODE_OF_CONDUCT.md
README.md

This adds the new maintainers to the README and Code of Conduct

Add new maintainers

---

INSTALL.md

Make clear(er) Noto Emoji must be installed manually.

Make clear(er) Noto Emoji must be installed manually.

---

openstreetmap-carto.lua

Resolves #2277, resolves #2258

Treat leisure=slipway, natural=ridge,arete as linestring by default

---

.travis.yml

I think at least the svgs should be valid xml files

Adding xmllint on all svg files

---

INSTALL.md

Add documentation about needing hstore

---

.travis.yml

Also some cleanups 3.0 enables

Check multiple Mapnik and Carto versions with Travis

---

symbols/place/place-4-z7.svg
symbols/place/place-4.svg
symbols/place/place-6-z7.svg
symbols/place/place-6.svg
symbols/place/place-capital-6.svg
symbols/place/place-capital-8.svg

There should be no visual changes here.

Cleanup SVGs for places

---

CODE_OF_CONDUCT.md

Update CoC to follow upstream Go changes

---

project.mml

Junction names for areas
Rebased #2484

Junction names for areas

---

project.mml

These are left over from the original JSON to YAML conversion. Because SRS strings contain leading - and other special characters, they're left quoted.

Clean up quotes and empty entries in MML

---

LICENSE.txt

This has always been the intention of @gravitystorm, but this avoids any doubt.

Explain that the cartography is covered by the license

---

RELEASES.md

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2362.

preview.png update instructions for a new release

---

amenity-points.mss
landcover.mss
project.mml

#2375 - at least gets the fitness_centre name rendered, we can get an icon added later.
I don't have a way to test this PR, but I assume it will work ok as I've just copied the parts where sports_centre is mentioned in the code.

Add fitness_centre with the same rendering as sports_centre

---

project.mml

fixes #2562 
before
z13
z14
after
z13
z14

fix minzoom for waterway bridges

---

addressing.mss

Typography for addressing.mss (line spacing)

Typography for addressing.mss

---

water.mss

Typography for water.mss (line wrap/line spacing)

Typography for water.mss

---

CONTRIBUTING.md

Policy for typography

---

fonts.mss

Follow up to #2622
No rendering changes

font documentation update

---

amenity-points.mss

Don't render malls as dots

---

.travis.yml

Adjust nodejs version for Travis

---

scripts/generate_road_colours.py

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2080.

Adding short description of generate_road_colours.py

---

INSTALL.md

Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2490/

Small INSTALL.md code readability fix

---

scripts/get-shapefiles.py

**New version of get-shapefiles.py**
In addition to only downloading archive updates (with the default options), the tool now performs archive expansion only in case of successfully downloaded file and generates the index only if missing or not up to date.
Some auxiliary controls have been added.
Usage and command line options remain unchanged, with a slightly different meaning for `-u`/`--update` option, which now allows to force downloading, expanding and indexing operations even if not needed.
The program now assumes that any index file already included in the downloaded archives with newer modification date than its related shp should be kept as is (without reindexing). Besides, in case `-s` option is used (indexing disabled) and when a new shp is downloaded, to avoid inconsistency …

New version of get-shapefiles.py

---

project.mml

Resolves #1253
A previous try at #2510 slowed down the rendering. I think this was because #2510 tried to backport this to the old branch using more complex code. This PR is much simpler. But it might be worth nevertheless to make sure there are no performance issues before merging this.

Junction names on areas

---

project.mml

Follow-up to #2732 (documentation update)
cc @pnorman

Update z_order documentation

---

project.mml

Fix ordering regressions

---

CONTRIBUTING.md

Small fixes in CONTRIBUTING.md to show colored syntax.

Code formatting in CONTRIBUTING.md

---

project.mml

More cleanup, partially left-over from aeroways.

Fix roads feature formation indentation and brackets

---

roads.mss

These don't occur elsewhere in the file.

Remove unused path width variables

---

amenity-points.mss

Follow up to #2824.
There are some strange text-dy's and some code could be clustered, but I leave it as it is now, because just categorizing makes enough code changes.

Culture POI category

---

amenity-points.mss
project.mml

Rendering shop=pastry like shop=confectionery

---

project.mml

A bit of code cleaning. Basic testing has been done to check that the code compiles and amenities are still here.

Skip amenities list check

---

project.mml

Render ele also on polygon alpine_hut and shelter

---

amenity-points.mss

Another follow up to #2824.
Basic testing has been made to make sure that labels are still here and they look the same as before.

Public service POI category

---

amenity-points.mss

Minor documentation update (em value)

Minor documentation update (em value)

---

DOCKER.md

include also relatively obvious git command
for anybody experienced in using git it would be obvious,
but it is preferable to make it as explict and as easy to follow as possible

be more explicit in docker quick start

---

amenity-points.mss

Follow up to #2833.
In general windmill is rather typical man made (orientation point) than amenity (to be used somehow).
Before
After

Changing windmill color to man_made

---

RELEASES.md

Add info about deployment

---

project.mml
roads.mss

This is a small simplification, we do not need the classes.

Use id's instead of classes for road layers

---

INSTALL.md

should improve onboarding experience for people not very experienced with PGSQL
code is one of useful part of now outdated https://switch2osm.org/loading-osm-data/

be more helpful in installation docs - add database creation command

---

amenity-points.mss
project.mml
symbols/apartment.svg

Resolves #401 
Renders from z>=18, i.e. one higher than hotel etc.
On a node: ![ta_node](https://user-images.githubusercontent.com/8266355/35044628-6ff25662-fb91-11e7-8fed-97bc32e774b3.png)  On a way: ![ta_building](https://user-images.githubusercontent.com/8266355/35044644-7b857c3e-fb91-11e7-9d27-c509d28eaa38.png)
Node on residential background: ![ta_residential_background](https://user-images.githubusercontent.com/8266355/35045131-21bf1758-fb93-11e7-9a09-4da400ff24f4.png)

add tourism=apartment

---

amenity-points.mss
project.mml

Add rendering for `shop=chocolate` based on [wiki page](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dchocolate)

Add rendering for shop=chocolate

---

scripts/docker-startup.sh

Possibly a minor typo in docker-startup.sh

Typo in docker-startup.sh

---

DOCKER.md
INSTALL.md
README.md
RELEASES.md
scripts/get-shapefiles.py

Move links to https where possible and fix tilemill link

---

amenity-points.mss
project.mml
symbols/sauna.svg

Fixes #3062 
From: https://www.openstreetmap.org/node/4709907893#map=17/46.66801/-71.23048 (node)
From: https://www.openstreetmap.org/#map=18/37.44146/-122.15891 (way)

Leisure sauna

---

amenity-points.mss
project.mml
symbols/shower.svg

Fixes #3067 
From: https://www.openstreetmap.org/node/4898075512#map=18/44.60609/-76.12866 (node)
From: https://www.openstreetmap.org/#map=19/45.72938/-68.83598(way)
Fake name added to test rendering:

Adding amenity=shower icon

---

aerialways.mss
project.mml

This is the version with `text-dy` decreased by 2 px:
Resolves #1807.

Show aerialway name

---

openstreetmap-carto.lua

Sorted list could perhaps prvent something like #3084

sort linestring_values in lua

---

project.mml

Fix error brought with PR #3121.
Duplicated lines !
See https://github.com/gravitystorm/openstreetmap-carto/pull/3121#discussion_r182010331

Fix duplicated lines in project.mml

---

water.mss

Follow up to #3104 to apply the same rendering to basins.

Extend intermittent waterbody rendering to basins

---

amenity-points.mss

Follow up to #2554.
Remove landuse=farm code leftover.

Remove landuse=farm leftover

---

fonts.mss

Fixes #3206 
Should trigger no rendering change when Noto Syriac Eastern is installed.

Small correction to for rendering of Syriac script

---

water.mss

Solves issue #1651 ditch and drain text is not offset. I also unified the code some to make it easier to follow. This is my first time doing this. So if I did anything wrong or if there is anything else I need to do, feel free to let me know.

Ditch and drain text is not offset 

---

CONTRIBUTING.md
fonts.mss

Fixes [this comment requesting more detailed text rendering documentation](https://github.com/gravitystorm/openstreetmap-carto/pull/3223#issuecomment-388044484).
- More detailed documentation of text rendering

More detailed documentation of text rendering

---

roads.mss

- Increasing shield distances.
Before
After

Increased shield distances (part of #3295)

---

amenity-points.mss
project.mml
symbols/bowling_alley.svg

Adds icon for leisure=bowling_alley closes #3297
https://www.openstreetmap.org/#map=19/37.69669/-122.07566 (way)
https://www.openstreetmap.org/#map=19/37.32456/-121.81336 (node)

Add icon for leisure=bowling_alley

---

amenity-points.mss

Fixes #3499 and partially #3511.

Remove smoothing for tracks and water slides..

---

project.mml

- Fixing small bug I overlooked in #3501

Fixing code for chimneys after merging cranes PR

---

amenity-points.mss

Fixes #1012
- reorder some features
- add opacity for private POI
`amenity=bbq`
https://www.openstreetmap.org/node/1062462954
`amenity=bench`
https://www.openstreetmap.org/node/4570165702
`amenity=bicycle_repair_station`
https://www.openstreetmap.org/way/266000780
`amenity=charging_station`
https://www.openstreetmap.org/node/5996039033
`amenity=drinking_water`
https://www.openstreetmap.org/node/5275971271
`amenity=shelter`
https://www.openstreetmap.org/way/426143872
`amenity=shower` and `amenity=toilets`
https://www.openstreetmap.org/way/343862313
`amenity=waste_basket`
https://www.openstreetmap.org/node/4078433504
`amenity=waste_disposal` (not included in the PR) …

Add rendering for private POI

---

indexes.sql
indexes.yml
project.mml

This adds a pair or brackets that we forgot to add in #3469.

Add missing brackets in SQL

---

INSTALL.md
fonts.mss

Fixes  #3655
- More detailed font documentation
- No rendering changes

More detailed font documentation

---

CONTRIBUTING.md

reporting issues goes to top as most people contribute in this way
keep pull requests instructions in one place not two

attempt to make order more logical

---

CODE_OF_CONDUCT.md
README.md

Welcome to @jeisenbe as new maintainer.

adding @jeisenbe as new maintainer

---

.travis.yml

Switch Travis to Xenial

---

Dockerfile
scripts/docker-startup.sh
scripts/generate_road_colours.py
scripts/generate_shields.py

Fixes #3815 
- Fix python3 installation for Docker
- Ensure python3 is requested for all scripts

Fix python3 installation for Docker

---

.github/workflows/ci.yml

This should fix the failing CI
Fixes #4142

Get packages list before apt-get install

---

indexes.sql
indexes.yml

Part of #4279
I was seeing a 50x speedup on these queries on my machine, and they have been identified as some of the slower queries.

Create a partial index for waterways

---

README.md

Add the line "The general purpose, the cartographic design goals and guidelines for this style are outlined in CARTOGRAPHY.md" to readme.md

Link to CARTOGRAPHY.md in README.md

---

scripts/get-external-data.py

Added a password option to `get-external-data.py`.
Before
After

added password as an extra option to get-external-data

---

INSTALL.md
indexes.sql
scripts/indexes.py

Documentation fixes

---

scripts/get-external-data.py

This is necessary on production systems where a different user is used for rendering.
Tested locally and select was granted on the new table.
cc @tomhughes
Fixes #4305

Add an option to grant permissions to a user for rendering from the shapefile tables

---

README.md

Added the line about major changes in v5.

Update README.md on v5

---

scripts/get-external-data.py

Fixes #4358 
- Add more verbose logging
- Explicitly check for status 200/304/other
New output (new data to download):
```
INFO:root:Starting load of external data into database
INFO:root:Checking table simplified_water_polygons
INFO:root:  Fetching https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip
INFO:root:  Download complete (23608777 bytes)
INFO:root:  File decompressed
INFO:root:  Importing into database
INFO:root:  Import complete
INFO:root:Checking table water_polygons
INFO:root:  Fetching https://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip
INFO:root:  Download complete (781453667 bytes)
INFO:root:  File decompressed
INFO:root:  Importing into database
INFO:root:  Import complete …
```

Add extra logging output and check for unexpected status codes

---

README.md

BTW, I think I would wontfix #2958 #2986 #2704 #3692 #3849 #3491 #3958 #3264 #3961 #3782 as not worth doing, not improving things or outright impossible

document growing issue count

---

CODE_OF_CONDUCT.md
README.md

Remove Matthijs as maintainer, as he is stepping down

---

CODE_OF_CONDUCT.md
README.md

I am no longer really active.
Thanks for working together and improving OSM Carto together!
I am no longer active for several reasons:
- I implemented most of what I wanted and could improve
- lack of time
- people kept trying to use OSM Carto to force their pet tagging schemes on others, bypassing discussions
- people were unhappy, no matter which decision I have taken (see also the first point)
- people were unhappy also if no decision was taken
- repeated insults from some of people who expected me to work on OSM Carto
as long as there were things that I could improve and wanted improve other issues were not important, but hobby projects are worth it when you are either doing something that you really want or people are really appreciating/using/liking what you are doing. In case of …

Mateusz Konieczny (matkoniecz) - no longer active

---

CODE_OF_CONDUCT.md
README.md

It is redoing #4561 but with a correct branch as a target.
I guess that this extra branch in main repo should be deleted.
@imagico Sorry for a confusion.

Technical fix

---

CHANGELOG.md
style/amenity-points.mss

Fixes #4502
Fixes #4225
Fixes #3800

Change symbol for Christian denominations that don't use cross

---

.github/workflows/ci.yml

Fail CI if YAML files aren't valid

---

openstreetmap-carto.lua

Relates to the column definitions.
- 
Before
After

Suggested change to code comment

---

openstreetmap-carto.lua

Fix missing parameter definitions in code comments, fix case of boolean

---

openstreetmap-carto.lua

Suggested change to code comment (2)

---

style/amenity-points.mss

This removes lines that were overlooked in https://github.com/gravitystorm/openstreetmap-carto/pull/3731#issuecomment-578486361
Fixes #4403
No rendering changes to hospitals

Remove healthcare dead code

---

scripts/get-external-data.py

My god, I am sorry that this even happened, I'm not used to this keyword being written with capital letter
Fixes: #4613

Fix for #4613

---

INSTALL.md

Correct the disable JIT command

---

RELEASES.md

This is a more consistent word wrap for release emails

Adjust word wrap for release message

---

style/roads.mss

Add missing semicolon

---

.github/workflows/ci.yml

Update CI versions to current versions

Update GH Actions versions

---

symbols/unpaved/unpaved.md

Fix markup syntax.
The original markup code did not escape the XML tags.
- The markup code escapes the XML code.
- General formatting update.

Fix markup

---

style/fonts.mss

Make font-directory statement effectife

---

.github/workflows/ci.yml

- Add a CI check that runs CartoCSS, validating the .mss files.

CI check for CartoCSS run

---

.github/workflows/ci.yml
symbols/unpaved/unpaved_primary-low-zoom.svg
symbols/unpaved/unpaved_trunk-low-zoom.svg

Update CI for road colors
- Update CI for road colors to cover the patterns
- Minor correction in the pattern color (issue catched by the CI)

Update CI for road colors

---

project.mml

- “Do not repeat yourself.” Use references instead of repetition in project.mml. If generating a JSON file out of project.mml the generated JSON file should be identical before and after this PR.

Avoid repetition in project.mml

---

project.mml

- Add a missing geometry declaration in project.mml
- No rendering changes.

Add missing geometry

---

style/amenity-points.mss

- Use a variable instead of individual values for the opacity of private amenity points. 
- No rendering changes.

Use a variable for opacity of private amenity points

---

DOCKER.md
Dockerfile

Fixes #4713 #4683 
- update Dockerfile to fix build issues
- update documentation to reference `127.0.0.1` instead of `localhost`
We should probably update the complete Docker stack and also help https://github.com/kosmtik/kosmtik to update but this PR at least makes the current code usable again.
~Test rendering with links to the example places:~

Fix Docker setup

---

DOCKER.md
INSTALL.md

This is my first ever pull request on GH - please be patient (and let me know) if I haven't done something correctly. I used this project to scratch my own itch, and I wanted to propose my minor documentation modifications back upstream.
- Formatting, spelling, and minor editorial corrections *only* to INSTALL.md and DOCKER.md docs

Formatting, spelling, and minor editorial corrections

---

CODE_OF_CONDUCT.md
README.md

With everything going on in my life I don't have the ability to take on the additional stress from OpenStreetMap Carto. Given the dead state of CartoCSS, I'm not planning to put in the time to change the current state of the project.

Step down as maintainer
