gravitystorm/openstreetmap-carto

roads.mss

it affected bridges on railway=preserved on z13, fixes #1213 
outer black casing was rendered from z13, inner white casing was rendered from z14

fix inner bridge casing zlevel mismatch

---

amenity-points.mss

Currently, there isn't any rendering for food courts (amenity=food_court). It would be nice to add this. It could be rendered the same way like amenity=restaurant.
Fixes #868.

Render amenity=food_court

---

amenity-points.mss

implements part of #1012
Thanks to @nebulon42 for SVG icons.
The same method as for private parking, without considering access=public as synonymous to access=yes

transparent symbol for private recycling and playgrounds

---

roads.mss

Based on the discussion in and supersedes #863.
At least partly resolves #826 and #345.
This does not add special styles for tunnels or bridges and might need some rework, when the 'proposed=*' key is available in the database.
Rendering example:

Add opacity to highway=proposed for less prominent rendering

---

roads.mss

Improve rendering of construction=residential on zoom 13

---

buildings.mss

Starting from https://github.com/gravitystorm/openstreetmap-carto/pull/1202#issuecomment-68927316 I'd like to propose a change were the hue of buildings is moved from the more yellowish  HSV(39°, .07, .84) to the more reddish HSV(25°, .07, .84). At the same time the outline is darkened by 10% to now 20% from the fill for more contrast.
Previews (before on the left, after on the right):
These previews are outdated.
no landuse
industrial/retail/commerical
residential/place of worship:
garden/grass:
farmland/farmyard:

adjust buildings hue, darken outlines

---

amenity-points.mss
symbols/town_hall.16.svg

Resolves #77. Rendering rules are the same as for library, cinema, theatre and courthouse, only the icon is different.
Icon: [nebulon42/osmic/town-hall-16.svg](https://github.com/nebulon42/osmic/blob/master/administration/town-hall-16.svg)
(see also [nebulon42/osmic/government-16.svg](https://github.com/nebulon42/osmic/blob/master/administration/government-16.svg))
before
not rendered
after (http://www.openstreetmap.org/relation/11101)

add rendering for amenity=townhall

---

project.mml
project.yaml
water.mss

Note: there are still some issues.
- <s>(1) - in a rare situation - intermittent waterway with bridge=*, connecting with not intermittent waterway ordering of rendering may be wrong, leading to a small glitch. It is fixable by ordering waterways in SQL querry - but is it worth additional complexity and performance hit to solve something that never appears in data? Or in the worst case - is really rare? (based on math1985's comment)</s>
- <s>(2) - is it possible to maintain consistent dashes across (meta)tiles? See the first image. (thanks @pnorman!) </s>
- <s>(3) - is it necessary to modify rendering of wadis? And (changed) derelict canals? Both use dashes,  but wider and  rounded ones. See examples at http://www.openstreetmap.org/way/81918899 and …

Special rendering for intermittent waterways - fixes #805

---

INSTALL.md

Thanks to @woodpeck.
Supersedes #837.

Paranar font resides in fonts-taml-tscu on Trusty

---

project.mml
project.yaml

Adds missing labels for glaciers and bare ground land covers for low zooms <10.  This is purely a fix for a coding error - styling already has the correct settings, just missing in project.yaml/mml.
In general the separate layers are prone to this kind of mistake, would probably be good to prominently mention this in CONTRIBUTING.md.

add missing landcovers to text-poly-low-zoom

---

amenity-points.mss

The attachments were there to prevent combinatorial explosion.
This is no longer necessary as the combinatorial explosion is now prevented
by means of the 'feature' field.

Drop attachments

---

INSTALL.md

Fixes #1294
The carto version requirements are met by Ubuntu 14.04, and of course npm installed carto is much more recent.

Increase minimum carto version

---

project.mml
project.yaml

Resolves #1301.
Fixes a regression introduced by specifying minzoom for the aerialway layer.

fix aerialway zoom regression

---

project.mml
project.yaml

resolves #1306 and also restores other amenity_points stuff at z<=12 (i.e. peaks).
In general i think a systematic check of the minzoom/maxzoom values would be in order.

correct minzoom value for amenity_points layers

---

.travis.yml
scripts/travis_check_project_files

Fixes #1329.
See https://travis-ci.org/floscher/openstreetmap-carto/builds/51741837 for a failing build and https://travis-ci.org/floscher/openstreetmap-carto/builds/51741018 for a sucessful build.
This suppresses the output of the complete diff, because I'd say that in only a very few cases it would be of interest **what** differs between `project.mml` and `project.mml2`, the information **that** there are differences should be enough. In most cases the author of the commit simply forgot to run `yaml2mml.py` (like in https://travis-ci.org/gravitystorm/openstreetmap-carto/builds/51634644).
This could surely be done in a oneliner, but I wanted to keep it readable. Additionally Travis will always print out the full command. That means it would also print the string saying that the files are …

Made Travis output on yaml2mml.py failure more comprehensive

---

placenames.mss
project.mml
project.yaml

* Don't render place=town on z16 and higher, and place=suburb and place=village
on z17 and higher.
* Render place=hamlet, place=locality, place=neighbourhood,
place=isolated_dwelling, and place=farm from z15 rather than from z14 (resolves
#948).
* Render place=town black rather than gray.
* Make font sizes more consistent by increasing font size for place=town on z12
and z13, for place=suburb on z16, and for place=village on z14 and z16
(resolves #734, resolves #1204).
* Treat capital=4 like capital=yes (resolves #522).
* Make text-wrap consistent.

Clean up place name rendering

---

amenity-points.mss
symbols/nightclub.18.svg

Adds rendering for nightclubs, resolves #456.
In order not to fully repeat the icon-related discussion please also see https://github.com/nebulon42/osmic/issues/8
before
not rendered
after

add rendering for amenity=nightclub

---

openstreetmap-carto.style

This style file isn't part of osm2pgsql, so shouldn't say so. Also the help text explaining the syntax is no longer needed.

Customize .style text for OpenStreetMap Carto

---

project.mml
project.yaml
water.mss

Render intermittend rivers with dashed line also on low zoom levels.
Screenshot:
Resolves #1305 and substitutes #1376 and #1399

Render intermittend rivers with dashed line also on low zoom levels

---

amenity-points.mss

Unfortunately, YA text-dy is too low :(

fix dy for golf labels

---

INSTALL.md

The old link broke when we rearranged the files

Update INSTALL.md dependencies link

---

amenity-points.mss

Do not render island/islet name when way_pixels is big
If islands are big and the zoom level is high, we still have a label rendered for these islands. This seems a little confusing to me.
This PR uses way_pixels to discard label rendering if the island surface is quite big (relative to your screen).
Maybe this approach may be also useful for other way_pixel based labels?

Do not render island/islet name when way_pixels is big

---

.gitattributes

Treating MML files as binary lets git not try to display a meaningless diff

Treat MML files as binary

---

landcover.mss

This resolves #781.
Supersedes #1449.
Before:
After:

Render cutline as thinner line

---

amenity-points.mss

Better explicitly add the size, so that it won't depends on some default.

Add missing font size for bank

---

project.mml
project.yaml

Not all of the SQL was reformatted with the change to YAML, and this fixes much of what was not done.
I believe there are no more big cleanups left.

Fix explicit indentation modifiers in YAML

---

.gitignore

A common workflow is to run kosmtik against project.yaml with a
localconfig.json, so it should be ignored by git

Add localconfig to gitignore

---

roads.mss

dropped invisible clutter from z8 to z11
visible railway=tram on z12
subtler at z13, z15, z16
fixes #1637
https://cloud.githubusercontent.com/assets/899988/8548012/b85467c2-24c2-11e5-92d5-2890be60ade0.png

rework display of railway=tram

---

roads.mss

small changes:
https://cloud.githubusercontent.com/assets/899988/8616741/f99326a0-26fd-11e5-9f0e-cd2c1a939a74.png
https://cloud.githubusercontent.com/assets/899988/8616743/f994ba6a-26fd-11e5-8698-77c3bbe7c85b.png
https://cloud.githubusercontent.com/assets/899988/8616742/f9944738-26fd-11e5-8b82-b2a14779a233.png
https://cloud.githubusercontent.com/assets/899988/8616745/f998f2f6-26fd-11e5-9c05-54c9c2d5cd73.png
https://cloud.githubusercontent.com/assets/899988/8616922/5d0a2494-26ff-11e5-9558-072ba1bae43a.png
big changes in rendering:
https://cloud.githubusercontent.com/assets/899988/8604275/ddaa6460-267d-11e5-8899-9e5f76b1b435.png
https://cloud.githubusercontent.com/assets/899988/8616915/5143aa5e-26ff-11e5-86f4-107fd33e7fb6.png
https://cloud.githubusercontent.com/assets/899988/8616746/f99ee314 …

start displaying minor rail from z13, fixes #1645

---

landcover.mss
project.mml
project.yaml

Unfortunately I was unable to eliminate weird effect for multypolygon observed in London - only one section receives full border. See http://www.openstreetmap.org/?mlat=51.5391&mlon=-0.1566#map=12/51.5391/-0.1566
https://cloud.githubusercontent.com/assets/899988/8512754/97f0c164-2351-11e5-9394-ab665e94e056.png
https://cloud.githubusercontent.com/assets/899988/8512753/97e99128-2351-11e5-82d9-37aec99d8837.png
https://cloud.githubusercontent.com/assets/899988/8512755/97f18c0c-2351-11e5-89b9-2e9d0099ab8c.png
https://cloud.githubusercontent.com/assets/899988/8512750/7bf017f8-2351-11e5-9e42-f8b374387fd8.png
https://cloud.githubusercontent.com/assets/899988/8512751/7bf055ec-2351-11e5-8882-eaed417faa08.png
EDIT: reported also on PL forum - see …

stop displaying really small zoos and theme parks

---

aerialways.mss

Fixes #875.
Symbols are grey instead of black and square instead of rounded. Square vs. round may not be really visible. But since #1612 it will be easier to adjust the pattern in discussion.
preview (right=new) (outdated)
aerialway=goods on the right side vs. other aerialways on the left side of each half.

different rendering for aerialway=goods

---

project.mml
project.yaml

Admin areas are labeled on the edges, so those where the bbox lies completely inside can be discarded in SQL
This helps with https://github.com/mapnik/mapnik/issues/2937 and generally slow performance with offsetting of polygons in the latest RC
https://github.com/mapnik/mapnik/issues/2942 prevents turning on clip for now, which would offer gains for nature reserve fill/edge

SQL tweaks to improve Mapnik 3 performance for admin areas

---

amenity-points.mss

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1642.
I think amenity-brown is better suited for services than shop-violet, which is mainly for buying goods:

Change color of amenity=bank and amenity=atm to @amenity-brown

---

landcover.mss

I think that rendering borders at z12 makes no sense - as are mostly hidden under other features and small present fragments are not really useful. For example UBC at z12 has visible only small triangle
At z10 and z11 even the biggest educational areas are quite small and a separate colour fill makes no sense. Even at z12 value of it is dubious.
https://cloud.githubusercontent.com/assets/899988/8718499/155e1dbc-2ba5-11e5-8400-1ff230630ab0.png
https://cloud.githubusercontent.com/assets/899988/8718500/1563519c-2ba5-11e5-94b7-3a1b7194a42e.png
https://cloud.githubusercontent.com/assets/899988/8718501/15674edc-2ba5-11e5-97a2-d51f484a207b.png
https://cloud.githubusercontent.com/assets/899988/8718502/156797c0-2ba5-11e5-8939-afd2721f8d87.png
with one of test versions of the new road style …

render educational areas as distinct later - fixes #1660

---

amenity-points.mss
landcover.mss

During #1662 I completely missed that it affects also hospitals (now I am testing whatever it resulted in worse rendering).
This change should make code less confusing.
It it is likely that this name may be improved - it is better than current one but I am not truly happy about it.
EDIT: Tested hospitals, it seems that hospitals are similar in size too universities - therefore there is no problem with rendering.

make variable name less misleading

---

buildings.mss
landcover.mss
roads.mss

Currently both highway=residential and highway=unclassified is rendered too early, leading to clutter on the map and poor display of available data. 
Default maps style vs Google maps in London
Default OSM style should not only show how many roads are mapped, it should also demonstrate that OSM data is able to distinguish minor and major roads.
before/after images
Large city (London)
550px: https://cloud.githubusercontent.com/assets/899988/8889566/8a5fa04a-32df-11e5-9d62-2d8dac82f958.png
1000px: http://www.mediafire.com/convkey/84d9/3v26frfg92zwaw7zg.jpg
Rural area in forested mountains (Slovakia)
550px: https://cloud.githubusercontent.com/assets/899988/8889567/924ec628-32df-11e5-8a37-f05be0cfb414.png
1000px: https://cloud.githubusercontent.com/assets/899988/8889568/9729bce8-32df-11e5-8a78 …

Start rendering of minor roads later

---

roads.mss

to prevent potential confusion:
In version currently used on OSM website both highway=unclassified and highway=residential are rendered from z10.
#1682 proposed rendering highway=unclassified from z11 and highway=residential from z12
@pnorman merged this pull requested and added commit https://github.com/gravitystorm/openstreetmap-carto/commit/93789b6bac94e7c13bae6fb4a6d8ee7df02aaf3f - that set both unclassified and residential to render from z12
This pull requests makes highway=residential thinner (0.4 width instead of 1.0).
550px preview:
https://cloud.githubusercontent.com/assets/899988/8900694/d49ea19c-3442-11e5-86b6-07d6d5c8f12d.png
https://cloud.githubusercontent.com/assets/899988/8900696/d4a387b6-3442-11e5-851c-09b88a3eebd6.png …

make highway=residential at z12 thinner

---

project.mml
project.yaml

The unordered layers were leading to artifacts on MT boundaries, and oddities where towns were rendered on top of cities.
Similar to #1461, but does not adjust low zoom or go as far.

Order place layers by place type

---

roads.mss

After recent changes to residential/unclassified a regression appeared. On z13 these roads turned grey what was neither wanted nor expected.
I found (very ugly) change that fixes that problem, but unfortunately I have no idea why rendering at z13 was affected by these changes and why this PR fixes problem.
It would be preferable to solve it properly.
These definitions are affecting
> #roads-low-zoom[zoom < 10],
> .roads-fill[zoom >= 10],
> .bridges-fill[zoom >= 10],
> .tunnels-fill[zoom >= 10] {
> #roads-low-zoom[zoom < 10]
problem happened on z13, so [zoom < 10] is a good alibi
.roads-fill[zoom >= 10], 
.bridges-fill[zoom >= 10],
>        .roads-fill, .bridges-fill {
>          line-color: @residential-fill;
>        }
should override gray color for these two layers
> …

fixed display of residential and unclassified roads at z13

---

get-shapefiles.sh
project.mml
project.yaml
shapefiles.mss

Since the preprocessed Antarctic icesheet data is now regularly available on [openstreetmapdata.com](http://openstreetmapdata.com/data/icesheet) (where also the coastlines come from) this PR adds rendering of the Antarctic ice based on that data.  Style-wise this should be an exact equivalent to normal glacier rendering.
See also #960 for more background information.
Rendering examples:
Resolves #960

adding antarctic icesheet rendering based on preprocessed shapefiles

---

roads.mss

It affects also current version. Residential now appears from z12. I am not 100% sure what will be in osm_planet_roads - link in http://gis.stackexchange.com/questions/37099/in-osm2pgsql-how-is-the-planet-osm-roads-table-populated/84913#84913 is dead (@pnorman, maybe you can update it?). According to my check tertiary is not appearing in osm_planet_roads (at least it happens this way for my local databases) and it is rendered from z10.

fix outdated comment

---

buildings.mss
project.mml
project.yaml
roads.mss

fixes #436
closes #828 as it is no longer necessary
partially implements #1320 
It adds two new layers - it is avoidable but at cost of complex SQL. I am not fully convinced what would be better idea but avoiding unnecessary complexity is certainly good and I am not sure whatever adding new layers has significant performance impact.
Labelling of bridges may be too agressive, I may be easily convinced to show labels later. 
Done as part of GSoC but may be reviewed independently from road restyling.
It should make one of the most popular tagging for renderer obsolete (bridges as building=* instead of man_made=bridge).
https://cloud.githubusercontent.com/assets/899988/8510890/367f514a-22ff-11e5-98aa-43e9547edf49.png
https://cloud.githubusercontent.com/assets/899988/8510889/367eb276-22ff-11e5- …

show man_made=bridge

---

INSTALL.md

There are no known major Mapnik 3 issues left.
After merging, I'll have a look at the issues against the Mapnik 3 milestone. Those which will require Mapnik 3 style features can be left, but others can be closed.

Support Mapnik 3 in install docs

---

shapefiles.mss

Fixes #1749.
I'm not sure if it is an improvement colour-wise, but out of consistency reasons admin boundaries on z1-3 should be the same colour as later on.
showing only after version:

change colour of admin boundaries to be consistent on z1-3

---

roads.mss

stop using italics - bridge is not landcover
smallest labels are slightly larger to make them more readable
I recommend merging it before release (in the nearest one man_made=bridge will be rendered for the first time).
https://cloud.githubusercontent.com/assets/899988/9503315/68ccd914-4c36-11e5-8f0f-a4f19cae9e90.png
https://cloud.githubusercontent.com/assets/899988/9503314/68cabb98-4c36-11e5-9192-3ef8c0f03580.png
https://cloud.githubusercontent.com/assets/899988/9503316/68cfe85c-4c36-11e5-8a5f-1b5155999425.png

better labels for bridges

---

power.mss

I think major power lines are slightly too prominent. This was amplified by the recent colour change of forest. I made them a bit lighter and slightly thinner.
z14 (left = before)
z16

Make major power lines less prominent

---

amenity-points.mss

Anyway it was not working due to typo. It is defined correctly later.
Rendering is not changed.

remove duplicated amenity=recycling label

---

scripts/shop_values.rb

as discussed in #1632 (it is not changing rendering but should protect against accidental reintroduction on updating list of shops displayed as dot)

add shop=winery to list of ignored shop values

---

amenity-points.mss

As mentioned in https://github.com/gravitystorm/openstreetmap-carto/pull/1777: shop=car_repair is in fact amenity, so it should be rendered in brown, since it sells services rather than goods:

Changing color of shop=car_repair to brown 

---

stations.mss

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1834.
Moving only the tram_stop labels (not touching dots) from z>=14 to z>=16 works for me.
**Wroclaw**
z14 (before/after):
z15 (before/after):
**Warsaw** 
It's even better - some (currently obscured) metro/railway stations and cemetery name start being visible.
z14 (before/after):
z15 (before/after):

Move rendering of railway=tram_stop labels later

---

roads.mss

In the recently merged new road style, roads are rendered quite narrow at zoom levels 18 and 19, especially residential and unclassified roads. At zoom 19, these roads are rendered much narrower than their real width. I propose to slightly increase the width of roads at zoom 18, and more so at zoom 19. At zoom 19, also the label font size is increased slightly.
See also the discussion at #1290.
Zoom 18 before / after:
Zoom 19 before / after:
Zoom 18 before / after:
Zoom 19 before / after:
Zoom 18 before / after:
Zoom 19 before / after:

Increase width of roads at high zoom

---

amenity-points.mss

Simple code cleaning to use the color variable name (water-text) instead of hardcoded hex numbers and compacting similar text label entries (natural_bay and natural_spring).

Changing water features color to already defined water-text variable

---

roads.mss
symbols/oneway-reverse.svg
symbols/oneway.svg

This PR moves rendering of oneway arrows from a dasharray representation towards a SVG marker symbolizer. This has the disadvantage of losing the ability to have bent arrows but results in a clearer representation, improves arrow positioning and avoids overlap with road labels. Additionally, rendering arrows for construction roads are dropped and arrows are coloured corresponding to either the casing colour or the fill colour of the road type they are rendered on, which leads to more visual consistency.
Fixes #606 by using SVG markers.
Fixes #681 as using markers prevents collision with labels.
Fixes #597 by dropping arrows for `highway=construction`.
Might fix #595 and #284, but I cannot definitely confirm, testing is welcome.
I think there is no change for #706.
Possible problems: …

rework oneway arrows

---

amenity-points.mss

There is one minor change to rendering: names for very large tourism=theme_park and tourism=zoo may be now rendered from z10 instead of z13 (way_pixels > 3000). I am not sure is it really changing rendering at any place across the world, but for very large feature it would be OK and allows to use simpler code.
After this change it is more readable what is redefined (like larger text-halo-radius for grave yards and cemeteries) and what is unchanged from default value, code is also shorter.
Overall it in my opinion improves readability.

reduce repetitions in  definitions of labels, fixes #1880

---

stations.mss

This is a follow up of my research which started in https://github.com/gravitystorm/openstreetmap-carto/pull/1878#issuecomment-143726126, but then went in a different direction.
I think railway=halt is somewhere between railway=station and tram_stop, but should be closer to the station. Currently they are indistinguishable from tram stops (they just start to be rendered earlier, like stations). That's why I want their labels to be bold (like the station), but with slightly smaller font size than station and visible from z15 (station is from z14 and tram stop is now from z16). I assume that aerialway=station are corresponding type (for the sake of simplicity, because they are the same now), but maybe they should be treated separately. If you have some other ideas, I'll try to test them …

Improving railway=halt and aerialway=station labels

---

roads.mss

Also make sure that the progression for font size minimum sizes increases with
a factor of 4 (this makes sure that every zoom level is one size bigger).
Bridge names currently show up way too early, see for example [here](http://www.openstreetmap.org/#map=14/52.0899/5.1238) with Viebrug and Lucasbrug.

Significantly increase minimum zoom level for bridge names

---

amenity-points.mss

even in areas with low feature density it makes no sense to render crosses before rendering PoW

tweak crosses to not appear earlier than place_of_worship

---

roads.mss

Follow-up to #1871.
Makes residential/unclassified refs stand out less, by removing the bold font, keeping the font size 1px below shielded refs (means decreasing by 2px on z15), increasing the spacing between texts so that less refs appear on z15 and increasing the halo width as replacement for a proper shield.
Previews are for a location that was mentioned in https://github.com/gravitystorm/openstreetmap-carto/issues/285#issuecomment-30535756 for having exceptionally many such refs.
before
after - current road shields
after - proposed road shields

make residential refs less prominent

---

project.mml
project.yaml

Trees were covering station labels, so the layer has been moved down below the placenames layers.
before
after

move tree layer below placename layer (fixes #1470)

---

stations.mss

Follow-up of #1881.
Since I find the colour of station labels quite ugly I thought it might be better to tie them to the colour of the station markers (but slightly darker and slightly more saturated). To improve readability of tram stop labels the halo is increased from 1 to 1.5.
Previews
City, z15
City (tram stops), z16
Railway halt/station, z15
Aerialways, z15

change colour of station labels

---

placenames.mss

Fixes #1913.
I removed the upper limit for the rendering of refs since on z4 we can easily go without it. That fixes a potential carto bug. Removing the upper limit may cause the refs of some large Russian or Canadian provinces to appear, which I regard as improvement.

fix state name labels are displayed up to z19

---

project.mml
project.yaml
water-features.mss

This saves 4 out 20 seconds on ever Carto-run on my system, and was a bug
anyway.
See also #1941.

Drop incorrect text class from text-line

---

amenity-points.mss

This improves #1941. Carto processing is now overall about 20% faster on my system.

Change order of definitions to speed up carto processing

---

roads.mss

* Make residential/unclassified 0.5 px narrower on z13
* Make tertiary 1 px narrower on z13
Before:
After:

Make residential and tertiary slightly narrower on z13

---

symbols/beverages-14.svg

I think the Osmic version is better than mine (slightly edited bottle, so it's different than shop=alcohol), so I'd like to replace my draft from https://github.com/gravitystorm/openstreetmap-carto/pull/1596 with the work of @nebulon42. Before/after comparison:

Osmic icon for shop=beverages

---

admin.mss
placenames.mss
project.mml
project.yaml
shapefiles.mss

Fixes #907, #1571.
Adresses part of #622 (the part that is similar to #907, #1571)
Changes are concerned with reduction of complexity and better rendering of country/state labels as well as boundary lines, especially in maintaining a visual hierarchy of admin levels 2,3,4.
Details:
* country lines are thinner on z1,2,3 but get thicker quickly and maintain a hierarchy with level 3 and 4
* level 3 and 4 are much thinner earlier
* line thickness of admin entities on higher zooms is unchanged
* line rendering only uses data derived from relations (osm_id < 0) which seems to avoid some duplicate rendering
* ~~simplification of admin lines starting at z4 using `ST_simplify` with a initial tolerance of ~ 7800 and decreasing linearly with scale denominator until the layer no longer gets rendered …

rework admin boundaries and admin labels on lower zooms

---

landcover.mss

Currently mapping landuse=farmland in most locations results in worse and less readable map. It is caused by too strong color and large size of landuse=farmland areas. In result it is frequently the most noticeable (or at least one of the most noticeable) features. Frequently it is more prominent than far more important features like villages or towns. There is also problem of residential, industrial, farmyard and other landuses not visible enough in sea of landuse=farmland. This problem is larger than implied by color difference computations due to differences in size of typical landuses and distribution of obscuring features. Density of buildings, names, roads etc are significantly higher on landuse=residential/industrial etc than on landuse=farmland.
All distances are in delta_e94 …

new farmland color - makes farmland less prominent

---

project.mml
project.yaml

Removes line-barrier catch-all rendering and fixes a bug where the line-barrier layer was displayed from z16, but a rendering rule for z14 was present.
Line barrier values > 1000 uses (with taginfo usage and comments):
fence           1 748 621 ok
wall              1 306 878 ok
hedge            646 979 ok
retaining_wall  93 566 ok
yes                   47 152 no wiki page, too general
kerb                 44 915 ok
ditch                 20 143 ok
city_wall           19 589 ok
guard_rail        17 077 ok
hedge_bank    14 508 only german wiki page available
wire_fence       10 379 no wiki page, should be fence
line                    8 166 no wiki page, not a barrier (access=no?), tagging for the renderer
chain                 5 405 ok
embankment     4 599 no wiki page, but included since …

remove line barrier catch-all rendering

---

admin.mss
placenames.mss
project.mml
project.yaml
shapefiles.mss

This recreates the styling of #1938 without the problematic queries.
It would be grand if there could be a .2 release including these changes. Sorry for the problems this has caused.

rework admin boundaries (without z4 logic)

---

landcover.mss

Taking over https://github.com/gravitystorm/openstreetmap-carto/pull/1526.
My take is that we can use "scrub green" as the color for cutlines, which works in many ways:
- it doesn't look like a road any more...
- ...which gives us the opportunity to make the cutline wider than before (to be visible under footway/path)...
- ...and looks more like typical cutline surface (low green plants, like scrub), while not using scrub symbols (because we're not sure it's really scrub, not the grass or something else)
For comparison: the vertical line is not a cutline, but real scrub area about 10 m wide.
z14:
z16:
z19:

Render cutline as thicker line with some green color

---

placenames.mss

This makes them visually stand out more from road/square names.

Increase size of small place names on z15 by one pixel

---

roads.mss

Fixes #2054.
Thanks @daganzdaanda for reporting.
before
after

fix oneway arrow colour for highway=path/footway and bicycle/horse=designated

---

amenity-points.mss
project.mml
project.yaml

fixes #2014 
swing_gate, lift_gate, whatever_gate instead of using simple barrier=gate, gate=detailed_values is not my favourite tagging scheme but it seems to be popular enough to be considered standard tagging, it is also supported by other data consumers.
https://cloud.githubusercontent.com/assets/899988/13266365/15bb3d58-da78-11e5-982a-59b08243a8d3.png
https://cloud.githubusercontent.com/assets/899988/13266368/15bd98e6-da78-11e5-857f-b68885a6fbee.png
https://cloud.githubusercontent.com/assets/899988/13266366/15bd24c4-da78-11e5-97d5-5175b1d46e8d.png
https://cloud.githubusercontent.com/assets/899988/13266367/15bd8c7a-da78-11e5-9c33-86f593a56fd9.png
https://cloud.githubusercontent.com/assets/899988/13266369/15bdcdf2-da78-11e5-8cd4-f1b22a738d63.png

render swing_gate like lift_gate

---

.travis.yml
INSTALL.md
get-shapefiles.sh
project.mml
project.yaml
shapefiles.mss
style.mss
water.mss

This should have no rendering changes, as the base land and base ocean are still the first things drawn.
We may want to re-order later to put water polygons by ocean polygons, but this will require consideration of what landuse should appear on oceans
Fixes #1982.

Switch to ocean polygons

---

roads.mss

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1974.
Trivial patch with non-trivial consequences, please propose some testing places from different parts of the world to see. Some screenshot samples around Warsaw for the start (click to see the full resolution):
1) City with residential, secondary and parking areas:
2) City with school and hospital area around:
3) Outside the city with current (new) farmland color:

Make tertiary road yellowish

---

project.mml
project.yaml

This can help have a consistent ordering across MT boundaries, reducing labeling problems.
Long labels are harder to place, so I put them before short ones.

Make place ordering better defined

---

INSTALL.md
indexes.sql
indexes.yml
scripts/indexes.py

These custom indexes should speed up rendering, particularly at low and middle zooms.
Fixes #207
cc @woodpeck @jburgess777 @Firefishy 
I'm not recommending any way_area indexes, not because I don't think they're worth it, but because they're more complicated to get right, and I'd rather go ahead and recommend a number of indexes I already know help performance.

Add custom index information

---

CONTRIBUTING.md

I realised that while these are very common throughout our code, it's not explicit in the guidelines how to handle them.

Add guideline on symbolizers which change per zoom

---

power.mss

idea by @SomeoneElseOSM
In this version it is less radical to keep power lines readable also on busy background (typically - in cities).
fixes #1260
https://cloud.githubusercontent.com/assets/899988/15992477/b206ef6c-30cd-11e6-9283-958b1aa0803e.png
https://cloud.githubusercontent.com/assets/899988/15992470/a8f65958-30cd-11e6-8715-c68894c6392f.png
https://cloud.githubusercontent.com/assets/899988/15992476/b203e04c-30cd-11e6-9748-d32999848e41.png
https://cloud.githubusercontent.com/assets/899988/15992478/b207862a-30cd-11e6-9cdf-b465270d8619.png
https://cloud.githubusercontent.com/assets/899988/15992474/b1db5d98-30cd-11e6-8e87-fe5cd98945f5.png
https://cloud.githubusercontent.com/assets/899988/15992475/b1f3560a-30cd-11e6-888b-483980599b9e.png …

thinner power=line and power=minor_line

---

roads.mss

It makes main railways slightly more prominent.
https://cloud.githubusercontent.com/assets/899988/15992726/02708792-30d3-11e6-93a5-1069316681a0.png
https://cloud.githubusercontent.com/assets/899988/15992727/027199e8-30d3-11e6-8d01-d4810b83e224.png
https://cloud.githubusercontent.com/assets/899988/15992725/026fed8c-30d3-11e6-9743-d048b603d5c3.png
https://cloud.githubusercontent.com/assets/899988/15992729/02748f9a-30d3-11e6-876c-86624bb22d3c.png
https://cloud.githubusercontent.com/assets/899988/15992728/02746f9c-30d3-11e6-9b5e-04ba2ea98742.png
https://cloud.githubusercontent.com/assets/899988/15992730/02774ea6-30d3-11e6-9b17-49b1275088a5.png
https://cloud.githubusercontent.com/assets/899988/15992731/0286d524-30d3-11e6-8f73-1f36ec79f621.png

darker standard rail on higher zoom

---

project.mml
project.yaml

No rendering change as nothing from this layer is rendered on z3 - see https://github.com/gravitystorm/openstreetmap-carto/blob/master/placenames.mss
Makes rendering on z3 slightly faster.

placenames-medium is not used on z3

---

placenames.mss

fixes #2175 
I tested some modifications to mid-zoom levels. Increasing labels for placenames is one that is a clear improvement (at least according to my tests).
https://cloud.githubusercontent.com/assets/899988/16192682/04cd0e84-36eb-11e6-97cf-a32621eff58e.png
https://cloud.githubusercontent.com/assets/899988/16192683/04cf6198-36eb-11e6-8a43-8c41a17fbb51.png
https://cloud.githubusercontent.com/assets/899988/16192685/04d732ce-36eb-11e6-8b4d-a459f8e90a71.png
https://cloud.githubusercontent.com/assets/899988/16192684/04d6e418-36eb-11e6-87c1-3837ad132099.png
https://cloud.githubusercontent.com/assets/899988/16192686/04d89448-36eb-11e6-8132-d08095584646.png
https://cloud.githubusercontent.com/assets/899988/16192687/04da6160-36eb-11e6-8044-cfabeda5c9d0.png …

larger labels for placenames

---

project.mml
project.yaml

see https://github.com/gravitystorm/openstreetmap-carto/blob/d789bdac60a17ff8fe18e6d8b978423147c21c53/buildings.mss#L13
it makes z12 significantly faster

it is not necessary to query buildings for z12, as buildings are not displayed on z12

---

placenames.mss

This results in rendering more labels for placenames for renderers using Mapnik 2.
For renderers using Mapnik 3 this will have no effect (text-min-distance is applicable only to text placed on line).
This change is equivalent in effect to upgrading to Mapnik 3.
fixes #2189, related to #1935 
According to my testing rendering more placenames results in much better/better map (in many cases), unchanged (most cases) or at least not worse (in rare cases).
Some examples with changes to lower zoom levels are at https://github.com/gravitystorm/openstreetmap-carto/issues/2189#issuecomment-228153236
Examples of changes to higher will be below.
Note that attached rendered examples were not generated with exactly the same code as submitted in PR (code included removal of `text-line-spacing: 1;` in …

remove text-min-distance - increase label density

---

INSTALL.md
style.mss

Fixes #2200 by removing fonts that have disappeared, updating package names, and updating font names.
-----
Running ``python -c "from mapnik import FontEngine as e;print '\n'.join(e.instance().face_names())"`` gives a list of fonts known to Mapnik. Doing this with 16.04 and eliminating Serif and Mono fonts gives
```
Ani Regular
Arundina Bold
Arundina Bold Italic
Arundina Italic
Arundina Regular
DejaVu Sans Bold
DejaVu Sans Bold Oblique
DejaVu Sans Book
DejaVu Sans Condensed
DejaVu Sans Condensed Bold
DejaVu Sans Condensed Bold Oblique
DejaVu Sans Condensed Oblique
DejaVu Sans ExtraLight
DejaVu Sans Oblique
Droid Sans Fallback Regular
Gargi Regular
Jamrul Normal
Khmer OS Battambang Regular
Khmer OS Bokor Regular
Khmer OS Content Regular
Khmer OS Fasthand Regular
Khmer OS Freehand Regular …
```

Update fonts list for Ubuntu 16.04

---

amenity-points.mss
landcover.mss

This change replaces the very strong and dark color for stadium/sports_centre with the bright education/hospital color and unifies track/pitch into an intermediate green tone.
This is based on the following considerations:
* the dark and strong color of stadium/sports_centre was a major problem since it stands out very strongly putting  a lot of emphasis on  these features and it does not comply with the general concept of using brighter and more muted colors for large features and stronger colors for small features.  Using the education color seems fitting since there are a lot of similarities.
* having a bright, neutral base color for stadium also encourages micromapping of features within - which currently often look ugly against the strong dark green.
* having different colors for …

Change and unify colors for stadium/track/pitch to be less dominating

---

project.mml
project.yaml

Using `planet_osm_polygon` for admin labels while using `planet_osm_roads` for admin lines might lead to a mismatch between lines and labels where labels are rendered without lines. This PR changes the table to `planet_osm_roads` to match both parts.
before
after

fix possible admin label and line rendering mismatch

---

scripts/yaml2mml.py

This should keep newlines the same on Windows
Fixes #2153

Use binary mode for mml in yaml2mml

---

project.mml
project.yaml

originally reported by @mmd-osm in https://github.com/gravitystorm/openstreetmap-carto/pull/2142#issuecomment-233179715.
My analysis led to the outcome that ...
> I think the problem is that in planet_osm_polygon the text placement depends on the complete outline and in planet_osm_roads on the individual lines. While the winding order of polygons is defined and so two adjacent lines end up with different orientation in case of lines the same line might be shared and so the orientation is the same. That results in wrong text placement.
The only way I see to fix this and to fix the line and label mismatch is to switch all admin boundaries to `planet_osm_polygon`. Input on possible implications is welcome.
A release 2.41.1 might be necessary.

reverts #2142 as it led to wrong admin labelling

---

roads.mss

Resolves part of #2209 
Uses font size 10 at zoom level 14. Other zoom levels unchanged.
Alternative might be to drop rendering of this feature at z14.
Before:
After:

Font size 10 for junction names

---

roads.mss

Drop rendering junction=yes on z14 (clutters the map at this zoom level). Follow-up to #2241

Move junction=yes to z15

---

ferry-routes.mss

Switch to font size font size 10 for ferry routes at z13. Implements part of #2209 
Before:
After:

Ferry route names font size 10 at z13

---

landcover.mss

Small tweak for a playground area. Currently playground areas are too visible for me (they stand out in the city) and they are also too blue (a bit like pool). 
After the fix they are light green and are still visible on school and park areas (the most usual places they exist):
even when the icon is still not there:
but also work reasonably on other surfaces, like grass or residential area:
It's a standalone fix, but can be very useful if we change the water color to be lighter than it is currently (see https://github.com/gravitystorm/openstreetmap-carto/issues/1781#issuecomment-235450267).

Different color for playground

---

stations.mss

Minimal font size 10 for stations.
Before:
After:
Adresses part of #2209.

Minimal font size 10 for stations

---

openstreetmap-carto.lua

This is a PR against the lua branch.
Sport is a non-physical key, so it should always be combined with
another, physical key. That physical key should define whether the
object is a polygon or line. Since an object with a polygon key
and a line key will be treated as polygon, treating sport as line
by default is the sane default.
For example:
* sport=running, highway=footway should be treated as line. The
current PR accomplishes this, before it would be a polygon.
* sport=soccer, leisure=pitch should be treated as polygon. Nothing
changes here.
This resolves ... #854 but only after it gets merged into master.

Drop sport from polygon_keys

---

landcover.mss

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1197.
As originally proposed by @daganzdaanda, made 10% lighter with 5% desaturation. Lightening stops hinting that construction areas are more important than buildings and desaturation takes away the golden tint, which is currently overused in osm-carto, making also construction area more distinct than lightened-only version.
1) City landscape, comparison with bigger buildings
Before
After
2) City detail, comparison with buildings, trees and special buildings (tagged as place of worship)
Before
After
3) City detail, comparison with buildings and landuse=garages
4) City detail, buildings on construction area

Less dominant construction color

---

amenity-points.mss

Revised min. zoom for tourism=alpine_hut
This PR supersedes #2139 and #2294 specifically for the functionality to reduce the min. zoom to show the text name of alpine huts (tourism=alpine_hut).

Revised min. zoom for tourism=alpine_hut

---

water.mss

Rendering labels of rivers flowing through canalizations is currently somewhat ugly.
Here is an example:
http://www.openstreetmap.org/#map=18/49.05799/8.52062
Thus I made this trivial change to German style. Probably also of interest to upstream.

Do not label waterway inside tunnel

---

addressing.mss

minimal font size for adresses: 10
Unify rendering of addr:housename and addr:housenumber and have now always the same size at the same zoom level. Drop rendering at z17 (yet currently there are collisions, often no way_pixels available for making a better choise). Minimal font size of 10.
Contains a filter for z20. Now osm.org does not provide z20. Is it useful anyway or not?

Change font size and minimum zoom level for house numbers

---

roads.mss

This pull request proposes changing the look of no/private/destination access.
Currently, the dashes indicating that roads are not accessible are heavy and attract attention to private ways, instead of attracting attention away from them.
In addition, the colours are not intuitive to new users of the map.
This pull request attempts to make access restrictions not as visibly noticeable, while still preserving the information for users that need it. In addition, it aims to make the information more intuitive for a user that is not familiar with the map.
This pull request proposes:
* Gray dashes for roads with access=no and access=private
* Gray dashes for roads with access=destination
* A gray outline for footways with access=no and access=private
* A grayed-out outline for other paths with …

Change access rendering

---

landcover.mss

In https://github.com/gravitystorm/openstreetmap-carto/pull/2292 I didn't check that construction color is used also for brownfield and landfill. While I think construction (76k uses) and brownfield (64k uses) are somewhat similar and more popular, landfll (21k uses) is much different, since it has nothing to do with development cycle. So I think it would be good to restore stronger color only for this tag. 
Example of construction and landfill areas near each other:

Make landfill color different than construction and brownfield

---

water.mss

**Revised text size for lakes**
[Edited summary]
This PR proposes to scale up the font size for large water area labels (natural=water or landuse=reservoir/basin) used for lakes (currently they are all rendered with a fixed font size, using text-size: 12).
It supersedes and attempts to improve unmerged PRs #2139 and #2287 for the specific relation to the text size used for water areas.

Revised text size for lakes

---

addressing.mss
project.mml
project.yaml

Render both housenumber and housename if both are present. Same colour for all address-related features. A little bit of documentation.
Fixes #2328 
Fixes #735

Render both housenumber and housename

---

style.mss

Documentation for how we made the choise for CJK glyph style. With https://github.com/gravitystorm/openstreetmap-carto/pull/2349#issuecomment-248396392 there was yet a question related to CJK glyph style, so it would be good to document why the current code is as it is.

Document CJK glyph style choise

---

placenames.mss

* Margin breaks Mapnik 2 support
* Avoid-edges prevent rendering of London and other places on
metatile boundaries

Drop margin and avoid-edges attributes in placenames

---

amenity-points.mss

Nearly all shops are located in shopping streets or shopping malls,
close to other shops. Therefore, only a very small part of shops
is currently displayed with label on z17. In addition, these areas
are very crowded.
By only displaying shop labels on z18, z17 will appear less overcrowded.
The shop icons will still be displayed on z17.

Move shop labels to z18

---

INSTALL.md

The metapackage relies on recommends on 16.04, so the individual
packages need to be specified.
Fixes #2391 
Fixes #2397

Directly install individual Noto packages

---

project.mml
project.yaml

Which makes it consistent across metatiles. Idea by @imagico. Ref #2378.
I have not seen any visual changes but at least we now can rule out this factor as source for misplaced labels at metatile boundaries.

base placename direction parameter on geometry

---

CONTRIBUTING.md

Give brief guidelines for map icon submission.  Mainly points contributors to back to OSM wiki for more extensive information.
In my opinion, the repository is currently a little sparse in regard to this kind of information.

Add Map Icon Guidelines to Contribution Guidelines

---

landcover.mss

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1190.
The color definition is not absolute for now to make it easier to test modifications. When it'll be ready to merge, I will remove the "[WIP]" (work in progress) from the title.
After some testing I feel this color (lighten 8%, desaturate 5%) is the best on typical backgrounds:
z14 - it's still visible on the sport center and on the ground, but less than a forest, and small spots on residential area are not a problem now:
Before
After
z15 - pitches are less intense than a special building and secondary roads, now they are more or less like a regular buildings, which is good:
Before
After
z16 - when school areas are bigger, it's the same as with sport centres, and we have a special case, pitch on the residential area, …

Making pitch and track color less dominant

---

roads.mss

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2364.
When man_made=bridge shape is not typical, the name label can be placed outside the polygon, which is unexpected and confusing. Simple fix required just adding `text-placement: interior;` option. Thanks for the hint, @HolgerJeromin!
Before
After

Rendering the name of man_made=bridge inside the polygon

---

buildings.mss
project.mml
project.yaml

Technical follow up to https://github.com/gravitystorm/openstreetmap-carto/pull/2371 (can't reopen after pushing the code). Also related to #327.
This PR makes any building=train_station to be rendered as a major building and does not touch the railway=station tag (this one just has both tags):
z18

Making railway stations appear as major buildings

---

CARTOGRAPHY.md

I have started with a draft of putting together some design principles for this style that hopefully help contributors in the future to better understand the direction of development.
This first part contains two of three sections i structured this into.  These two are the description of the style purposes and a list of the main goals derived from these.  I plan to supplement this with a section with more specific guidelines on style decisions with - from my side - subsections on colors and zoom levels - which can be supplemented by others on further subjects like for example icon design.
This structure is meant to show that the specific principles listed are not arbitrary but are meant to serve the described goals which are followed to make the style serve its purposes.
Mostly i tried to …

Proposal for design goals and guidelines - part 1

---

.gitignore

Technical follow up to https://github.com/gravitystorm/openstreetmap-carto/pull/1578.
Causes git to ignore also `localconfig.js` file (not only `localconfig.json`).

Adding localconfig.js to gitignore

---

landcover.mss

Small variables cleaning in landcover.mss:
- color letters (hex) in lowercase
- sections names from big letter
- transport section created
- added ref to other use of the variable

Cleaning variables in landcover.mss

---

scripts/get-shapefiles.py

**Update get-shapefiles.py renaming project.yaml to project.mml**
Rename project.yaml to project.mml following https://github.com/gravitystorm/openstreetmap-carto/pull/2473

Update get-shapefiles.py renaming project.yaml to project.mml

---

project.mml

Add village and hamlet to capital-names and exclude these capitals from placenames-small. This currently affects Vaduz and Ngerulmud [as documented in Wiki](http://wiki.openstreetmap.org/wiki/Key:capital) (see also Talk page). This respects the index for places from #2408.
I originally did a Github commit comment with tests but this comment vanished when I rebased, which is a known gotcha. Better use PR or review comments.

Add village and hamlet to capital SQL query.

---

project.mml
stations.mss

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/645.
I guess we need to wait for a database reload to show also refs, but it's possible to render the name of subway entrances right now ([15k+ uses](http://taginfo.openstreetmap.org/tags/railway=subway_entrance#combinations)):
UPDATE: probably ref should be available, but is not in .stations - could somebody help me with it?

Adding ref for railway=subway_entrance

---

landcover.mss

This fixes the strong outlines as seen in https://cloud.githubusercontent.com/assets/5251909/20907746/5f006326-bb50-11e6-8ab6-2875a8e5ac75.png

Do not render camp_site and quarry outline until z13

---

project.mml

Small fix to make layers code more uniform, as discussed in https://github.com/gravitystorm/openstreetmap-carto/issues/2429.

Cosmetic fix for uniform layers code

---

style.mss

switch to Noto Naskh
Resolves #2485

switch to Noto Naskh

---

INSTALL.md

Obsoletes https://github.com/gravitystorm/openstreetmap-carto/pull/2521.
Enables https://github.com/gravitystorm/openstreetmap-carto/pull/2470.
Instructions for compiling this style using CartoCSS.

Proper API version for CartoCSS

---

CHANGELOG.md

Version 3 adds rendering of the "ref" tag for subway entrances. In earlier versions, these entrances were rendered with an icon only.

More accurate change log entry for subway entrance

---

openstreetmap-carto.lua
scripts/lua/test.lua

This code takes a stricter view on what a multipolygon is, and adds test coverage for relation handling.
I'd like to get some more eyes on this before merging to lua and reloading my test machine over the weekend. My test machine is currently finishing off an unrelated test import for some osm2pgsql stuff and will be free then.

Rewrite relation handling code

---

amenity-points.mss

IMO access=permissive is a valid tagging but should not be equivalent to private.
Example:
https://www.openstreetmap.org/way/4646264#map=18/51.91005/8.84213
Done this for all parkings, recycling, playground, dog_park
We dropped permissive rendering for roads with #682.
resolves #1634
superseeds #2512

Make permissive equivalent to access=yes and drop access=public

---

landcover.mss

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2449.
Split from https://github.com/gravitystorm/openstreetmap-carto/pull/2519. 
Renders clinic area the same as for the hospital (part of the code is already here since https://github.com/gravitystorm/openstreetmap-carto/pull/1565):

Add area rendering for amenity=clinic

---

project.mml

@TomH noticed differing labels between the lua branch and v3.0.1
While it's possible this particular example is from a myriad of other causes, having an unspecified ordering can lead to labeling problems at MT edges, or if using multiple servers, labeling problems at tile edges as well.
I did some artificial tests and this helps, but I don't have good screenshots.

Order road names to avoid metatile edge issues

---

project.mml

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1997.
SQL fix that prevents from rendering major buildings twice (as normal building and as a major building on top of that).

Fixing rendering major buildings twice

---

symbols/bus_stop.12.svg

Not yet ready to merge. The `<rect/>` element shouldn't be there, but without the icon changes size on the map.
I'm wondering if the rect is forcing the size and the bus part is smaller, so even though marker-width is 12px, the visible part is smaller. This strikes me as the wrong way to achieve that.
cc @nebulon42

Clean up bus_stop SVG

---

landcover.mss

fixes #2498, #2388.
This is also significantly weaker than previously to make sure the outline is not so prone to be confused with barriers, like for example here:
http://www.openstreetmap.org/#map=18/47.98378/7.82667

better outline color for societal amenities (hospitals, schools), adding missing outline for stadium/sports_centre

---

roads.mss

Similiar typography tuning for roads.mss (not for linear features like roads themself, but for labels that are rendered with horizontal lines): Minimal text size 10 and fine-tuned line spacing.

Typography for roads.mss

---

landcover.mss
project.mml

This removes rendering for `landuse=farm`, currently rendered like `landuse=farmland`.
`landuse=farm` is discouraged since 2013 and deprecated since 2014. There is a prominent warning on the wiki page and also the JOSM validator issues warnings about it.
[Taghistory](http://taghistory.raifer.tech/) shows a steady decline, but according to [Taginfo](https://taginfo.openstreetmap.org/tags/landuse=farm) there are still around 360 000 uses.
Removing it from the rendered tags shall speed up the re-tagging into either `farmland` or `farmyard`, but since there are still quite some uses there will be changes to the map. However, this is intended.

remove rendering for landuse=farm

---

landcover.mss

fixes #2135.
looks like this:
Should also reduce the incentive to abuse wetland=bog to wrongly map non-ombrotrophic wetlands.

changing pattern and adding base color for wetland=fen

---

project.mml
water.mss

fixes #2424.
Note this only removes the area rendering, correctly treating closed ways with waterway=canal as line features will depend on the database reload.  Current lua branch already has this covered:
https://github.com/gravitystorm/openstreetmap-carto/blob/lua/openstreetmap-carto.lua#L40

removing waterway=canal area rendering

---

amenity-points.mss
project.mml

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2505.
Rendering of amenity=arts_centre is the same as for the theatre, just one zoom level later (z17+):

Adding icon for amenity=arts_centre

---

buildings.mss

Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2094.
I see no reason to render airport terminals different than other major buildings:
1. It should be clear what are they from the context.
2. We use strong violet for industrial features (especially power stations, IIRC).
3. I'd like to unify the general look of all the transportation "stations".
Also sharing rule that all the buildings are rendered from z13.
Warsaw, z14:
Before
After

Unification of major buildings

---

aerialways.mss

Fixes #347 
This is a special case so it needs some explaining. This feature request was rejected first due to low usage. In this case usage is not really significant as it is a rare feature. There is at least one of those not far from where I live. Since we render other types of aerialways already it makes also sense to render this one, especially as leaving it out can lead to the weird situation that other aerialways are seemingly not reachable as in my example below.
Also there is tagging for the renderer going on as https://www.openstreetmap.org/way/31766480 illustrates. Under this circumstances I wanted to add this. Also it is mentioned on the aerialway Wiki page and it also has its own Wiki page. Given the rare occurrence of this feature I view this tag as established.
I chose the …

add rendering for aerialway=mixed_lift (same as gondola)

---

roads.mss

before
after
This also avoids situations where one part of the label can be placed and the other cannot due to some conflict with another object. Leads to simplified code too.

replace text-dy logic with combined name and ref rendering for motorway junctions

---

roads.mss

By looking at https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L1954 I think that the additional `tertiary_link` filter is redundant and can be removed.

remove redundant tertiary_link from road names

---

project.mml
roads.mss

Fixes #2477
Uses zoom level, size etc. of the respective road types. Also restricts the construction values we render names for to the types where we render highways and empty values of construction.
before
z14
z15
after
z14
z15

use parameters of road type for text rendering of roads under construction

---

INSTALL.md

Documentation update (font usage and download)
Resolves #2606

Documentation update (font usage and download)

---

amenity-points.mss
project.mml

This cleans up the overcrowded z17 significantly:
Before:
After:

Render most shops on z17 as dots only

---

project.mml
roads.mss

This makes the split between lowzoom (<9) and highzoom (>=10) clearer,
and improves performance of z9.
No change in cartographic output.

Move halo's to fill layer

---

INSTALL.md
fonts.mss

Our only current fallback font—Unifont—covers Unicode plane 0 completely. The coverage of plane 1 is not that good. And plane 2 is not covered at all.
Plane 2 is used for CJK characters that did not make in into the set of CJK characters in Plane 0. Plane 2 has currently 52 844 characters. Noto covers 2 238 characters of plane 2.
This PR introduced Hanazono as additional fallback font, and earlier in the list before Unifont. Hanazono covers almost all CJK characters up to CJK-ExtD. In plane 2, it covers 47 082 characters. CJK-ExtE (Unicode 8) stays uncovered. CJK-ExtF (to be released in Unicode 10 later this year) stays also uncovered. Hanazono is dual-licensed under a particular MIT-style license and the well-known SIL OFL. It is normally available as package on modern Linux …

Better font fallback beyond BMP

---

water.mss

Ref #488.
Waterway tunnel dashes might disappear depending on background. By using an additional line with land-color as base this does not happen anymore.
Original location of #488:
before
after
This would also apply to intermittent waterways:
before
after
This can have side-effects when a intermittent river is tagged with a riverbank. Depends if we view that as valid tagging combination.
before
after
Also stream tunnels over forests look a bit strange but there is likely some fine-tuning possible:

use land-color as background for waterway tunnels

---

INSTALL.md

With the use of lua, osm-carto no longer uses all the osm2pgsql defaults.

Update readme instructions

---

water.mss

remove leftover from background line for intermittent waterways

---

project.mml

Fixes #2626.
Needs carto >= 0.17, 0.18 is now our requirement, Kosmtik comes with 0.18 when updated, but forcibly sets the name attribute when not present. Fix under way: https://github.com/kosmtik/kosmtik/pull/242

remove deprecated and redundant layer name attribute

---

README.md

Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2666 and https://github.com/gravitystorm/openstreetmap-carto/issues/2490.
Small editing to make README.md up to date with v4.x.

Updating README.md for v4.x

---

RELEASES.md

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2612.
The problem was unencoded spaces in URL, which is used to pre-fill the form.

Fixing RELEASES.md markdown

---

INSTALL.md

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2255.
I have updated links and .shp names according to the current `get-shapefiles.py`.

Updating install documentation for manual shapefiles

---

INSTALL.md

Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2576.
I think user should have the easiest installation option visible right from the start. This should make all the problems with manual installation less severe.

Make Docker information more notable in INSTALL.md

---

.gitattributes

Adding .gitattributes to avoid that Git for Windows converts docker-startup.sh newlines to DOS, so that this script can run inside a UNIX container.
This configuration affects all *.sh files of the repository.
Tested with Ubuntu and with Windows.

Adding .gitattributes to Docker configuration

---

DOCKER.md

Fixing small problems with DOCKER.md. The most important one was 
> `docker-compose up` to run the style preview application
instead of `docker-compose up kosmtik`, because it was importing (probably the same) data file each time, which may be very time consuming.

Fixing Docker documentation

---

Dockerfile
scripts/docker-startup.sh

This code adds some plugins to make Kosmtik more usable.
I don't see why `.config` directory was created, because `.kosmtik-config.yml` seems to be used outside it, so I removed that line.

Adding Kosmtik plugins to Docker

---

.env
.gitignore
scripts/docker-startup.sh

Follow up to https://github.com/gravitystorm/openstreetmap-carto/pull/2679#issuecomment-313905873.
The only strange thing is that when there is no .env file, import fails, even though this file should be just created. Next time the import is invoked, everything works. That's why I marked it as a work in progress.

Fixing .env file creation for Docker

---

amenity-points.mss

Related to https://github.com/gravitystorm/openstreetmap-carto/pull/1881.
Airport labels are currently shown on top of icons, I'd like to unify it with other labels (bus stops, railway stations etc.).
Warsaw, z10
Before
After

Airport labels moved under icon

---

README.md

Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2666.
I think we're ready to drop v3 compatibility plans now and go on with v4.1.0 release soon. If that's the case, project documentation should reflect it.

Dropping v3 compatibility plans in README.md

---

amenity-points.mss
project.mml

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1143.
Simply moves aerodromes with access=private or lacking any of ICAO/IATA codes from z10-z14 to z11-z14. 
I was not able to properly add `aerodrome:type` tag to `project.mml` queries, but it would be good to filter also private types here. Still the effect is good enough for me:
**Full London area from Mapzen extract at z10** (click to see unscaled images):
Before
After
**Full Indiana area from Geofabrik extract at z10** (click to see unscaled images):
Before
After

Moving smaller airports to higher zoom levels

---

landcover.mss
project.mml
roads.mss
style.mss
water.mss

This PR changes the following:
* Landcover in z<12 is now less bright.
* Built-up landcover areas are now rendered more prominently in z<12.
* Unimportant roads are now white rather than gray.
* Water is now a brighter blue (thakns @kocio-pl).
* Low/midzoom roads are now rendered with bright halos.
This should improve the legibility and esthetics of the map. In particular:
* Roads, esp. primary roads, are now better legible on zooms 8-11
* Water areas are easier to recognize
* Minor roads on mid-zoom levels are rendered more clearly
* Residential areas are more prominent and easier to recognize

Improve mid-zoom levels and water color

---

landcover.mss

Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2094.
Currently we're using special color for rendering railway=station area, but it looks like a leftover when it was considered to be a building (like supermarket for example). In general I'd like to unify all transportation areas, but in this case I think railway/industrial color works better, as it is a railway area anyway.
The question is however if we want to imply a landuse color or not fill it at all (so the explicit landuse tagging is needed)? It's the same problem as with https://github.com/gravitystorm/openstreetmap-carto/pull/2700.
Gliwice, z17
Before
After

Changing area color for railway=station

---

CONTRIBUTING.md

Related to #2666.
Dropping v3 compatibility request, fixing URL and unifying titles.

CONTRIBUTING.md updates and cleaning

---

landcover.mss
project.mml

Related to https://github.com/gravitystorm/openstreetmap-carto/pull/2654.
Start rendering farmlands on z8+ instead of z10+. I don't want to touch lowzoom yet (https://github.com/gravitystorm/openstreetmap-carto/issues/2688), but when we start showing forests/woods on midzoom, we can also show the farmlands, because both are very popular and with color fading they enhance the background in a subtle way.
Full Poland extract (click to see unscaled images):
z8
z9 (converted to JPG to fit in the GitHub filesize limit)

Rendering farmland earlier on midzoom

---

symbols/grave_yard_generic.svg

Fix for https://github.com/gravitystorm/openstreetmap-carto/pull/2714#issuecomment-321981096.
Now it's symmetric rendering:

Fix generic cemetery symbol geometry

---

project.mml

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1770.
No changes in rendering. I've just checked that rendering in low zoom still works.

Removing ordering in landcover-lowzoom

---

amenity-points.mss
landcover.mss

Related to #2654, follow up to #2722.
Another landuse type that can be rendered on midzoom on z8+ (instead of z9+), just like the forest and farmland, because there are already places where it can be quite big (=visible even on the low zoom scale) and it helps diversity.
@rrzefox: Could you add this patch too and check the performance implications?
Examples  (click to see unscaled images):
Egypt, z8
Africa, z8 (converted to JPG to fit in GitHub filesize limit)
[-> link to big image](https://user-images.githubusercontent.com/5439713/29237544-a19b77fe-7f20-11e7-956c-9b9129ee4e42.jpg)

Rendering natural=sand earlier on midzoom

---

amenity-points.mss
project.mml
symbols/plaque.svg

Related to https://github.com/gravitystorm/openstreetmap-carto/issues/1560.
With hstore we can finally push such small memorial objects as plaques to other small amenities. In my city there are so many of them, that I skip mapping them to not clutter the map. 
In this code I've used icon from osmic, because it's depicting plaque.
Warsaw
**z18**
Before
After
**z19**
Before
After

Move plaque rendering to higher zoom levels

---

amenity-points.mss

Resolves #2358 (last part is solved by this PR)
Before:
After:

Better line spacing

---

roads.mss

This improves rendering on mid zoom levels by smoothing up the highways.
Before:
After:
This becomes especially important after implementing something like https://github.com/gravitystorm/openstreetmap-carto/issues/2194#issuecomment-265266841:
Before: 
After:

Do not render link roads until z12

---

.dockerignore
DOCKER.md
Dockerfile.db
docker-compose.yml
scripts/docker-startup.sh
scripts/tune-postgis.sh

Should fix #2698 in a very good way.
This will:
- Giving user a good out-of-a-box PostgreSQL / osm2pgsql turing.
- ... but still allow user to supply args during their first import;
- ...then generating `.env` based on args above.
Also fix the document about the behavior.
There are some steps to see how it just works, you can try:
1. For the first time, running `docker-compose up import` without any custom args
2. Check `.env`, change some value, then destroy all volumes using `docker-compose down -v && docker-compose rm -v` (PostgreSQL turnings will only applied once the volume is created)
3. Run `docker-compose up import` again to see whether settings from `.env` applied
4. Destroy volumes again
5. Prepend args different from those in `.env` in import command, like stated in …

Bullet-proof Docker variable turning with PostGIS.

---

project.mml

There is currently no ordering for the roads-low-zoom layer. The issue is most noticeable at zoom 9, the highest zoom level where the roads-low-zoom layer is used.
Applying #2732 to roads-low-zoom clears things up.

Add ordering to roads-low-zoom

---

project.mml
roads.mss

This will fix #505.
Rendering railway labels will make maps in some railway-centric area better, especially Japan.
I did some copy-and-paste work and make this pull request, hoping to get some feedback about how the label should be styled.
My two cents:
- Should the style of railway lines be changed to match the label?
- Subway under highways is mostly not rendered. Can we render that?
By following is some rendered images of the initial commit in Tokyo, Japan:

Render railway labels

---

DOCKER.md

subtask of #2291 
I think that `Quick start` section should be self-contained and require no digging in other parts of documentation (especially with "Read on below to get the details.").
It reduces confusion - for example at start I missed fact that `openstreetmap-carto` is obviously necessary. Info how to see anything is currently hidden in the later part.

Make installation process more explicit

---

roads.mss

Resolves #2731.
Reverts unimportant roads color from white to @residential-casing color (as in v4.1.0).
Before revert:
After revert:

Revert white color for unimportant roads

---

amenity-points.mss
project.mml

Atom removed these excess spaces in null edits. Committing to avoid
these changes masking real changes and hence rendering audit more
complicated

Null edit to remove excess spaces as identified by Atom

---

landcover.mss

Null edit in Atom that removed excess spaces.
To prepare file for edit so that code changes are clearer

Null edit to remove spaces

---

placenames.mss

Resolves  #2793.
Typo in z12+ progression.

Fixing village label size progression

---

roads.mss

This improves rendering on mid zoom levels by smoothing up the highways.

Do not render link roads until z11

---

amenity-points.mss

While natural=tree progression is nice in theory, in practice single trees do not belong to z16-z17 when [tagged fully](http://www.openstreetmap.org/#map=16/52.2435/20.9537):
z16
Before
After
z17
Before
After

Moving natural=tree to higher zoom

---

amenity-points.mss

As proposed by @math1985 at https://github.com/gravitystorm/openstreetmap-carto/pull/2730#issuecomment-322591915 here is a PR that unifies the line wrap for amenity points over all zoom levels. I think that indeed it makes sense, because amenity points are rather small (at difference to other features like cities or lakes that have larger line wrap at higher zoom levels because they are much bigger), and anyway the difference is not big compared to the current code. This PR will make zoom-in/zoom-out less surprising, because you get always the same line wrap for amenities.

Same line wrap of amenitys for all zoom levels

---

project.mml
water.mss

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2557.
Gdańsk, z17
Before
After

Rendering name for waterway=dock

---

amenity-points.mss
project.mml

Resolves #318.
Name selection in SQL was removed because we're not displaying names for such POIs.

Moving emergency phone to a new tagging scheme

---

amenity-points.mss

Follow up to @giggls https://github.com/gravitystorm/openstreetmap-carto/pull/2765#issuecomment-323748719.
Embassy icon is rather kind of office (like town hall) than transportation amenity (like bus stop), so I prefer rendering it as such.
Before
After

Changing embassy color to amenity-brown

---

Dockerfile
Dockerfile.import

Resolves #2755.
There are different ways to skin this cat, but this is the easiest and fastest for us to use. I've changed the import container distribution too just to be consistent with a kosmtik container.

Fixing line wrapping bug in Docker

---

project.mml

On low zoom levels (up to z9) it is not important which road crosses
on top of the other. Instead, it is important to always show important
roads on top, so lower classes roads do not hide motorways.

Do not order low zoom roads by layer

---

amenity-points.mss
project.mml

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/267.
Simply removing support for deprecated tagging scheme and adding support for the new one (much more popular already).
I need some help, since it works for points, but not for ways. Another thing is deciding on rendering names - 3% have them, but I suspect most of them are the names of the highways.

Moving ford to a new tagging scheme

---

amenity-points.mss

Follow up to #2765 and https://github.com/gravitystorm/openstreetmap-carto/pull/2786#pullrequestreview-61696327.
This PR is **just a code change** (new variable is created with the same color as before), but it makes it easier to make gastronomy POIs look different. 
We are currently using amenity color for pretty much everything:
- small amenities (waste basket, picnic table) 
- public offices (police station, town hall)
- culture and entertainment (library, cinema)
- gastronomy (restaurant, bar)
- memorials and artworks
We don't have to use different colors for all of them, but creating such categories would make POIs more customizable.

Gastronomy POI category

---

project.mml

Resolves #53.
Follow up to #2740.
A basic testing was made to make sure rendering is not just broken after this.

Removing z-ordering in landcover

---

landcover.mss
project.mml

Irregular wave pattern for natural=sand would make it visibly different from farmland (and also from beach). Initial pattern shape and color are just proof of concept.
Egypt
z10
z13

Adding pattern for natural=sand

---

amenity-points.mss

Follow up to #2824.
I will push groups one by one because features are clustered so it's easier to break something while making big cleaning. Basic rendering test shows that this group looks like before and changing color works for included elements too.
Memorials (with artworks)
- monument
- obelisk
- memorial
- memorial plaque
- artwork
I have moved archaeological site to another cluster, so it can be included in a "culture" group.

Memorials POI category

---

amenity-points.mss

Follow up to #2824.
This is a bit more complex PR, because it's not only about making another POI color group sharing the same variable name, but it's also icon/label unification, fixing part of the problem described in #1355, #1794 and https://github.com/gravitystorm/openstreetmap-carto/pull/2268#issuecomment-237856186.
While amenity brown is overused, leisure-green (dark leisure-related color) is underused currently. It's used for many labels and only for some icons - namely both golf-related ones. I have changed the color of playground, water park and dog park icons to match their label color (leisure-green). I have not tried to match zoom levels for labels and icons nor was I touching other aspects of text.
Here's the result:
Before
After
Before
After
Before
After

Leisure POI category

---

amenity-points.mss

Lighthouses are currently rendered in transportation-blue.
After:

Move lighthouse icon and label to man-made color

---

amenity-points.mss
landcover.mss
project.mml

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/887.
Warsaw, z18
Before
After

Rendering man_made=works

---

ferry-routes.mss

This makes the labels look more similar in color to the lines they belong.
Before:
After:
With the new water color, contrast should be strong enough anyway.

Drop halo from ferry labels

---

roads.mss

Unfortunately it seems like we do need link-roads on z10, for
junctions like
https://www.openstreetmap.org/#map=10/51.8748/4.3918 .

Reinstate link-roads on z10

---

admin.mss

Due to the coastline paradox, dashed lines for borders don't work
well on low-zoom: strongly curved borders appear solid instead of
dashed. Also, solid dashes generally are too busy for the crowded
z5-7.
This PR makes regional boundaries (admin_level=4) solid instead of
dashed up to z9.
To prevent the borders from getting too strong, they are also made
thinner.
Before/after:
z4:
z5:
z6:
z7:
z8:
z9:

Make regional admin borders solid instead of dashed

---

landcover.mss

This starts showing zoos and theme parks from one zoomlevel before
they are large enough to get a name.
Example of theme parks of the size that will disappear now:

Hide tiny zoos and theme parks

---

RELEASES.md

Fix a trailing `.` and reference to a branch we're no longer using.

Minor release instruction fixes

---

project.mml
roads.mss

More progress on #2046. The cartographic changes are minimal and involve some strange real-world situations.
This is done as part of road layer simplification, but also fixes a few layering bugs showing up where there are aeroway bridges, and some casing width problems with invisible bridges.
There are no changes to the typical airport
(left v4.2.0 on osmf servers, right this PR)
The weirder situations are bridges
17/47.92228/-122.27635
16/33.6224/-84.4291
Where there is a road crossing a runway (e.g. Gibralter) the runway will remain rendered on top of the road.
There is one case of a runway tagged as a tunnel in OSM where the runway goes through a mountain [in North Korea](http://www.openstreetmap.org/#map=14/39.0937/127.4091), and that case will remain unhandled and rendered like a …

Move aeroways to their own layer

---

amenity-points.mss
landcover.mss

The area of a bare rock can be substantial - and lack of overlay pattern doesn't help to recognize what it is.
[Area in Libya](http://www.openstreetmap.org/way/138017567)
z8
Before
After
z9
Before
After

Rendering natural=bare_rock earlier

---

addressing.mss
project.mml

This branch implements rendering of addr:unit tags on ways (buildings) and nodes (entrances etc.), as discussed in issue #2488 
The image below, rendered from http://www.openstreetmap.org/#map=18/60.16315/24.87713 shows rendering of addr:unit with addr:housenumber on buildings and without addr:housenumber on entrances.

Render addr:unit

---

project.mml

Fixes #2886 and I suppose addition parenthesis won’t make any harm on other PostGre versions or setups.

Fix SQL problem with some PostGre versions

---

amenity-points.mss
project.mml

Resolves #484.
I'm not 100% sure about rendering names for ways, it's safer to skip it, since it's not clear if name label belongs to a slipway or a highway.

Adding support for slipway ways

---

project.mml
water.mss

Resolves #1604.
Closes #2864.
Test shows that changing pixel query factor from 0.01 to 1 probably does not make visual difference (or the change is subtle), but improves performance a lot and we can reasonably render all the water areas from z0. For details see discussion in #1604.
Only water layer:

Start showing water areas from z0

---

addressing.mss

Better minimal distance between housenumbers
The current distance is too small. Sometimes you cannot distinguish the individual housenumbers on est-west-roads (see bottom-right on the screenshot).
Before:
After:

Better minimal distance between housenumbers

---

amenity-points.mss
landcover.mss
project.mml
symbols/shop/marketplace.svg

Resolves #751 using icon number 5.

Marketplace rendering

---

INSTALL.md
fonts.mss

Use Noto Sans Arabic.
With the recent release of Noto, there is now a true “Sans” (=low constrast) arabic font available. It seems Naskh-like, but because it’s Sans, it fits much better with the rest of scripts and the styling is nevertheless Naskh-like. It is a little bigger with more spacing, what should improve legibility:
Before:
After:
As this release is not yet available as Ubuntu package (and therefor OSM servers unlikely to provide it right now), the current Naskh style is kept as fallback.
This PR contains now also code for Bold variant of Arabic and fallback.

Use Noto Sans Arabic

---

amenity-points.mss

Resolves #1448.
Island names are currently rendered on z7+, but they should be rendered on z4+ (as early as possible, but not compete with country labels on z3) and islets also 3 zoom levels earlier.
@rrzefox: Could you test this patch on your server?
Nunavut (Canada) example
z4
Before
After

Show island and islet labels earlier

---

buildings.mss
project.mml

Part of a transport unification effort, related to #2094 and #2763.
We have no unified solution for transportation areas in practice, but they all can have station/terminal. I'd like to make them all look similar, because for the passengers this is the most important building on such area, no matter what kind of transport is involved.
[Example aerial station](http://www.openstreetmap.org/way/267743094)
z18
Before
After
[Example public transport station](http://www.openstreetmap.org/way/97985328)
z18
Before
After

Showing all stations as major buildings

---

stations.mss

This enables text-wrap for station labels, in line with other POI labels.
Before:
After:

Introduce text-wrap for stations

---

USECASES.md

Looking up city location is listed as z5 activity

make USECASES more consistent

---

stations.mss

Resolves #2918
Use @standard-font-size in stations.mss whereever variables are also used for wrap width and line spacing. As wrap width and line spacing depend on the font size, this keeps together the values that are used together and interact together…
Because railway stations use different font sizes on different zoom levels, switching here to absolute values instead of variables for all (font size, wrap width and line spacing).
Only visible rendering difference should be for railway stations on zoom levels ≥ 15.

station typography

---

amenity-points.mss
project.mml
symbols/bunker.svg

Adding rendering for popular military/historic POI military=bunker - it has 35 251 uses and a [wiki page](https://wiki.openstreetmap.org/wiki/Tag%3Amilitary%3Dbunker).
Reusing cave entry icon, but with amenity brown color, because it looks like a solid shelter. Examples:

Add rendering for military=bunker

---

USECASES.md

maybe for other countries internal division is also useful from z5 - in that case it also should be mentioned

mention U.S states in usecases

---

admin.mss
project.mml
roads.mss

* Render roads from z6 instead of z5
* Render national parks from z8 instead of z7
* Render railways from z8 instead of z7
This is in line with the discussion on use cases and USECASES.md.
This contributes towards #2925 and #2688.

Clean up low-zoom levels

---

landcover.mss

Make parking gray instead of yellow

---

amenity-points.mss

* Labels for masts and water towers are now the same color of dark gray
as mast/water tower icons, rather than the current black color.
* Windmill icons are now rendered in man_made gray rather than black
Before:
After:

Fix color for man_made icons

---

ferry-routes.mss
project.mml

This moves the minimum zoomlevel of ferries from zoomlevel 7 to 8.

Move ferries to zoomlevel 8

---

landcover.mss

Resolves #2956.
This should make the use of green backgrounds more consistent:
- `landuse=recreation_ground` and `leisure=recreation_ground` should look the same and use leisure green
- `leisure=garden` should use park green
[Update:] `leisure=common` changes are reverted (needs additional discussion)
landuse=recreation_ground
Before
After
leisure=recreation_ground
Before
After
leisure=garden
Before
After

Better shades for recreation_ground and other green areas

---

project.mml
roads.mss

Make them visible from z11, but not have them dominate the map.
Involves a colour change the also affects other zoom levels.
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2965 .

Bus Guideways

---

landcover.mss

Now that we use light green for different small leisure areas, we could use it also for big ones, as they typically don't overlap. 
That unification would also offload societal_amenities color a bit (so we have less problem defining what it really is) and tie green color closer with the physical activities, which makes the system more predictable.
Examples in Warsaw (with different landuses around):
Before
After
Before
After
Before
After
Before
After

Change sports_centre and stadium color to green

---

admin.mss

With this commit, national park boundaries will be shown from the
same zoomlevel and size as their label, effectively eradicating
small unlabelled national parks from the rendering.
Such small national parks seem to contribute to a crowded feel of
the map in the areas and zoom levels where they occur.

Show national park boundaries from higher zoomlevel and larger size

---

project.mml
shapefiles.mss
water.mss

We don't render other landcover at z6/z7, and the glaciers, especially in
the Alps, currently attract too much attention.

Render glaciers and icesheets from z8 instead of z6

---

water.mss

On zoom levels 0-7, don't render small water areas (smaller than 32px).

Do not render small water areas on low zoom

---

amenity-points.mss

Related to #1745.
Bicycle and motorcycle parkings are usually quite small comparing to car parkings, about 70% of them are tagged as nodes - most probably because they are small in reality. Especially bicycle parking icons tend to clutter the space, because there can be many of them on not too big urban area.
Another factor is that z17 is generally overused, even after moving shop icons later (see #2945).

Push non-car parking icons to higher zoom level

---

.travis.yml
INSTALL.md
landcover.mss
project.mml
scripts/get-shapefiles.py
shapefiles.mss

Currently, we use VMAP0-data instead of OSM-data to indicate built-up areas
on zoom levels 8 and 9. This PR replaces the VMAP0-data with the OSM
landcover data.
Resolves #256.

Replace VMAP0-data by OSM-data

---

landcover.mss
project.mml

Related to #2087.
I think it's safe to add community_centre (#506) and social_facility (#1295) as societal amenities - with a light yellow background.
I would also like to add arts_centre, since this is sometimes similar to community_centre, but I'm not sure if this would be accepted - what do you think about it? We don't have a clean, generic solution for lot of "campuses" and social services, so I prefer to make smaller steps where this seems quite consistent rather than try to solve as much as it's possible.
amenity=social_facility 
Before
After
amenity=community_centre 
Before
After

Yellow background for community_centre and social_facility

---

INSTALL.md
fonts.mss

Update Noto to next version “Phase III”
What this PR does:
- Currently we use the UI version only (!) for the base font. Apparently the UI version was identical with the non-UI version, and will not be part of Phase III. So we should be prepared and switch the base font to the non-UI version. Resolves #2908 
- The current font release provides now some more scripts as bold face. These have been added. (Cherokee, Symbols)
- The current font release provides now some more new scripts. These have been added [except Anatolian Hyroglyphs because this is a historic script]. (Adlam, Adlam unjoined, Osage, Symbols2)
- The current font release provides now some more scripts as UI version. These have been added. (Sinhala)
- Where a UI version is available, the non-UI version is now _always_ in the …

Update Noto to Phase III

---

project.mml
roads.mss

Fine-tuning of bridge labels
Now the names of bigger bridges are preferred over the names of smaller bridges. The deprecated `text-min-distance` has replaces by a (slightly bigger) text-margin to avoid confusion with labels that are too near from each other. And margin and halo now scale smoothly with increasing text size.
Before:
After:
Before:
After:
Before:
After:

Fine-tuning of bridge labels

---

amenity-points.mss
project.mml

Resolves #847 (I guess, because this code is broader).
Only recycling centres (11k+ uses) will stay on z17+, all the other recycling features are supposed to be small or less important - including very popular recycling_type=container (107k+ uses) and all the other non-standard values.

Move small amenity=recycling bins to z19

---

INSTALL.md

"Additionally you need some shapefiles." reworded and moved to correct directory
explain why shapefiles are needed
explain what script is doing once
new version should be shorter and give all info of the current version

simplify information about shapefiles

---

project.mml
water.mss

Resolves #2095.
Tag seasonal has basically two values used - yes and no (~96% of 147k uses), but there are also others, like spring or similar. I think it's safer to treat every value other than "no" as a sign, that there is some seasonality, and this code reflects this choice. 
Of course we can also render just some list of values (with seasonal=yes of course), but it's hard to tell what to include exactly. Originally it was proposed to render just "yes", but this is not binary concept.

Rendering seasonal waterways as intermittent

---

landcover.mss
project.mml

Showing natural=heath on z8+ (instead of z10+) gives England nature reserves a context:
z8
Before
After
z9 (click to see full images)
Before
After

Move natural=heath earlier

---

addressing.mss
buildings.mss
project.mml
symbols/corners.svg
symbols/rect.svg
symbols/rectdiag.svg

Render entrances starting at z=17. The "main" and "staircase" entrances are rendered with a square marker, the "service" entrance with a circle (starting at z=18) and other entrances with a disc.
Three levels of marker brightness reflect the access permissions of the entrance. Darker color means more permissive access. The "main" entrances are dark by default. The access tag modifies the brightness such that access="yes" and "permissive" set the marker to darkest and access=no to the lightest colour. Entrances with other access tag values have intermediate brightness.
Exits, such as entrance=exit and entrance=emergency are not rendered.
Address label text-halo-radius is increased at z>=18 to improve readability of labels on top of entrance markers.
**Examples:** …

Render entrances.

---

amenity-points.mss

Resolves #2915.
[Example place](https://www.openstreetmap.org/#map=19/52.11688/21.08482) with both `tourism=picnic_site` and `leisure=picnic_table`:
Before
After

Changing tourism=picnic_site icon colour to green

---

amenity-points.mss

Related to #1884.
Emergency phones are really small scale, special features and I'm not even sure if they belong to general map - probably not, but even if they do, they should be rendered later, because proper tagging results in z17 clutter:
[Example place on z17](http://www.openstreetmap.org/#map=17/41.30962/-72.92796):
Before
After

Move emergency=phone to higher zoom level

---

landcover.mss
project.mml

Follow up to #2981, related to #2985.
With recent changes with leisure backgrounds, `societal amenities` are better defined and I think amenity=arts_centre is a good candidate to be included, since it is similar to amenity=community_centre.
[Example location](http://www.openstreetmap.org/#map=19/52.16103/21.21327):
Before
After

Yellow background for amenity=arts_centre

---

project.mml

This PR moves rendering the tourism-boundary layer under the barrier layer.
Barriers on tourism-boundaries (currently zoo, theme_park) are not visible. Here is a mixture of fenced and unfenced boundary - try to figure out.  Hint: bride is unfenced, SW and NE corners are fenced. 
There are two reasons:
1. tourism-boundary is rendered in a higher layer than barriers
2. the current outer line of the tourism outline (a/line) is relatively dark brown. As it uses opacity=0.5 the barrier shines weakly through, but this is barely noticeable since barrier uses a very thin (width=0.4) grey (```#444```) line. 
This PR only fixes reason 1. The effects are currently marginal, however the fix is a prerequisite of working further on outlines while keeping barriers visible, see drafts in #2290, #2704, …

Fix invisible barriers on tourism_boundary - step 1

---

buildings.mss
project.mml

Nodes with access=yes|permissive were rendered as brown circles at z=19
due to overly general entrance rendering rules. Tighten the entrances
layer code to apply only to entrance nodes. Fixes #3043.

Fix rendering bug (#3043) with access=yes|permissive tags.

---

scripts/docker-startup.sh

Slim mode uses temporary tables, so running the process takes more disk
space, while less memory is used.
This resolves #2911.

Run osm2pgsql in slim mode

---

amenity-points.mss
project.mml
symbols/waste_disposal.svg

Resolves #419.
As this feature is both popular (54k+ uses) and small scale, I choose the least obtrusive rendering possible. 
The icon is bigger than waste basket, since in reality it is larger (standard 14 px matrix instead of 10 px), but otherwise they are rendered in a similar way: on z19+ with low priority. I also render only nodes to avoid rendering icons on waste disposal sheds. Nodes are much more popular so this means rendering of 95% such objects.
There might be some extreme cases mentioned in a discussion (https://github.com/gravitystorm/openstreetmap-carto/issues/419#issuecomment-193307736) where there are a lot of such sheds, but tagged as nodes, but this might be solved by retagging as `building:part=*` area (which is more precise). I also added dimmed rendering for access …

Adding rendering for amenity=waste_disposal

---

amenity-points.mss
project.mml

Resolves #3052 
Add barrier=log to the non-opening barrier types 'bollard' and 'block'.
z19 before/after (Kosmtik):

add barrier=log like block

---

amenity-points.mss
project.mml
symbols/fort.svg

Resolves #2871.
Icon design is kind of a blend of https://github.com/gmgeo/osmic/blob/master/tourism/castle-fortress-14.svg and https://github.com/gmgeo/osmic/blob/master/tourism/fort-14.svg, which makes sense, since fort is similar to castle (newer form), but its icon in Osmic is not clear for me at 14 px (![fort osmic](https://user-images.githubusercontent.com/25656654/35795068-4133b0a2-0a58-11e8-89a0-87530f7ee8dd.png) ).
Rendering from z16 like monuments for example, because they are rather alone by design so it shouldn't clash with other objects on the map. It also takes lower priority than museum icon (like [here](https://www.openstreetmap.org/way/37014114#map=16/52.4155/16.8728)), which is good in my opinion.
[Example on the node](https://www.openstreetmap.org/node/710620121): …

Adding rendering for historic=fort

---

amenity-points.mss
project.mml
symbols/shrine.svg

Resolves  #131.
It seems that we can render shrines from z17, the same as crosses, because it doesn't look too bad even in this extreme example (see https://github.com/gravitystorm/openstreetmap-carto/issues/131#issuecomment-142845653):
Another, [much more common example](https://www.openstreetmap.org/node/4281335169#map=17/52.17459/21.04477), where the religion is christian (in the example above shrines lack `religion=*` tag) - we also have the name (30% shrines have it too):
The difference between christian and generic shrine is subtle, but it's always good to promote diversity if possible (it's not always the case).

Adding rendering for historic=wayside_shrine

---

CONTRIBUTING.md
project.mml

Fixes #3077.
See [the precedence table](https://www.postgresql.org/docs/9.3/static/sql-syntax-lexical.html#SQL-PRECEDENCE-TABLE): `IS` is higher than `(any other)`, which includes `->`.

Fix operator precedence for hstore queries

---

amenity-points.mss
project.mml
symbols/toll_booth.svg

Adds a toll booth symbol. Based on the icon of @MaestroGlanz, but without the right bollard (because at 14×14, with the bollard it looks to me a little bit like a dripping oil can). Some small geometry adjustments.
Resolves #958 
To discuss:
- Zoom level: 16?
- barrier=toll_booth on areas? JOSM and iD have a preset for both, points and areas. The wiki allows it on points and areas (right box on the wiki page), but at the same time, the wiki description says _“The node should be on the highway the toll applies to, in order to support routing decisions.”_ and doesn’t describe a correct mapping on areas. Actually about 5% of the toll booth objects in the database are areas – most of them have also a `building=*` tag.
- Between ¼ and ⅓ of the toll booth objects have a name. Should this be …

toll booth symbol

---

project.mml

Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2203.
Rendering the same as other `roads_area_text_name` objects.
Warsaw, z16 - two squares which are not simple footway or pedestrian areas:
Before
After

Adding place=square name rendering

---

INSTALL.md

Mention that, if Mapnik is being used programmatically, the map should be loaded in non-strict mode.

Mapnik non-strict mode

---

DOCKER.md

update docker.md with requirements and troubleshooting from last night's installation experience.
Trying to cover different host OS, while experience is from MacOS.

Docker.md improvements, requirements and troubleshooting

---

amenity-points.mss

Resolves #2787.
Resolves #3081.
Fixing code to avoid rendering artifacts. Some types haven't been reported, but when the problem is known, it was easy to spot examples. Railway crossings added to make the code more consistent.
[Mini golf, guest house](https://www.openstreetmap.org/#map=18/54.43010/-2.96525)
[Golf](https://www.openstreetmap.org/#map=15/45.5906/-122.6432)
[Apartment](https://www.openstreetmap.org/#map=19/52.26586/20.99200)
[Bus station](https://www.openstreetmap.org/way/485181612#map=18/51.39249/21.15921)
[Chalet](https://www.openstreetmap.org/way/537467185#map=18/49.36841/22.43469)

Fixing SVG icons artifacts

---

amenity-points.mss

Related to #1745.
This change moves the toilets to higher zoom levels, because in well mapped areas they compete with other amenities like shop or cafe. Also this is rather a short-distance amenity, so lower zoom levels are not relevant here.
The problem is that we don't even know if they are standalone amenities or just a part of some other amenity. So I guess that toilets with access for everyone ("yes") or paid ("customers'" or "destination") are more important and most probably standalone, but status of the rest (including "permissive" and lack of the access tags) is not clear and they are probably less important. 
[Louvre example](https://www.openstreetmap.org/#map=17/48.86141/2.33593) (click the images to view full size)):
z17
Before
After
z18
Before
After

Move amenity=toilets to higher zoom levels

---

landcover.mss

Resolves #3022.
Green areas redesign (#2964) didn't work too well for gardens. It seems that garden is a very wide concept, so it can be a small residential green area, something like farm, something like park (including public botanical gardens), also a more precise version of village green.
Therefore a more subtle change would be better - something like grass (general mild green) but with a pattern that shows that there's usually something more growing and it's human curated (hence regular pattern from plant nursery). I also opt for 60% opacity for the pattern, since I don't like the home gardens to stand up too much and also because the original pattern color has lower contrast because the background is darker.
Examples:

Making gardens to use grass color with plant nursery pattern

---

shapefiles.mss

Before:
After:
Still needs testing on more realistic data.

Give oceans outline and simplify shapefiles on z0-7

---

landcover.mss
project.mml

[Example of natural=grassland](https://www.openstreetmap.org/#map=9/51.3906/67.5536) shown from z8 (instead of z10+, as it is currently). Maybe also meadows could be visible there, but not the natural=grass, since it is intended for smaller grass areas.
z8
z9

Move natural=grassland and landuse=meadow earlier

---

amenity-points.mss

Resolves #2170.
Replace greenish hardcoded colour to opacity value.

Change label colour of private parking

---

amenity-points.mss

Follow up to #3057.
Small fix to make label rendering of [danger area without landuse=military](https://www.openstreetmap.org/way/173480188) still easy to recognize (hence dark pink again) and compatible with area labels rule (hence slanted):
z11
Before
Current master
After

Make military=danger_area font dark pink and slanted

---

CHANGELOG.md
openstreetmap-carto.lua
scripts/lua/test.lua

This was causing objects with natural=cliff or natural=tree_row to be incorrectly processed.
Fixes #3084
This does not require a MAJOR release and can go into the next 4.x release. It could even go into a patch release since it's a bugfix. The schema hasn't changed, previous code wasn't producing output that matched the target schema.
Should we attempt to add some SQL for a migration? It's likely to be reasonably long because the column lists are very long.
I'd probably write something along the lines of
```sql
WITH areas_deleted AS (
DELETE FROM planet_osm_polygon
WHERE "natural" IN ('cliff', 'tree_row')
AND NOT (tags ? 'area')
AND osm_id > 0
RETURNING * )
INSERT INTO planet_osm_line
SELECT
osm_id, access, "addr:housename", ..., 
tags,
(ST_Dump(way)).geom AS way;
```
Given the minor …

Fix duplicate key in linestring_values table

---

roads.mss

Fixes #2224
before:
and added to the construction tags gives this:

Issue #2224 Construction steps

---

amenity-points.mss
project.mml
symbols/advertising/column.svg

Fixes #3002 
From https://www.openstreetmap.org/#map=19/45.51028/-73.61213 (node):
Z19:
Z18:
From https://www.openstreetmap.org/#map=19/48.53969/2.65847 (way):

Adding advertising=column icon

---

project.mml
water.mss

Rendering big bay labels is currently missing, notable example is [Port Phillip Bay](https://www.openstreetmap.org/relation/1221199#map=9/-37.9962/145.0923) in Australia:
Using Mapnik 3.0.15 (currently in Kosmtik):
z8
z9 (probably eclipsed by a town name)
Mapnik 3.0.19 (latest release):
z8
z9 
Related to #2068.

Adding rendering for big natural=bay

---

amenity-points.mss

Resolves #2020.
I think moving from z16+ to z17+ should be enough:
[Standard example](https://www.openstreetmap.org/node/3404845697#map=16/52.2216/21.0927):
z16, before
z16, after
z17
[Extended example](https://www.openstreetmap.org/node/2730785546#map=16/52.1516/21.0551):
z16, before
z16, after
z17

Move highway=mini_roundabout rendering to higher zoom level

---

landcover.mss
project.mml

Resolves #428.
It adds visual clues for bigger parking areas. It's rendered the same as parking, but without "P" letter and probably without name, I think z18+ is good enough. This tagging scheme is used [118 468 times](https://taginfo.openstreetmap.org/tags/?key=amenity&value=parking_space).
[Example 1](https://www.openstreetmap.org/#map=19/52.30362/21.05551)
Before
After
[Example 2](https://www.openstreetmap.org/#map=19/52.25835/20.99361)
Before
After

Adding rendering for amenity=parking_space

---

INSTALL.md

This commit updates PostGIS website link from https://postgis.org to https://postgis.net/

docs: Update PostGIS website link

---

project.mml

A fix triggered by finding this bug: https://github.com/gravitystorm/openstreetmap-carto/issues/2440#issuecomment-377272725.
Objects with no area/outline rendering should not be selected in the landcover data layer. It might go unnoticed most of the time - for example it's hard for me to imagine firepit area with any kind of background, like grass - but if this area is tagged also with something using landcover features, it can lead to lack of the background/outline of the second feature.

Removing objects without background/outline from landcover data layer

---

RELEASES.md

Related to #2927.
Small documentation fix - let's use "OpenStreetMap Carto" as an official project name everywhere.

Update project name in RELEASES.md

---

admin.mss

The code that renders admin and nature reserve labels along borders
(on z16 and higher) was broken: it only rendered one label per
metatile. With the new code, labels are rendered every 600px.

Fix repetition of high-zoom admin/nature reserve labels

---

roads.mss

This PR adds a white halo to roads on z6 and z7. It also makes motorways on z6 slightly narrower #2972.
This should give the roads slightly more contrast.

Add halo to roads on z6 and z7, and make motorways on z6 slightly narrower

---

project.mml
water.mss

Drop derelict_canal rendering

---

placenames.mss
project.mml

See #2673
Rendering place=square name for nodes too
z17
z18
z19
Data (4 objects with place=square, original place is [here](https://www.openstreetmap.org/node/4917621976)):

Render place=square name for nodes

---

admin.mss

Reverts #3101 because of the performance problem. See https://github.com/gravitystorm/openstreetmap-carto/issues/3159#issuecomment-382932958 for details.

Revert "Fix repetition of high-zoom admin/nature reserve labels"

---

amenity-points.mss
project.mml

RE: https://github.com/gravitystorm/openstreetmap-carto/issues/3159#issuecomment-383376498
Fixes #3195
POIs with both `amenity` and `office` tags triggered both code paths, resulting in points that shared some visual effects of both of these points.
Refactored the code to use `feature` field instead, as the coalesce() function guarantees it is unique. In the above example, `amenity` takes precedence over the `office` tag.
I've also, added extra checks in `addresses` and `building_text` layers so that they don't render labels when amenity/shop/office tags are defined.
In most (but not all) cases these labels were already hidden by Mapnik because they would have overlapped POI icons otherwise. However, even if not rendered, these labels would still be processed by Carto and Mapnik, …

Fixed office/amenity conflict

---

amenity-points.mss

Fixes #323
- moving barriers from z16+ to z17+:
- gate
- lift_gate
- swing_gate
- bollard
- block
- log
[Example place with gates, z16](https://www.openstreetmap.org/#map=16/52.2223/20.9062)
Before
After
[Example place with bollards, z16](https://www.openstreetmap.org/#map=16/52.2560/20.9835)
Before
After
[Example place with gates and lift gates, z16](https://www.openstreetmap.org/#map=16/46.3637/11.0327)
Before
After

Move barriers to higher zoom level

---

amenity-points.mss
project.mml
symbols/spring.svg
water-features.mss

Fixes #325
- before
- after
Thanks to @imagico for the starting point.

Refurbished spring icon (fix #325 using @imagico first tests)

---

project.mml

Related to #2504, #2037 and #1659.
- Hide railway platforms which are located underground, because they eclipse station buildings too much and this is rather indoor feature (see https://www.openstationmap.org )
[Warsaw](https://www.openstreetmap.org/#map=17/52.22925/21.00564)
Before
After
[Berlin](https://www.openstreetmap.org/#map=17/52.52497/13.37020)
Before
After

Hide railway=platform with location=underground, tunnels and covered=yes

---

landcover.mss
project.mml

Fixes #3110
Add rendering of `amenity=taxi` in a similar way than other parking amenities
https://www.openstreetmap.org/way/284714637
Before
After
I noticed that `amenity=parking` is also included into `amenity-low-priority` in the project file. Should I put also taxi in this section ?

Add area rendering of taxi

---

landcover.mss
project.mml

Part of a transport unification effort, related to #2094. Using the same subtle area color for bus station as for the other transportation areas (taken from the airport area).
Cracow, z19
Before
After

Adding area rendering for amenity=bus_station

---

symbols/shop/deli.svg

The current shop=deli icon looks pretty fuzzy to me. This PR pixel aligns the icon to the pixel grid.
Icon before:
Icon after:
The edges of the jar are snapped outward to the pixel grid and the curve on the label is removed (the curve is not really visible at 14x14 anyway).
Before:
https://www.openstreetmap.org/#map=18/45.51760/-122.97312&layers=N
After:

Pixel align the shop=deli icon

---

water.mss

Compacting code for waterway=canal - rules for z13 and z14+ are the same.
No rendering change is expected.

Compacting code for waterway=canal

---

landcover.mss
project.mml

Related to #3045.
Resolves #848.
Rendering police and fire station areas with the same hatching as new military area style, as discussed before. It will make uniformed services areas to use similar look.
Examples:
[Police](https://www.openstreetmap.org/way/556906228#map=18/52.24606/20.99851)
[Fire services](https://www.openstreetmap.org/way/35017939#map=19/52.18410/21.00388)
[Comparison with military area rendering](https://www.openstreetmap.org/#map=18/52.21053/21.01156)

Adding rendering for amenity=police and amenity=fire_station areas

---

landcover.mss

This resolves #2777
The brightness sequence from z10 up used to be 212-216-211-223, now it is 212-216-221-223.
Before
After

Brighten built-up areas on z12

---

amenity-points.mss

Observed in the German style.
- Make amenity=shelter brown, as it is not a transport nor accommodation utility, rather generic amenity
It looks more like other amenities [on platforms](https://www.openstreetmap.org/#map=19/52.23285/20.99709) and doesn't take away attention from real transport-related objects:
Before
After
It blends better with other amenities [at the picnic site](https://www.openstreetmap.org/#map=18/52.30240/20.87196) and with buildings:
Before
After
It's also easier to spot [in the forest](https://www.openstreetmap.org/node/2881682202#map=16/52.3026/20.3666):
Before
After

Make amenity=shelter brown

---

placenames.mss
project.mml

Fixes #798
- adding rendering for place=quarter as a name label on z14-z16
Rendering test:
- [Example place](https://www.openstreetmap.org/node/334557199#map=16/52.1973/21.0438) (_Sielce_), compared to place=suburb (_Mokotów_) and place=neighbourhood (_Marcelin_):
z14
z15
z16

Adding rendering for place=quarter

---

project.mml

Power cables with a location tag that says they are overground, are now selected and rendered just like power lines, to improve the look of substations that use gas insulated cables. Since those cables are insulated, they have to be mapped with power=cable instead of power=line, but this left undesirable gaps in the connections.
[According to the wiki](https://wiki.openstreetmap.org/wiki/Tag:power%3Dcable) cables without a location tag default to 'either underground or underwater', so they are treated as such.
Closes #3217.
Location: [a substation in Zeebrugge, Belgium](https://www.openstreetmap.org/#map=18/51.32588/3.18409)
~~I tried to set up Kosmtik but the installation failed horribly. I don't feel like installing even more versions of Node.js (which I don't like) on my system to see …

Select overground power=cable like power=line

---

amenity-points.mss
project.mml
symbols/city_gate.svg

Fixes #152 
Show an icon and label for `historic=city_gate` in man_made colour
https://www.openstreetmap.org/way/317181351
Before
After

Adding rendering for historic=city_gate

---

indexes.sql
indexes.yml
project.mml

Follow up to #2873.
Related to #1604.
It needs some testing, but it looks that dropping subpixel accuracy from SQL queries does not have visible effect on rendering - if any - while increasing performance (at least decreasing memory usage).
Affected objects: water, landcovers, buildings and nature reserves.

Dropping subpixel accuracy for areas

---

project.mml
water.mss

Fixes #157
Render lock_name
https://www.openstreetmap.org/way/231720575
Before
After

Adding rendering of lock_name

---

amenity-points.mss
project.mml
symbols/guidepost.svg

Ref #1978, #3105.
Adds a guidepost icon on z19 and drops rendering of guidepost nodes before z19.
before z18
after z18
before z19
after z19

differentiate guidepost from general tourism=information display

---

scripts/get-shapefiles.py

When downloading files it is a good idea to set the timestamp of the remote file for the downloaded file which is better for subsequent updates than the download time.

Add curl option

---

.travis.yml

This checks with find rather than an explicit list, because any .yml or .yaml files should be YAML, and should be valid.

Check all YAML files are valid YAML

---

roads.mss

Fixes #3258 
- Lighten living street tunnels less (respective to normal living street colour)
Before/After
https://www.openstreetmap.org/way/424282172#map=19/41.80501/12.62467

Living street tunnels different from residential

---

water-features.mss

Fixes #2652
- Lowers the stroke width of man_made=pier
- Adds square line-cap to remove rendering artifacts
- Does not effect piers mapped as an area
From the discussion in #2652, there was some disagreement on whether piers should represent real world geometries or abstract lines. My opinion is that it doesn't matter which camp you're in, piers are currently much wider in the map than they are in the real world, and as an abstract line, they are still too wide (they are wider than residential roads at zooms 12, 13 and 14).
At [this sample area.](https://www.openstreetmap.org/#map=14/45.6079/-122.6679)
Before
After
Before
After
Before
After
Before
After
Before
After
Before
After
Before
Notice the gaps in the line rendering.
After
Before
After

Finer man_made=pier width

---

project.mml

Adapt the list in our SQL queries that decides about paved/unpaved surface to the current list in the OSM wiki. Closes #2753

Adapt paved/unpaved decision to OSM wiki

---

amenity-points.mss
project.mml
symbols/shop/ticket.svg

This pull request adds an icon for shop=ticket and closes issue #3115
https://www.openstreetmap.org/#map=19/37.73301/-122.50486 (node)
https://www.openstreetmap.org/#map=19/37.76897/-122.47026 (way)

Add icon for shop=ticket 

---

roads.mss

Increase casing width of tertiary on z12

---

water.mss

This PR adds `text-repeat-distance` for all waterways; it belongs to the split of #3295 in several PRs.
Before/after test renderings:
https://www.openstreetmap.org/#map=17/48.19305/6.41723
https://www.openstreetmap.org/#map=18/48.27490/6.14848
https://www.openstreetmap.org/#map=16/48.4706/6.1019
Edit: added links to test locations.

Added text-repeat-distance for all waterways (part of #3295)

---

amenity-points.mss

`leisure=fitness_centre` and `leisure=fitness_station` have a larger than standard text halo. The screenshot posted for the recent bowling icons looked odd to me (comparing the bowling text to the fitness text):
It turns out that a larger halo was added to dog park text to make it more visible over the paw pattern. fitness_centre and fitness_station matched the same CSS block. This PR splits dog_park from fitness_centre and fitness_station like so:
```
[feature = 'leisure_fitness_centre'],
[feature = 'leisure_fitness_station'] {
text-fill: @leisure-green;
}
[feature = 'leisure_dog_park'] {
text-fill: @leisure-green;
text-halo-radius: @standard-halo-radius * 1.5; /* Extra halo needed to stand out from paw pattern. */
text-halo-fill: @standard-halo-fill;
}
```
Before …

Standard text halo for fitness_centre and fitness_station

---

amenity-points.mss
project.mml
symbols/shop/paint.svg

Adds icon for shop=paint which closes #3288 
https://www.openstreetmap.org/#map=19/37.77712/-122.40170 (Way)
https://www.openstreetmap.org/#map=19/37.76481/-122.41495 (Node)

Add icon for shop=paint

---

Dockerfile
Dockerfile.db
Dockerfile.import

Fixes #3308 
* Postgresql 10 (as is the default is in Ubuntu 18.04, Bionic Beaver)
* Nodejs 8.x (also its default)
* Addition of `fonts-hanazono` fonts package which was never included in Dockerfile but is mentioned in the install guide
* Sets the prefix of npm installation to /usr, which is what kosmtik expects (Default in Ubuntu 18.04 npm package is /usr/local, which confused its installation scripts). Kosmtik **is** expected to be node 8 compatible. See https://github.com/kosmtik/kosmtik/commit/aed8789c6d11e53f03b151f2817b08a659d20c99 .
Testing performed:
docker-compose up import (against a data.osm.pbf file)
docker-compose up kosmtik

Update kosmtik, db, import Dockerfiles for Ubuntu 18.04 and nodejs 8

---

amenity-points.mss
project.mml
symbols/bird_hide.svg

Adds icon for leisure=bird_hide closing #3175 
https://www.openstreetmap.org/#map=19/47.43837/-122.47189 (Way)
https://www.openstreetmap.org/#map=19/47.81981/-119.97127 (Node)

Add icon for leisure=bird_hide

---

DOCKER.md
INSTALL.md
RELEASES.md

Related to #2927.
Follow up to #3160.
- Change of the remaining technical project name occurrences in different places of the documentation into the proper name

Name of the project fixes

---

amenity-points.mss
project.mml

Fixes #3335 
- Render attraction=water_slide similar to a (water) stream
- Render a marker for water slide
- Render the name of the water slide
This is more a proof of goodwill, probably both the rendering and the code have to be further improved, as I'm a complete newbie to this.
In particular, the marker is hidden unter the slide, how can I fix that?  However, I'm not so sure the marker makes sense, anyway.
https://www.openstreetmap.org/way/353735844
Before
After

Water slide

---

amenity-points.mss
project.mml
symbols/shop/trade.svg

Adds icon for shop=trade, shop=wholesale closes #3291
Shop=trade (uses same updated icon as shop=wholesale)
https://www.openstreetmap.org/#map=19/37.77322/-122.41143 (way)
https://www.openstreetmap.org/#map=19/37.76920/-122.40372 (node)
Shop=wholesale
https://www.openstreetmap.org/#map=19/40.66082/-73.72151 (way)
https://www.openstreetmap.org/#map=19/40.73295/-73.86265 (node)

Add special icon for shop=trade, shop=wholesale

---

landcover.mss

Closes #2821
- Changing the colors of farmland and societal amenities taken from @imagico fork (https://github.com/imagico/osm-carto-alternative-colors, changes described in details in http://blog.imagico.de/more-new-colors/ )
In short, this makes basically a color swap between farmland and societal amenities, in effect:
- farmlands are greenish, which is coherent with other vegetation areas
- farmlands are lighter, which is better than going back to dark, since they tend to be quite big
- societal amenities are reddish, which is more coherent with some other landuses 
- societal amenities are darker, which makes them easier to spot, since they tend to be not too big and eclipsed with some other landcovers (like grass for example)
Farmland color …

Changing farmland and societal amenities colors

---

roads.mss

Currently trunk_link, primary_link, secondary_link and tertiary_link are all rendered identically to their main road types. These changes let them them render thinner.
Test renderings with links to the example places:
**primary_link before**
https://www.openstreetmap.org/#map=18/47.45893/18.98951
**After**
**trunk_link before:**
https://www.openstreetmap.org/#map=17/47.46131/18.87792
**After**
**secondary_link and tertiary_link before:**
https://www.openstreetmap.org/#map=18/47.46888/19.08032
**After**

Render all road links thinner

---

amenity-points.mss

Fixes #3325
- Moving manors icon rendering to higher zoom level without touching any other castles
[Poznań at z15](https://www.openstreetmap.org/#map=15/52.4074/16.9290)
Before
After

Moving manors to higher zoom level

---

project.mml

This way, we respect the layer tag for water slides, and it should not harm for fords.
Fixes #3413 
Order amenity_lines by layer
https://www.openstreetmap.org/#map=19/48.51073/9.03904
Before
After

Order amenity_lines by layer

---

amenity-points.mss

- Render amenity=atm on z19+ instead of z17+
ATMs are small facilities which make clutter on the map on z17 and z18 when located near some other POIs, which is common case in cities. ATM is smaller than bank, where it can be usually placed, so it should be rendered later, and since their size is smaller than all the shops, I think they should be rendered from z19.
Just two examples out of many:
[Bank is eclipsed by ATM at z17:](https://www.openstreetmap.org/#map=17/52.27057/20.97482)
Before
After
[ATM eclipsing label of a bigger amenity at z18:](https://www.openstreetmap.org/#map=18/52.23101/21.01254)
Before
After

Moving amenity=atm to z19+

---

amenity-points.mss
project.mml

Partially fixes #2018 
- add icons for leisure=sports_centre + sport=swimming and leisure=swimming_area

Add more swimming icons

---

amenity-points.mss

Replace board icon by map icon for `information=tactile_model ` following [comment](https://github.com/gravitystorm/openstreetmap-carto/pull/3246#issuecomment-427578416) of  @Tomasz-W from #3246
https://www.openstreetmap.org/node/4362875819 (the land of gift shops)
Before
After

Fix icon for information=tactile_model

---

project.mml
water.mss

Fixes #804
Add label to `natural=strait` from z10
https://www.openstreetmap.org/relation/2667319
Before
After

Rendering of strait from z10

---

amenity-points.mss
project.mml

This PR adds rendering for leisure=track on lines. As it is they are currently rendered on areas but not on ways. Closes #2632 
https://www.openstreetmap.org/#map=18/39.19833/-122.02187 (location 1)
https://www.openstreetmap.org/#map=18/39.14384/-121.67329 (location 2)
There is also some other related issues in #2632 that it potentially closes, but I wasn't sure which ones. So I can add them later. Also, the line is a little thin and tracks are usually pretty wide. So maybe it could be made wider.

Add rendering for leisure=track on lines

---

landcover.mss

This PR changes the color for aprons in aerodromes. As they are currently to prominent. Closes #3385

Change color for apron in aerodromes

---

amenity-points.mss
landcover.mss

This PR moves post box's to z19+. There are multiple reasons why this is a good idea. A few are that they clutter things up to much and block more important icons and names at zoom levels above 19. Also, its a small feature that is not used that often, and is only important on a neighborhood or even block level most of the time. Closes #3431

Move amenity=post_box to z19+

---

landcover.mss

Fixes #3004
- Making societal amenities (schools, hospitals etc) look like regular built up areas on z10-z12, so we avoid light patches, which are too early to be identified and just create visual noise
**Warsaw, z10**
Before
After
**Warsaw, z11**
Before
After
**Warsaw, z12**
Before
After

Making societal amenities look like residential on medium zoom

---

landcover.mss

Fixes #585
* Remove outline of swimming pools between z14 and z17
* Lighten colour of outline
https://www.openstreetmap.org/#map=15/43.7081/7.3168
Before
z15
z17
z19
After
z15
z17
z19

Reduce noise of swimming pools at low zoom

---

amenity-points.mss

Fixes #3410
Follow up to #2945
- Rendering orange dot for gastronomy objects on z17, because they are very popular and create visual clutter (excluding food court, which is bigger and less popular, it would be still rendered as full orange icon)
- Removing night club from this category and showing it similar to other entertainment objects like cinema, since this is more about party than gastronomy, it's also much less popular and does not create clutter
[Warsaw, Old Town, z17](https://www.openstreetmap.org/#map=17/52.24951/21.01196)
Before
After

Rendering orange dots for gastronomy on z17

---

roads.mss

Related to #3467.
- Moving rendering of motorway junction names from z12+ to z13+. Refs are on z11+ and it was sane to render names 1 step later, but names tend to be much longer than refs and in some cases they dominate the area.
**[Amsterdam](https://www.openstreetmap.org/#map=12/52.3685/4.9117)**
Before
After
**[Malmö](https://www.openstreetmap.org/#map=12/55.5840/12.9634)**
Before
After
**[Warsaw](https://www.openstreetmap.org/#map=12/52.2322/20.9538)**
Before
After

Rendering motorway junction names later

---

landcover.mss
project.mml

Fixes #3454
Render `military=danger_area` above other landuses by moving it into the `landuse-overlay` layer
https://www.openstreetmap.org/way/307904554
Before
After

Move danger_area into landuse-overlay

---

buildings.mss
landcover.mss
project.mml
roads.mss
water.mss

This pull request cleans up the rendering on z13 and z14, by removing a number of features from these zoom levels.
* Drop buildings from z13 ~~and z14~~
* Drop footways from z13
* Drop service roads from z13
* Drop pedestrian roads from z13
* Different rendering of living_street on z13
* Drop playground outlines from z13 and z14
* Lighten up the color of trams
* Drop streams, ditches and drains from z13 (and intermittent ones from z14)
Fixes #3331.
The primary purpose of this pull request is to remove visual clutter from z13 and z14. These zoom levels contain lots of tiny elements that are hard to interpret, and lead to noise in the images. As a consequence of removing these features, the remaining features (such as the street pattern) become easier to read.
The secondary purpose is to …

Clean up z13

---

roads.mss

This PR adds `text-repeat-distance` for highways, which currently unnecessarily clutter the map on dense areas. It uses a smaller value of 50 for `highway=unclassified` and lower-importance highways, and 200 for higher-importance highways. This also achieves the split of #3295 in smaller PR as requested by @kocio-pl, and consequently closes #3111.
Before/after examples:
https://www.openstreetmap.org/#map=17/48.66397/6.17061
https://www.openstreetmap.org/#map=17/48.68110/6.14494
https://www.openstreetmap.org/#map=17/48.69825/6.18554
https://www.openstreetmap.org/#map=16/48.1898/6.4266
Edit: added links to test locations.

Added text-repeat-distance for highway names

---

project.mml

Fixes #709
Add support of `basin=detention` and `basin=infiltration` in `int_intermittent` variable
`basin=detention` https://www.openstreetmap.org/way/220462429
Before
After
`basin=infiltration` https://www.openstreetmap.org/way/234418071
Before
After
`basin=infiltration` https://www.openstreetmap.org/way/532562272 (no modification)

Improve intermittent waterbody rendering of basins

---

CHANGELOG.md

Before, buildings were hidden up to z12, not z13.

Correct typo in changelog related to buildings

---

amenity-points.mss

Fixes #3510
Related to #3512 
**Changes proposed in this pull request:**
- Change the text color of man-made feature's name labels to man-made-icon gray darkened by 15%
- Make text-dy 10 for all of these man-made features
- Remove redundant name label code for wastewater and water plants
- Fix formating of natural_cave_entrance text-dy
**Features affected**
man_made = lighthouse, windmill, hunting_stand, bunker (currently gray)
historic = wayside_shrine (currently gray)
man_made = tower, mast, communications_tower, water_tower, chimney
_power = generator with generator:sourece=wind_ - if this is merged (currently black)
Not affected: Religious items with black icon and text
man_made = cross
historic = wayside cross
**Rational**
All man_made features with icons in man-made-icon color …

Change man made gray and text color, make text-dy uniform

---

roads.mss

Related to #3467.
- Rendering railway pattern on z12 instead of a simple black line. It allows to recognize railways from tram lines in urban areas and makes it easier to recognize them in the outdoor (we show power lines later, but one does not have to know that).
[Bratislava](https://www.openstreetmap.org/#map=12/48.1478/17.1361)
[Amsterdam](https://www.openstreetmap.org/#map=12/52.3756/4.8987)
[Zagreb](https://www.openstreetmap.org/#map=12/45.8123/15.9757)
[Bytom](https://www.openstreetmap.org/#map=12/50.3406/18.9142)

Rendering railway pattern on z12

---

stations.mss

Follow up to #3467.
- After cleaning of z13 tram stops became too visible and make a noise, so they are pushed to z14+.
Warsaw, z13
Before
After

Move tram stops later

---

project.mml

Related to #3534.
Resolves #1614.
- removing needless buildings, religion and name related queries from `landcover-low-zoom` data layer
This should make the query marginally faster, but it's mostly code cleaning.

Landcover low zoom cleaning

---

project.mml
stations.mss

Fixes #3559
Move `railway=station` + `station=subway` to z14 as well as `railway=tram_stop` following #3541
`z12`
before
after
`z13`
before
master (with #3541)
after
`z14` (no changes)
before
after

Move station=subway to z=14

---

roads.mss

* Make subway bridges under construction thinner and only appear from zoom 14 on.
Currently, all railway construction bridges are rendered the same. However not all (non-construction) railway bridges are identical.
Namely, subway bridges are thinner and appear later (zoom 14 instead of 13) than standard railways.
This PR unifies the appearance of subway bridges, whether under construction or not.
Some other railway types have their own rules for bridges (light rail, funicular, narrow gauge, etc.). They are not handled in this PR, but could be if there is interest.
(Area: https://www.openstreetmap.org/#map=14/48.1131/-1.6690)
Before
After
(This one is more subtle.)
Before
After

Use usual subway bridge style for subway construction bridges

---

roads.mss

**Fixes #1109** 
(This issue is currently closed, but tertiary_link was not added)
**Changes proposed in this pull request:**
- Render highway=tertiary_link thinner than highway_tertiary (generally the same width as secondary_link)
**Explanation:**
Leaving different tertiary links causes oddities in connections to higher-order tertiary links, eg 
[](https://user-images.githubusercontent.com/19976610/45986666-4d7a4280-c043-11e8-97cb-28c287caaa12.PNG)
Tertiary_link is used over 150k times and is mentioned in the highway link documentation, and it is currently rendered, but at the same width as highway=tertiary. This makes the tertiary links significantly wider than motorway, trunk, primary and secondary links.
Previously this was not fixed, because tertiary has been rendered in white, the …

Add tertiary-link width, same as other links

---

admin.mss

Related to #3538, #2978
- Make nature reserve boundaries less prominent at z8 and z9
- On all zoom levels: Reduce the "glowing" effect that occurs on boundaries that are shared between two adjacent nature reserves
Test renderings of [Northern California](https://www.openstreetmap.org/#map=8/41.263/-122.574)
z8 before:
z8 after:
z9 before:
z9 after:
z10 before:
z10 after:

Nature reserve boundaries revision

---

amenity-points.mss
landcover.mss

Related to #3045 "Outline Coordination Meta Issue"
and #3521 "Add Aboriginal Areas"
- Change tourism color from brown to `#660033` - this is currently the tourism=attraction text color
**Explanation:**
In #3521 it is planned to use brown for boundary=aboriginal_lands (eg American Indian reservations)
Therefore it is necessary to change the color of the outline used for zoos and theme parks.
This has also been desired, so that these tourist areas would be more visible on the map with a color more closely related to retail areas and other points of interest. The proposed change will also unify the color used for these two features with that used for tourism=attraction.
Purple and orange have also been discussed. Purple would work well, but would be …

Change tourism outline color

---

amenity-points.mss
project.mml

Follow up to #2830.
Resolves #603.
Since I have found no clear rules of how `boundary=protected_area` relates to national parks and nature reserves, it should be rendered the same. Only `protect_class=1-7,97-99` should be rendered, because they are more or less in the same category as them - see https://wiki.openstreetmap.org/wiki/Tag%3Aboundary%3Dprotected_area#Nature-protected-area (<s>to be implemented</s>). Smaller ones will appear later, so no clutter is expected. 
Example rendering ( https://www.openstreetmap.org/way/199324293 )

Adding rendering for boundary=protected_area

---

landcover.mss

Fixes #3593
**Render the polygon fill pattern at z13 and above, instead of z14 and above, for the following areas:**
1. vineyard
2. orchard
3. garden
4. plant_nursery
5. cemetery / graveyard
6. scrub
7. beach, shoal (`beach`)
- _gravel, fine_gravel, pebbles, pebblestone, shingle, stones, shells_ (`beach_coarse`)
8. Specific wetland patterns, i.e.:
- _marsh, saltmarsh, wet_meadow_ (`wetland_marsh`)
- _reedbed_ (`wetland_reed`)
- _mangrove_ (`wetland_mangrove`)
- _swamp_ (`wetland_swamp`)
- _bog, fen, string_bog_ (`wetland_bog`)
**Unchanged:**
1. Allotments have recently begun to render the pattern from z13 instead of z14
2. Leisure=dog_park has a pattern at >= z16. This has an open issue, and has not been changed.
3. Some other patterns already render sooner: 
- Forest/wood already renders …

Start rendering most patterns at z13 instead of z14

---

amenity-points.mss
landcover.mss

- Render parking at z14 and above only
(No longer render parking lots at z10 to z13)
- Parking lots currently render as soon as z10, and the icon is rendered as soon as the way_pixels (height x width) is greater than 900 (eg 30 pixels wind and high), without consideration of zoom level
- However, very few parking lots are large enough to have an icon at z13 (I have yet to find one), and generally only the fill color is visible
- The fill color for parking is nearly the same as the background land-color, or the color of untagged land, so parking lots are only visible at z13 and lower when they are surrounded by other land uses or natural areas, and they then appear as a "hole" in the landuse or other area.
- This is a particular problem in the USA, where many town centers have more than …

Render parking at z14 and greater

---

admin.mss

Related to #3538.
Change proposed in this pull request:
- Make country borders thicker at z8 and z9.
This will make these borders more prominent at these zoom levels, where they are currently quite thin. It will also make them easier to distinguish from railways when the border color from #3553 is implemented and when railways are made lighter in the future.
The "after" renders are shown with the border color from #3553. 
z8 before 
z8 after
z9 before
z9 after

Thicker country borders at z8 and z9

---

amenity-points.mss

This PR changes certain amenity icons that are passive to grey in order to help off load things color with amenity brown a little and to reflect the fact that they aren't "services." Included in the PR is bench, picnic table, waste basket, shelter, and waste disposal. Not included in the PR is things related to recycling. Which will be changed in a separate PR. The PR is related to PR #3402 and issue #3326. 
bench, waste basket, picnic table
https://www.openstreetmap.org/#map=19/40.68154/-122.36317 (node)
shelter
https://www.openstreetmap.org/#map=19/37.79619/-122.42138 (node)
https://www.openstreetmap.org/#map=19/40.58366/-122.39271 (way)
waste disposal
https://www.openstreetmap.org/#map=19/37.48214/-122.22696 (node)
https://www.openstreetmap.org/#map=19/37.49039/-122.22382 (way)

Change certain amenity icons to grey

---

amenity-points.mss
project.mml

Fixes #3545
Related to https://github.com/gravitystorm/openstreetmap-carto/pull/1063#issuecomment-67853592
- Add generic "dot" icon for tourism=attraction
- Render tourism=attraction only at z17 and above
- Move tourism=attraction to low-priority label, after other features, so that it will only render if there is no other more specific tag (this fixes #3545 "tourism=attraction stops man_made=cross from rendering")
- Change text to standard font, render text and dot in tourism color ( `#660033` now)
Explanation:
- Features tagged tourism=attraction will currently render earlier than z17 if tagged on a large area (closed way or multi polygon), however there is no area fill or icon
- Area rendering was previously rejected in #1257 "Add area rendering …

Reduce priority of tourism=attraction and render from z17

---

project.mml
roads.mss

Fixes #2595
**Changes proposed in this pull request:**
- Stop rendering undocumented construction=* types
- Specifically render raceway, pedestrian, living_street, road as types of other construction roads
- Render minor construction=* types later
- Reduce width for narrow highway=construction, to match finished road times (or narrower)
- Add paths, track and null construction name label rendering
- Change color of construction=null and construction=path/track to #aaa, medium gray (same as minor highway=construction)
**Explanation:**
There are several issues with the current highway=construction rendering. This PR addresses several:
1. Highways under construction (construction=*) should be no wider than their finished counterparts (highway=*) on a given zoom level.
2. Highway=construction …

Adjust width of highway=construction rendering

---

amenity-points.mss
project.mml
symbols/barrier/cycle_barrier.svg
symbols/barrier/full-height_turnstile.svg
symbols/barrier/kissing_gate.svg
symbols/barrier/motorcycle_barrier.svg

This PR adds more icons for barriers. It closes #846 
Motorcycle barrier
https://www.openstreetmap.org/#map=19/53.20660/-1.41045
Cycle barrier
https://www.openstreetmap.org/#map=19/53.22609/-1.41716
Kissing gate
https://www.openstreetmap.org/#map=19/52.45566/-1.58009
Full height turnstile
https://www.openstreetmap.org/#map=19/52.19147/-1.48791
Turnstile
https://www.openstreetmap.org/#map=19/51.50322/-0.11377
Lots of gratitude to everyone involved, especially @Tomasz-W for making the icons and keeping track of everything.

Add more barrier icons

---

amenity-points.mss

Small fix of #3528 to restrict private rendering of label to `tourism=alpine_hut/wilderness_hut` and `amenity=shelter`. 
Currently several `tourism=*` with private access display an inconsistent rendering with transparent label and opaque icon 
https://www.openstreetmap.org/way/67006491
Before
After

Fix label opacity for tourism features

---

project.mml

Partial revert of #3539.
- bring back the "no building" checking line in `landcover-low-zoom` data layer, since this might have performance implications (see this comment: https://github.com/gravitystorm/openstreetmap-carto/pull/3539/files#r244279150)
Test rendering is positive (nothing is broken).

Reverting lowzoom nobuilding test change

---

project.mml

Fixes #3566
Related to #1280
- Modify SQL query in project.mml to only select as features motorway_link, trunk_link, primary_link, secondary_link and tertiary_link.
Before
After

Select only motorway_link to tertiary_link as link in SQL

---

project.mml
water-features.mss

This partly replaces #3228 and is an example of converting a layer to use `ST_PointOnSurface`

Convert springs to use ST_PointOnSurface and reformat SQL

---

amenity-points.mss

Related to #3395
- Add `@barrier-icon` color variable with value of `#3f3f3f `
- Change barriers marker-fill to use `@barrier-icon` instead of `#3f3f3f `
Note: 
-bollards, logs and blocks are unchanged, because these currently use a much lighter shade of gray.
- 'barrier_gate' does not use marker-fill, because the icon uses two colors (#3f3f3f plus a white halo)
In the future this variable could be changed to use @man-made-icon if we wish to reduce the number of shade of gray.
Test rendering is not shown, because the cartography is unaffected.
I have tested this commit and found that it works without changing the rendering.

Add "barrier-icon" color variable with #3f3f3f for barriers

---

amenity-points.mss

Related to #3395
- Add `@religious-icon: #000000;` 
- Use this variable for place_of_worship, historic=wayside_cross and man_made=cross
In the future this could also be extended to other religious icons, such as wayside_shrine or other religious objects if they become defined in the database. 
Test rendering is not shown, because the cartography is unchanged. 
However, I have tested this commit and found that it works without problems.

Add "religious-icon" as a color variable

---

placenames.mss

Fixes #1984
- Start rendering hamlets at z14 (instead of z15) through z17
- Use a slightly larger text label for hamlets, intermediate between place=quarter and place=neighborhood / locality / farm
- Move place=hamlet to same layer as place=quarter
- In areas where hamlets are common, the map may not display any place names, or too few, at z14
- Mappers sometimes misuse place=village for very small settlements so that they will render sooner. This change will reduce this incentive. 
- Hamlets are larger and more important than farms, isolated_dwellings, and "localities", since they are found in rural areas but have more than one or two families, so they should be rendered sooner and with a subtly different text.
**Wales**
_high latitude_
z14 Trefin - current
After
z14 Dobshill - current …

Change zoom level and text size for place=hamlet

---

amenity-points.mss

This renders gate ref's in black instead of in purple. Purple used to be the airport color, but apart from gates purple is no longer used for airports.
Before:
After:

Render gate ref's black instead of purple

---

roads.mss

- Modify the code for display of the ref on unclassified and residential highways:
- Add `text-placement: line` for ref of minor roads so that the ref will display more than once on a way
- Remove deprecated `text-min-distance`, replace with `text-repeat-distance` instead.
- Currently the reference number of an unclassified or residential highway (aka "minor highway") is only displayed once at the center of the OSM way, because `text-placement` has not been set to `line`. This PR will allow ref numbers to display every 760 pixels approximately, as intended. 
- Also, `text-min-distance` was used, but this has been deprecated in the CartoCSS documentation. This has been changed to use the new recommended option, `text-repeat-distance`, which is already used for name label rendering in most …

Render ref of minor roads more than once

---

project.mml
roads.mss

Related to #2052 
- Add rendering of "ref" codes and numbers for track roads, using a similar style as used for residential and unclassified roads
Track roads, tagged with highway=track, are used to access agricultural and forestry areas. Many of these small roads are unnamed, but in some areas it is common to use a reference number or string of letter and numbers to refer to such roads. For example, Forest Service roads in North America often have a ref, without a name, or sometimes both. 
Adding rendering of the ref will help with routing in these areas. The style of rendering is rather subtle, using the same style as the name text label rendering.
One issue is that the ref layer is rendered first, so if there is not space for both the name and the ref, the ref alone will be rendered. …

Add rendering of "ref" for track roads

---

project.mml

- Way_pixels will now be calculated from way_area divided by the square of scale_denominator and the standard pixel size
- Currently, the value of the column `way_pixels` is calculated from the way_area (which represents the approximate area of a polygon in square meters, but by Mercator projection) by dividing by pixel_width * pixel_height.
- However, this causes the calculation to change when the resolution is changed, for example, when exporting at 2x resolution in Kosmtik, or when rendering "retina" resolution tiles. 
- Using the scale_denominator instead of the actual pixel height/width results in a consistent rendering at different rendering resolutions.
_Southern Australia_
9/-32.7988/137.0764
**Screenshot at standard resolution** - unchanged before and after PR
z8
z9
**Export at …

Change way_pixels calculation to use scale_denominator

---

landcover.mss

Related to #3651 and #3517 
- Change the pitch outline color to be the pitch color, darkened 20% and desaturated 10%
- Also changes track outline color in the same way.  (The track and track outline colors are the same as the pitch and pitch outline colors currently)
- In #3651 and #3517, it's been suggested that the pitch outline is not harmonious with the pitch background color.
- The current pitch outline is 30% darker and 20% more saturated than the pitch color (`#aae0cb` or  Lch(85,22,168). This is a much higher chroma than the pitch background color, so the outline does not appear to be based on the same color. 
- Examining the outline colors for other features, such as residential, commercial and industrial land, shows than most are 15 darker and just slightly higher chroma (in …

Reduce saturation of pitch outline color 

---

admin.mss

- Renders national_park, nature_reserve, protected area, and aboriginal_lands boundaries at >750 waypixels instead of >3000.
- This causes the boundary outline to render 1 zoom level sooner than the name label for these areas. The text label renders at >3000 waypixels.
- This is also the same limit that is used for tourism areas, such as zoos and amusement parks, with outlines. (Military areas and police stations currently render with > 900 waypixels, similar to the number in this PR.)
- Currently, boundaries for protected areas, national parks, nature reserves and aboriginal_lands are only shown when the polygon is rather large: 3000 square pixels, approximately. For example, a 31 by 101 pixel rectangle will render, but a 30 by 90 pixel polygon would not show the borders at that zoom …

Reduce way_pixels limit to >750 for protected_area boundaries

---

project.mml

The WHERE clause in the inner SELECT restricts the possible values of highway to 'motorway', 'trunk', 'primary' and 'secondary'. Therefore, 'tertiary', 'unclassified', 'residential', 'runway' and 'taxiway' will
not occur as values of highway.
- no visual changes, just code cleanup
Before
After

roads-text-ref-low-zoom: remove unused SQL CASE conditions in ORDER BY

---

amenity-points.mss
landcover.mss
project.mml

This PR drops rendering of leisure=common.
The leisure=common tag has several problems. I therefore think we should not render it on the default style.
Some of these problems are:
* The tag defines a legal ownership concept, not a physical concept. According to the [wiki](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dcommon), a common is 'land which has an owner, but over which other people have certain rights'. I think we should render the physical appearance or purpose of features rather than their legal status.
* The tag is very UK centric. Commons are a UK concept that does not really translate to other countries.
* The tag is heavily misused. At least in Western Europe, almost all objects tagged with leisure=common are not actually commons. The tag is often used for random pieces …

Drop leisure=common

---

project.mml
roads.mss

Fixes #2865 
Fixes #1937
- Add missing oneway arrows for tracks and paths
- Fixed rendering of arrows on footways: these will always use the footway color, rather than changing if there is (mis)-tagging with designated=bicycle or designated=bridleway.
- Fixed bridleway one-way arrow color. It is now based on brideway color instead of track color.
**EDITED: New changes**
- Change arrows to Unicode text with halo for better visibility.
- Adjust position of text based on `oneway = -1` to make sure text is always on the same side of one-way paths and tracks
(First option, without change to unicode text arrows and halos)
Before
After - first option
**EDITED: Current commit:**

Add missing oneway arrows for tracks and paths

---

admin.mss
project.mml

Related to #622
Also see #3649
- Render admin_level 1 to 4 text labels along the admin boundary lines from z11
- Redner admin_level 5 to 8 text labels along the border lines from z12 to z15 based on admin_level (5 at z12, 6 and z13, 7 at z14, 8 at z15), and admin_level 9 and 10 will continue to render at z16 and higher.
- Add a minimum way_pixels limit for admin 1 to 4 which are the same as largest central text label rendering. Thus the text labels will appear along the border lines when the total area is greater than 360,000 pixels for admin_level 1 and 2, and 196,000 way_pixels for admin_level 3 and 4. The limit is 48,000 way_pixels for higher admin_level, which have no other text labels.
- Remove unnecessary `admin_level IN ('0',` from query, as this level is not used. 
- Border text …

Show administrative boundary text labels from z11 to z16 based on admin_level

---

indexes.sql
indexes.yml

This reflects changes to the SQL query of layer landuser-overlay introduced by commit 52085d3b6d60cfbe7f39fc44ae6c9345c89c1fd6 (pull request #3469). This partial index was introduced for this layer and its WHERE condition needs to be updated as well if the WHERE condition of the SQL query used by that layer is changed.
There are no visual changes but rendering performance of this layer should become better.

Update condition of index planet_osm_polygon_military

---

project.mml
stations.mss

Also a minor code cleanup to prio generation

Use ST_PointOnSurface for stations

---

.travis.yml
INSTALL.md
project.mml
scripts/get-shapefiles.py
shapefiles.mss
style.mss

Fixes #1982 
Reverts #3065
See similar previous PR #2066 which was reverted due to #2101  
Also see #2507
Related to solving several issues including #621, #1547, #1781, #2013, #2025, #2609, #2688, #3695, and PR #3670
- Change from rendering  land polygons on an ocean-color background to rendering ocean polygons on a land-color background
- Remove outline from low-zoom coastlines
It is beneficial to render the oceans (that is, all water outside of the openstreetmap coastline) as polygons, rather than the present situation where the continents and islands are rendered as polygons. While this PR does not make any changes in the layering of land and water, with the introduction of water polygons it will become possible to move the oceans above water lines and landcover, which will be helpful …

Change from land polygons to ocean polygons

---

.travis.yml
INSTALL.md
project.mml
scripts/get-shapefiles.py

- All links and references to openstreetmapdata.com are changed to the new source of shapefiles, hosted at osmdata.openstreetmap.de
- The file `simplified-water-polygons-complete` is now `simplified-water-polygons-split`
The rendering is unchanged after manually downloading the new water and icesheet shapefiles. 
The script 'get-shapefiles.py' appears to begin downloading the shapefiles properly. However, I did not complete the download via the script, due to the amount of bandwidth required.
I have not tested the changes to the `.travis.yml` file.

Source water & icesheet shapefiles from osmdata.openstreetmap.de

---

amenity-points.mss
project.mml

Reverts #3498
Fixes #3639, #3606 
Related to #3706, #3594, #3609 
Can be reverted after a new version of #3644 is merged and database reloaded (probably some months in the future)
- Remove "healthcare" key from project.mml and amenity-points.mss
- Removes rendering for features tagged with "healthcare" only (most healthcare features, which are also tagged with amenity=hospital, =clinic, =doctors, =pharmacy etc, will continue to render)
Features mapped with the key "healthcare" are not currently loaded into the database as a polygon when mapped as a closed way. Fixing this requires database reload; see #3644 which was closed. 
In the meantime, features mapped as closed ways are not be rendered when tagged with "healthcare" alone. This provides inconsistent mapper feedback, suggesting that …

Revert rendering of healthcare key

---

landcover.mss
project.mml

Fixes #3696
Change proposed in this pull request:
- Add landuse=grass to the landcover-low-zoom layer and render it from z5 instead of z10
This allows large grassy areas, such as in the Netherlands, to be visible at low zoom. 
https://www.openstreetmap.org/#map=9/52.0322/4.7873
z9 before
z9 after
https://www.openstreetmap.org/#map=8/52.0322/4.7873
z8 before
z8 after

Render landuse with grass color from z5 instead of z10

---

project.mml

Only render route=ferry label and dashed line on ways with positive osm_id in database, i.e. real ways, not relations.
Fixes #3726, platforms on route=ferry relations are not rendered with labels and lines any more.
Before
After

Render lines and labels only on route=ferry ways, not relations

---

amenity-points.mss
project.mml

Partial fix for #3634
- Remove rendering of natural=cape polygons (Nodes will continue to be rendered as at present)
- Change cape name label text to use standard font, rather than landcover font
- [According to the wiki](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dcape), a cape is the extreme point of land that projects out into a body of water, such as a sea or lake. 
- [Taginfo confirms](https://taginfo.openstreetmap.org/tags/?key=natural&value=cape) that 12 ,747 capes are mapped as nodes, and only 148 as ways, 355 as relations.
- The recently approved tag "natural=peninsula" is available to tag areas of land that are mainly surrounded by water. From the [wiki](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dpeninsula):
> "The tag natural=cape refers to a coastal extreme point, …

Restrict rendering of natural=cape to nodes, change font to standard

---

project.mml

Fixes #3481
- Move `tourism=information` to the lower priority `tourism` query within `project.mml`
- Move `office` to below the second `tourism` query
This change makes sure that natural features and other amenities render first, and are not blocked by a tourism=information tag on the same node. 
Since tourism offices are more important than most offices for a general map users, they can be tagged with office=* which would then be rendered as a blue office dot and text label after this change. Therefore, `office` is moved after `tourism` in the relevant layers within `project.mml`
A few features which are double-tagged with "office=*" and another major tag will be affected by this change, for example, an office in a building that is also tagged as "historic=manor". This should be a …

Move "tourism=information" and "office" to lower priority in amenity-points query

---

placenames.mss

We have yet few rules for z20. This would add another one.
- Do not render neighborhood names on z20+ anymore
Before
After
The screenshot is from Ivory Coast, which is low latitude. I think the typical neighborhood is yet as big at z20 that we can stop the label rendering there.

Do not render neighborhood names on z20+ anymore

---

landcover.mss
project.mml

**Fixes** #426, #1473, #1547 and #2609
Related to issues #1781, #2013, #2025, #2688, #3707 and PR #3670 as a necessary step in the solution.
Continuation of PR #3694
Partially reverts #3189
- Move ocean and water above landcover
- Icesheet polygons are moved before water lines, which are now before water-areas, and ocean polygons are after these. Landcover is now first.
- Also, springs are moved above water-barriers, marinas are moved below water-barriers, and `necountries` is moved to immediately before admin-low-zoom
- Natural=mud is rendered in the `landcover-area-symbols` layer, above all the water bodies
- This PR is the first application of the switch to water (ocean/marine) polygons instead of land polygons. The layering changes follow the order used in the `alternative-colors` …

Reorder layers to render ocean and water areas above water lines and landcover

---

project.mml
water.mss

Partial fix for #3634 and related to #804
Follow up of #3438
- Add rendering for natural=strait mapped as a linear way
- Nodes and polygons (closed ways / multipolygons) tagged with natural=strait area currently rendered, since #3438. However, many straits are tagged as linear ways, and these are not yet rendered.
- The current PR renders the text label for the name of a strait as soon as the way is longer than 100 pixels. This is similar to the standard for rendering name labels at >3000 waypixels, but somewhat stricter. 
- The name label is repeated after 800 pixels, so that there will usually be one label on the screen at zoom levels where the way is long relative to the screen size.
- A similar font style is used as with the name labels for straits, bays and lakes, with a larger font …

Add rendering for straits mapped as linear ways

---

INSTALL.md
scripts/get-shapefiles.py

Fixes #3757
- Remove the download link to world_boundaries-spherical.tgz from `README.md`
- Remove world_boundaries-spherical.tgz from the download script `get-shapefiles.py`
- This file has not been used since PR #2969 in Dec 2017 but it has not yet been removed from the list of shapefiles
- Test rendering is unchanged for z19 to z0

Remove world_boundaries-spherical.tgz from get-shapefiles script

---

amenity-points.mss
roads.mss
water.mss

Fixes #1082
For various areas, we start label rendering not at a fixed zoom level, but based on the area of the feature. Bigger features get rendered yet on earlier zoom levels.
Furthermore, the size of the label usually gets bigger when the zoom level raises and so the feature occupies more space on the screen.
Since a while, we want to stop label rendering for very big areas that cover the hole screen because the label is quite useless at this scale. However this was not possible in the past because of a bug in our software stack. The bug has been fixed, so now we can do this. (See #1028)
- Stop label rendering for too big landcover areas.
- Unify the thresholds of islands/islets with the other landcover features: 750, 3000, 12000, 48000, 192000, …

Stop label rendering for too big areas

---

amenity-points.mss

Fixes #3759
- Restore rendering of text name labels for shops
Diamond Run Mall, Vermont
https://www.openstreetmap.org/#map=18/43.58108/-72.96442
Current z17 - mall and department store names not shown
After z17 - mall name now in red text, department store names shown
z18

Restore rendering of text labels for shops

---

project.mml

This used to be done by processing in the subselects and the outer selects, now it's done in just the outer.
Fixes #3765

Restore height and ele text

---

project.mml

Fixes #3780
Tested locally where I found some differing points.

Use ST_PointOnSurface for building labeling

---

project.mml
water.mss

- Render name labels for natural=bay mapped as linear ways, using same style as natural=strait
- Currently we render name labels for natural=bay mapped as an area or as a node. However, there are almost 400 bays mapped as linear ways, especially in areas with fjords such as Norway, Greenland and Chile. Many of these bays are long, narrow and curving, so it is reasonable that some mappers like to map these as linear ways.
- Recently we added rendering for straits mapped as linear ways in PR #3733 - this new PR will complete the rendering for bays as well, using the same style as that used for straits in the former PR
- 99% of the bays mapped as ways could be rendered as early as z13, but the initial zoom level is set at z14 to be consistent with the current rendering of bay nodes. 
Chile: …

Add text label rendering for natural=bay mapped as linear way

---

power.mss
project.mml

Fixes #1179
* Merge layers `power-towers` and `power-poles` in `project.mml`
* Adjust modifications in `power.mss`
there is no rendering differences
https://www.openstreetmap.org/#map=17/46.17629/6.23976
`z=15`
`z=16`
`z=17`

Unify code of power=tower and power=pole

---

project.mml

Fixes #3742
-  Select only specific values of barrier for rendering from the polygon geometries, matching the same list used for line-barriers 
- Start rendering historic=citywalls from polygon geometries for consistency with rendering of barrier=city_wall
- Stop rendering barriers on polygons where building is not NULL
- Currently all values of the key barrier are selected when mapped as polygons. 
- - This includes all relations of type=multipolgyon and all closed ways tagged with area=yes or with any of the keys that are considered a polygon, such as "building", "amenity", "tourism", etc.
- - All values are picked, including barrier=no and barrier=nonsene
- historic=citywalls is rendered on line geometries, but not on polygon geometry. This is a problem if a feature is mapped as a …

Render only specific values of barrier and historic=citywalls on polygons

---

amenity-points.mss
placenames.mss
project.mml

- Change place=locality initial zoom to z16
- Move place=locality to `amenity-points` layer instead of `placenames-small`
- The tag [place=locality](https://wiki.openstreetmap.org/wiki/Tag:place=locality) was developed in 2007 for tagging an "unpopulated location for which there is no extant feature to which the tag could be associated." 
- Most of the uses of this tag are from imports in the United States, from the GNIS database and similar public data sources. These are usually "former human settlements for which all taggable features are gone, but which still see use (and/or have value) as named locations. This is most frequent in the case of former hamlets, or for historical railroad stations or railroad junction locations."
- The wiki page for this tag advises that it should not be …

Reduce rendering priority of place=locality and raise initial zoom level to z16

---

project.mml

This makes sure the casing and fill queries are the same for both
turning-circle-{fill,casing} and roads-{fill,casing} layers

Reuse sql statements for turning-circle and roads layers

---

roads.mss

- Making the roads code z20-ready
- Larger service roads at z20
- Larger motorways at z20
- The other roads types without changes. It seemed to me that only motorway and service roads are in current master at z20 significantly smaller than on the ground, so only changing these types.
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:

Road width at z20 adjusted

---

project.mml

- Render text labels along borders of admin boundary relations only, not from closed ways
- Render name labels for country and province/state from relations only, not from closed ways
- Currently the border lines are only rendered for borders mapped as relations (with `osm_id < 0`)
- But the text labels along the borders are rendered for both relations and closed ways, in the case when the closed way is also tagged with a key that is imported as a polygon, such as `place=island` or `landuse=residential`. 
- This commit adds a filter for "AND osm_id < 0" to the admin-text layer, so that the text labels do not appear in the rare occasions when an administrative boundary is mapped as a closed way instead of a relation
https://www.openstreetmap.org/way/146660105/
- closed way tagged …

Render administrative boundary text labels for relations only

---

CHANGELOG.md
amenity-points.mss
openstreetmap-carto.lua
project.mml
water.mss

Fixes #3303
- Import the tag `railway=station` as a polygon feature
- This will allow closed ways tagged with `railway=station` to render properly as POIs or areas. Currently an `area=yes` tag or double-tagging with `public_transport` is needed for proper import.
- Database reload is required before any changes are visible, so this PR should be merged to the schema_changes branch, which will be made public when the next database reload is ready

Import railway=station as a polygon

---

openstreetmap-carto.lua

Fixes #3812 
- Add `tourism=yes` as a linestring exception in `openstreetmap-carto.lua`
- Currently all features in the key `tourism=*` are imported as polygons when mapped as closed ways. This means that features tagged with the property `tourism=yes` are always imported as polygons when mapped as a closed way with a key such as `railway=` or `highway=*` which is normally a linestring. This tag is intended to say that a feature is "interesting to tourists", so it should not define an object as an area. By adding this tag to the list of linestring exceptions, it will not be imported as a polygon, unless the main feature tag on the object is a polygon feature.
This PR is submitted to the branch schema_changes, since it will require database reload to take effect.
I've tested the rendering …

Add tourism=yes as a linestring exception

---

.travis.yml

This catches when the generated road colours file has drifted out of sync with the source.
Part of #3830, but doesn't address all the generated code.

Check the generated road colours for drift

---

project.mml

Fixes #3797
- Remove natural=marsh from rendered features
Currently `natural=marsh` is rendered, however, the correct tagging for a marsh is `natural=wetland` + `wetland=marsh` as with other types of wetland. These two options are currently both rendered identically
According to the wiki, `natural=marsh` has not been recommended [since January 2009](https://wiki.openstreetmap.org/w/index.php?title=Tag:natural%3Dmarsh&oldid=217946)  or earlier, and the page has specified that this tag is deprecated [since 2016](https://wiki.openstreetmap.org/wiki/Tag%3Anatural%3Dmarsh).
Since 2009, `wetland=marsh` has shown steadily increasing usage. It is now used 135,000 times, compared to 9000 remaining uses of `natural=marsh`:
https://www.openstreetmap.org/#map=16/51.2726/-0.7962
Before
After

Remove rendering of natural=marsh

---

openstreetmap-carto.lua

Related to #432
- Import "allotments" as a polygon feature by adding it to the list of polygon_keys in the lua transformations file
- This will import closed ways tagged as "allotments=plot" properly as a polygon rather than a linestring, which makes it possible to render the ref numbers for plots (see #432) or plot outlines
- Current rendering is unchanged
Should be merged to the `schema_changes` branch, which will be merged to master at the time of the next database reload

Import "allotments" as a polygon key

---

project.mml

Fixes #3756
- Add `cache-feature: true` for all layers that use attachments to get better performance. We have quite a lot of them…
Test rendering with links to the example places: Should trigger no rendering change.
This PR would need performance testing, but I am not able to do that.
Another question: What about adding `cache-feature: true` to _all_ layers? If this would be performance-neutral, it might be worth to do so, to prevent adding new attachments while forgetting about adding `cache-feature: true`?

Use “cache-feature: true” for better performance with attachments

---

project.mml

fixes #3697
Originally only shop with their own icons were rendered.
Later popular shop values were also rendered - as dots without icons. This was deliberate decision to not render cases like shop=supermarkte
Since #2415 all shop values except 'no', 'vacant', 'closed', 'disused', 'empty' are rendered.
Given that any, even never used shop value is rendered and `shop=yes` is unreasonably popular it is desirable to encourage more specific shop tagging.
Dropping `shop=yes` may encourage using some new shop values and in some cases people will mistakenly create new tags duplicating existing ones,
but standard shop types are still encouraged by using icons.
shop tag currently has long tail of unusual shop types (with most tagged correctly - for example `shop=maps`, some shop like this really …

stop rendering shop=yes [ready for review]

---

roads.mss

Fixes #3808
- Drop steps from z13
Footway rendering was dropped with #3467, steps should likewise be dropped. For future reference, if more cleanup/adjustments happens to z13:
>When taking the current status of z13 otherwise as a given removing steps would be an improvement. But i like to point out that #3467 (and to some extent already #747) left z13 and the whole zoom level progression in a fairly inconsistent state with several contradicting design ideas being thrown together. I have my doubts that in the long term a z13 design and a zoom level progression with no footways (and accordingly no steps) at z13 makes a lot of sense. #3467 did not really present a vision how this is supposed to work outside European urban settings and even there it has its problems.
>So yes, removing the …

Drop 'highway=steps' from z=13

---

fonts.mss

[The font _Noto Sans Tibetan_ has been renamed to “Noto Serif Tibetan” yet in 2015.](https://github.com/googlefonts/noto-fonts/issues/1540) New updates and corrections are now  made only to _Noto Serif Tibetan_. The old _Noto Sans Tibetan_ will disappear in the future.
[In Ubuntu 18.04 Bionic Beaver the package manager still only installs the old one.](https://packages.ubuntu.com/search?searchon=contents&keywords=tibetan&mode=filename&suite=bionic&arch=any) But with 19.04, the package [fonts-noto-core contains both](https://packages.ubuntu.com/disco/all/fonts-noto-core/filelist).
Currently, we use _Noto Sans Tibetan_. This PR switches to _Noto Serif Tibetan_, but keeps _Noto Sans Tibetan_ as a fallback.

Update support for Tibetan

---

project.mml
roads.mss

Partially replaces PR #3663
Follow-up to PR #3654
1) Move unclassified, residential and track highways, and aeroways "ref" to a later layer, after name labels are rendered
2) Change text-halo to standard size for highway=unclassified/residential refs and aeroway refs
3) Change residential / unclassified road "ref" size to 11 point at z17, to be the same size as the name text labels at this zoom level and higher. 
**1) The minor roads, aeroways, and tracks with text-based ref labels currently render in the same layer as the shields for major roads.** 
- The ref text is rendered before the name label, and can block the name from rendering when spaces is limited.
- Major road shields render much sooner than the ref text labels of minor roads, which are not shown until z15 or z16.
- Major …

Create new layer for "ref" of minor roads and paths 

---

amenity-points.mss

Adjust aerodrome and airport zoom levels
Fixes #2664 and fixes #3809 
Related to issues #1028 and #1143
Follow-up of PR #2674, replaces closed PR #3856
- Move initial zoom level for text for airports from z10 to z11. The Icon continues to render from z10
- Continue rendering icon and text until z16, but stop rendering large areas earlier (when `way_pixels > 192,000`)
- Increase icon initial zoom level from z11 to z12 
- Move initial text label zoom level from z11 to z13.
- Continue rendering till z17, or until `way_pixels > 192,000` if mapped as an area.
The current initial and final zoom levels for aeroways are z10 and z13. This appears to have been picked to work with large, international airports in the high lattitudes, though even there it's surprising that airports are not rendered …

Adjust aerodrome zoom levels

---

landcover.mss

Adjust width of hedge & citywall rendering from z15 to z19 and add z20, change hedge to @forest
Fixes #3845
Related to #3747
- Adjust hedge and citywall width from z15 to z19, so that hedges and citywalls have the same width and the width changes by small steps, increasing by no more than 50% between zoom levels.
- Slightly adjust hedge color to match @forest
- Add rendering rule for `barrier=hedge` and `barrier=city_wall` / `historic=citywalls` at z20 with slightly greater width. 
**Background:** 
- Current citywalls (tagged either as `barrier=city_wall` or `historic=citywalls`) are rendered from z15, while hedges only render from z16. 
- However, at z16 citywalls are only 1.5 pixels wide, while hedges begin at 3 pixels wide. 
- At z17 citywalls are rendered wider, 3px, matching hedges. …

Adjust width of hedge & citywall rendering from z15 to z19 and add z20, change hedge to @forest

---

amenity-points.mss
project.mml

Fix low priority layers
Fixes #3860 
- Remove duplicate parking, motorcycle_parking, bicycle_parking, wayside_shrine, wayside_cross and man_made_cross from amenity-points layer.
- Create text-low-priority layer to render text labels of parkings and wayside shrines/crosses
- Move `parking_entrance` to `low-priority-point` layer, to match other parking features
- Fix rendering text labels for `parking` on nodes
- <s>Adjust initial zoom level for `amenity=parking` nodes from z17 to z18 to match `bicycle_parking` and `motorcycle_parking` - (the code would be more complex otherwise). </s> - removed
- Use ST_PointOnSurface to combine `amenity-low-priority` and `amenity-low-priority-poly` into one layer, and re-use the same SQL table for low-priority text labels layer. …

Fix low priority layers

---

amenity-points.mss

- Increase `office=` initial zoom to z18 for documented values
- Remove `office=physician`, `office=therapist`, and `office=administrative` from the list of documented values that are rendered at z18
In issue #3794 it is noted that "the office dots render before or at the same level as the buildings and the building name gets "covered" at z17, where most office= names are not yet rendered. 
This PR moves the initial rendering of the dot marker from z17 to z18, and all frequently-used, documented values will have a name label rendered at z18. Currently a small subset are rendered at z17.
The three deprecated tags office=physician, office=therapist, office=administrative were removed from the explict list of documented values which are rendered at z18, but they will still render at z19.
The …

Increase "office=" initial zoom to z18 and move deprecated values to z19

---

amenity-points.mss
project.mml

**Fixes #3876**
**Fixes #3868**
- Restore rendering of text labels on points, including landcover and islands
Prior to #3764 most features in `landcover` had text labels rendered at high zoom level when tagged on nodes. For islands this was the case before  #1444. It appears that text labels of the name for points was unintentionally lost in these two PRs.
This PR restores this rendering by adding a check for way_pixels=null.
Suprisingly, `way_pixels != null` has to be checked for each instance of `[way_pixels > 12000]` or else the points render with the large lancover text size
Old rendering, before #3764 but after #1444
Current test rendering:
After this PR:

Restore rendering of text labels on points

---

addressing.mss
amenity-points.mss
stations.mss
water-features.mss
water.mss

- Remove `text-placement: interior` from features in `text-point` and other layers
Since the layers `text-point`, `stations`, `text-low-priority`, and `building-text` all use ST_PointOnSurface it is no longer necessary to use `text-placement: interior` except for features in text-poly-low-zoom (z9 and below)
- Remove `marker-placement: interior` 
This code is no longer needed because all layers used to place markers (`amenity-points`, `amenity-low-priority`, `station`) now use ST_PointOnSurface to select a point
- Remove one instance of unneeded code `text-placement: point` from natural_strait - this is the default text placement and does not need to be explicitly stated
Test rendering is unchanged.

Remove unused text-placement: interior and marker-placement: interior

---

addressing.mss
project.mml

- This appears to be the last relevant layer that needs to be switched now, unless we wish to switch all polygon layers to use ST_PointOnSurface
- Switch `addresses` to use ST_PointOnSurface
- This makes addresses consistent with `amenity-points` and `building` names.
- Address numbers will no longer be displayed separately than the POI or building name for oddly-shaped polygons
https://www.openstreetmap.org/#map=19/50.63295/3.06320
Before
After
Before
After

Switch addresses to use ST_PointOnSurface

---

admin.mss

- More detailed documentation for inner line rendering of protected areas. Maybe too verbose?
Cross-reference #3887 and https://gis.stackexchange.com/questions/287980/drawing-polygon-border-on-inside-only-in-mapnik/335537#335537

Documentation of inner line rendering

---

placenames.mss
project.mml

Related to #3201 - migration to server-side vector tiles
- Change `country-names` and `state-names` layers to use a point generated by `ST_PointOnSurface` instead of a polygon. This is necessary to be able to use vector tiles with this style.
- Remove `text-placement: interior;` from `place-names` since this code is no longer needed; the label will be placed on the point created
The label placement with `ST_pointonsurface` is better in some cases but worse than the current placement in others.
Liechtenstein country label:
Libya provinces:

Use ST_PointOnSurface for country and state text labels

---

project.mml

Adding parenthesis around additional conditions allows to use index and prevents from selecting all rows from DB containing "addr:housename" or "addr:unit".
Fixes #3937 
- Adding parenthesis around additional conditions
No changes in rendering

Apply bbox to part of "addresses" query

---

amenity-points.mss

Follow-up to #3829
- Remove lines referencing natural=marsh from amenity-points
- The rendering for natural=marsh was already removed in PR #3829, so these lines are unused, but I missed them in that PR.
- Rendering is unchanged

Remove natural=marsh from amenity-points

---

project.mml

- Give junction names and bridge names precedence over amenity-points.
Before:
After:
Rationale:
Often I see junction names that appear on z15, but later disappear on z16 or z17 because of some shops near to the junction, just to re-appear again on higher zoom levels when there is enough space for both, the junction name and the shop icon. I think the junction name is more important as the shop icon. Furthermore, for more consistency features that have yet appeared on z15 should in general not be hidden later by features that only appear on z16 or z17.
The “bridge” layer was just next to the junction layer. I've moved it also, because I think the same arguments apply here. There should be fewer …

Precedence of junctions over POIs

---

.travis.yml
amenity-points.mss
landcover.mss
placenames.mss
project.mml
roads.mss
shapefiles.mss
water.mss

- Do not use classes any more.
- Check with Travis that classes are not used any more.
This is a step towards vector tiles.
It seems surprisingly simple to eliminate the classes. Not sure if I'm missing something?

Don't use classes anymore

---

DOCKER.md

- Documentation update: Shut down native Postgre server before starting Docker Postgre server
Cross-reference comment https://github.com/gravitystorm/openstreetmap-carto/pull/3399#issuecomment-531548561 by @kocio-pl

Update Docker documentation

---

amenity-points.mss
water.mss

This is a bugfix PR for water body labels.
- Since #3764 (Stop label rendering for too big areas) water body labels disappear once the surface is quite big. In the same PR I had introduced a bug that makes labels appear again from z17. Consider the [Lagune Pouto](https://www.openstreetmap.org/#map=17/5.36215/-3.77535): The label correctly appears at z11, correctly disappears at z16 and incorrectly appears again at z17. The current PR will fix this.
- `natural_bay` has rendering rules both in `amenity-points.mss` (rendering a label in regular font) and `water.mss` (rendering a label in italic font). Consider the [Baie des sirènes](https://www.openstreetmap.org/#map=17/4.64612/-6.91497): The label is rendered in a regular font up to z16, but starting …

Fix rendering of water body labels

---

amenity-points.mss
project.mml

Fixes #3908
Partial revert of #3874 
Follow-up to fix bug in #3612
- Moves `amenity=parking`, `amenity=motorcycle_parking`, `amenity=bicycle_parking` and `amenity=parking_entrance` to `amenity-points` and `text-point` layers instead of `amenity-low-priority` and `text-low-priority`
- This fixes bugs where the building text or address number is shown instead of the icon and parking text, introduced by #3874 
- Parking had previously been rendered in both amenity-points and amenity-low-priority.
- Recently PR #3874 had consolidated parking rendering in low-priority only, but this leads to problems when there is a building or an address on the same feature
- This commit moves parking back to the amenity-points layer, but near the end. 
- The minzoom for text-low-priority is now changed back …

Move parking back to amenity-points layers, change way_pixels limit and fix initial zoom level

---

project.mml
style.mss
water.mss

This commit reverts PR #3930, which changed river color to #8fcadd for waterways and river, canal areas

Revert PR #3930 which added river-color

---

fonts.mss

Specifically, add a comma between "Noto Sans Adlam Unjoined Regular" and
"Noto Sans Armenian Regular". The missing comma resulted in the Armenian
font being missing from the generated Mapnik XML.
Fixes #3986.
Before
After

Fix syntax of font list and enable Armenian font

---

openstreetmap-carto.lua

This PR adds each of the 3 features as local linestring_values in openstreetmap-carto.lua:
- import `man_made=pipeline` closed ways as linestrings
- import `man_made=cutline` closed ways as linestrings
- import `power=cable` closed ways as linestrings
- All closed way features (ways which start and end on the same node and do not self-intersect) which are tagged with `man_made` or `power` are normally imported as polygons when added to the rendering database, as are linear `man_made` features like embankments and breakwaters.
- But there are exceptions for features that are only mapped as lines: currently `power=line` and `power=minor_line`, but `power=cable` is missing from this list of linestring exceptions.
- The tag `man_made=cutline` is also rendered and is only mapped as a line, so …

Import man_made=pipeline, man_made=cutline and power=cable as linestrings

---

project.mml
roads.mss

Related to #3201
- Use ST_PointOnSurface for roads-area-text-name in project.mll
- Remove no longer needed `text-placement: interior` from roads.mss
This is necessary to be able to use this style with server-side vector tiles.
https://www.openstreetmap.org/#map=18/47.13734/9.52334
before:
after:

Use ST_PointOnSurface for roads-area-text-name

---

landcover.mss
project.mml

Follow-up to closed PR #3834
Fixes #971
Also see discussion in about walls mapped as areas (not rendered) #3453
1) Stop rendering the green fill for hedges on polygons unless
2) Render standard green line for hedges on polygons instead
Currently all closed ways tagged `barrier=hedge` will render with the dark green hedge fill color when they are imported as a polygon feature. This happens for closed ways tagged area=yes, relations with type=multipolygon or type=boundary, and for closed ways that are tagged with another polygon key like landuse=* or amenity=*. Unfortunately, many mappers add barrier=yes to other features like landuse=meadow to describe that there is a hedge around most of the meadow. In this case the meadow will often render like a solid hedge area, which is incorrect. …

Remove polygon fill rendering for barrier=hedge

---

landcover.mss
project.mml

Closes #3744
- Remove the rendering of barrier=embankment
- Change minzoom for barrier layer to z15 since this is now the earliest that any `barriers` feature is shown (city walls).
- The tag `barrier=embankment` was once somewhat used, but never was documented in the wiki. Instead `man_made=embankment` or `man_made=dyke` are the much more common ways to make one-sided embankments and levees. The definition of `barrier=embankment` was not clear and it is not similar to the other barriers rendered in the same way (fences and walls), so it's best to no longer support this tag. (See #3744)
(Note: these images also show changes proposed in #3969)
(Test shows fence, kerb, wall, embankment from top to bottom)
Before
After

Remove rendering of barrier=embankment

---

openstreetmap-carto.lua

Related to #3611
- Add `aerialway=station` to list of local polygon tags in openstreetmap-carto.lua
- This will import closed ways tagged with `aerialway=station` as polygons for proper rendering as a POI.
- Currently aerialway= features are not imported as polygons when mapped as closed ways, but according to https://wiki.openstreetmap.org/wiki/Tag:aerialway%3Dstation this is also an allowed mapping method as an area
- Most `aerialway=station` features are mapped as nodes (24,000), but there are almost 2700 mapped as areas (http://overpass-turbo.eu/s/PFK)
Rendering is unchanged. Not expected to have a significant affect on import time based on tests with moderately sized .pbf extracts (luxembourg, Papua)

Import aerialway=station as a polygon feature

---

landcover.mss
project.mml

Closes #3714 
- <s>Remove the rendering of barrier=embankment</s>
- Remove the rendering of barrier=kerb 
- Kerbs (aka curbs) are rendered the same as significant obstacles like walls and fences. In issue #3714 I attempted to find a subtle rendering for kerbs which would not look like a fence or wall, but failed to find a good option for z19. Without rendering sidewalk and street areas these features are not intuitive.
- <s>The tag `barrier=embankment` was once somewhat common but never was documented in the wiki. Instead `man_made=embankment` or `man_made=dyke` are the much more common ways to make one-sided embankments and levees. The definition of `barrier=embankment` was not clear, so it's best to no longer support this tag.</s> (See #3744)
(Test shows fence, kerb, wall, embankment …

Remove rendering of barrier=kerb

---

amenity-points.mss

Fixes #3963
- Limit text rendering using `text-dy` to `generator:source=wind` only
Other power generators which are not buildings have their text labels rendered in the landcover font style, adjusted by way_area. Buildings do not need a separate rendering. Only wind generators have an icon, so only they need `text-dy: 10` for the name to be rendered properly
Test rendering:
Before
After

Only use text-dy for wind generators, not for other power=generator features

---

project.mml

- Remove way_pixels selection from bridge layer SQL query
The `bridge` layer for rendering man_made=bridge polygons does not use way_pixels, so this is not needed. Removing the line will slightly improve performance.
Test rendering is unchanged:
Before
After

Remove way_pixels selection from bridge layer

---

project.mml

- The column `name` was selected but not used for `water-areas`, `water-barriers-poly`, `water-barriers-line`, `bridge`,  `waterway-bridges`, `tourism-boundary`, and `protected-areas`. 
- The name labels for these features are rendered in different layers. 
- Therefore, `name` can be removed from the sql query for these layers
Test rendering is unchanged:
Before z16
After

Remove name from SQL select when unused

---

amenity-points.mss
project.mml

Related to #3201 - migration to server-side vector tiles
- Change `text-poly-low-zoom` layer to use `ST_PointOnSurface` - this is necessary to use this style with vector tiles, and this makes the low zoom rendering consistent with the label placement at higher zoom levels (z10 and up
- Also remove unneeded `text-placment: interior` for the polygon features affected - this code is no longer needed, because the labels are placed on a point, not in a polygon, by Mapnik at the time of rendering.
z8 Libya
https://www.openstreetmap.org/#map=8/27.330/17.216
z9 Wan am namus
https://www.openstreetmap.org/#map=9/24.8628/17.7742

Change text-poly-low-zoom to use ST_PointOnSurface

---

project.mml

Related to #3201
- Use ST_PointOnSurface for `junctions` layer in project.mml
Test rendering:
Before
After
This PR will need to be updated after #3915 is merged

Use ST_PointOnSurface for junctions

---

amenity-points.mss

Fixes #3946
- Remove `operator=` text label rendering for `amenity=vending_machine` features
The operator tag is often incorrect and rarely helpful for these features. 
Searching for all in Wales with operator= finds a few more useful examples, including: "Amazon" , "Transport for Wales", "Knolton Farmhouse Cheese", "4CG", and "Newport Bus".
But many more operator tags are unhelpful: "Ceredigion Council", "Pembrokeshire Coast National Park Authority", "Pembrokeshire County Council", "Conwy Council", "Bangor University" x2, "Campus Catering", "Caerphilly County Borough Council".
The example given in issue #3946 is [node 4329279576](https://www.openstreetmap.org/node/4329279576) which has the operator is "Stadt Göttingen", meaning "Göttingen City", so rendering this is not useful.
It would …

Remove operator text label rendering for amenity=vending_machine

---

openstreetmap-carto.lua

Related to #3611 and #3865
- Add waterway=tidal_channel to the list of linestring exceptions in openstreetmap-carto.lua so that closed ways with this tag will only be imported as a linestring
- This tag is only used on lines, similarly to waterway=stream and waterway=river
- While it is not currently rendered, there are over 2,500 features with this tag: https://wiki.openstreetmap.org/wiki/Tag:waterway=tidal_channel
- Adding this to the lua transformations file will make it easier to render this feature correctly in the future or in other map styles which are based off of this style.

Import waterway=tidal_channel as a linestring

---

openstreetmap-carto.lua

Related to #3611 and #1697
- Import the key `craft=` as a polygon when mapped as a closed way
- Adds 'craft' to the list of polygon keys in openstreetmap-carto
The key "craft=" is similar to "office=" in that it can be used on points or areas. It is commonly used and there is a chance this will be rendered in this style, or if not, then in others based on it: http://wiki.openstreetmap.org/wiki/Key:craft

Import the key `craft=` as a polygon

---

project.mml

Fixes #4022
- Changes the geometry of building-text, text-poly-low-zoom and roads-area-text-name to point, because these layers now are labeled as a point, created by ST_PointOnSurface
Thank you for catching this issue, @imagico 
Test rendering is unchanged.
I don't think this will affect performance.

Change geometry to "point" for building-text, text-poly-low-zoom & roads-area-text-name layers

---

openstreetmap-carto.lua

Related to  #3611 and #2288
(Fixed version of #4012)
- Add [natural=earth_bank](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dearth_bank) to the list of linestring exceptions in openstreetmap-carto.lua so that closed ways with this tag will not be imported as polygons, but as a linestring only.
- This tag is only used on lines, similarly to natural=cliff or man_made=embankment
- While it is not currently rendered, there are over 4,000 features with this tag, including 202 closed ways (where the bank encircles an area) which are not intended to represent areas. http://overpass-turbo.eu/s/Qa3
- Adding this to the lua transformations file will make it easier to render this feature correctly in the future or in other map styles which are based off of …

Import natural=earth_bank as a linestring

---

openstreetmap-carto.lua

Related to #3611 
- Import closed ways which are tagged with the key `club=*` as polygons
While this style is unlikely to render features with this key, some contributors have suggested that this style should provide a complete list of the main keys and tags which are intended to be mapped as areas (polygons)

Import closed ways with the key `club=` as polygons

---

openstreetmap-carto.lua
scripts/lua/test.lua

ref. https://github.com/gravitystorm/openstreetmap-carto/issues/3611#issuecomment-582672393
Checked by loading an extract and verifying that building=no with other polygon tags are still areas, and then loading just a building=no way

Don't form areas from tags like building=no

---

openstreetmap-carto.lua

Related to #3611
- Import closed ways tagged with the key `emergency=` as polygon features, with exceptions for those values which are used as "access" tags on lines: designated, destination, no, official, yes
While we have not decided to render any specific `emergency=` features now or in the next few months, it is possible that this will be desired in the next few years. Also, other styles which are based off of this stylesheet may wish to interpret `emergency=` features, so it is beneficial to have a proper import schema for this tag.

Import emergency= features as polygons, with exceptions

---

landcover.mss

- Intermediate step before #3670
- Only fade from z11 and only 1 level - reduces the 3 level fading to only one level, using `lighten 0.2` instead of 0.4.
- Remove built-up-z11 color - this is no longer needed, since z11 is now the same as z10 and below
- Change `@built-up-z12` to `#dddddd` - this maintains the current rendered color at z12
- Change `@built-up-low-zoom` to `#d0d0d0` - same as current `@built-up-z12` color
As discussed in issue #3936 and the WIP PR#3670, the current fading of the landcover layers at low and mid-low zoom levels makes it difficult to distinguish different types of landcover/landuse at z12 and below.
Roads, railroads, and waterways are much more prominent than landcover at z12 and below, especially at z10 and below. Water areas are not faded, and therefore …

Reduce landcover fading at mid-low zoom levels

---

landcover.mss
project.mml

Related to #3707 and #545
Reverts #2746 - addition of `beach.png` pattern for `natural=sand`
- Remove pattern rendering for natural=sand from landcover-area-symbols (where it renders above water areas)
- The tag `natural=sand` is currently rendered with a unique color fill, different than beaches or bare_earth, so the pattern is not needed to distinguish sand from similar areas. Removing the pattern will make the map less busy. This will also make it easier to add a pattern for `natural=dune` areas, if desired.
- Removing the natural=sand pattern will also hide areas tagged natural=sand outside of the coastline. These should be tagged `natural=beach` or `natural=shoal`.
http://www.openstreetmap.org/#map=17/53.31607/-3.50920
z17 before
z17 after …

Remove overlay pattern for natural=sand

---

project.mml

Fixes #3984
- Removes rendering of power=cable features which are currently rendered (those tagged with location=overhead, =overground, =surface, =outdoor and =platform). 
Currently only the small minority of `power=cable` features with `location=` values of `overhead, `=overground`, `=surface`, `=outdoor` and `=platform` are rendered. Most power=cable features are underground (or under water).
These location values are rare, the vast majority of power cables are underground or undersea, and the documentation suggests that this tag should usually not be used for overhead and overground cables. Some mappers occasionally use this tag instead of `power=minor_line` for distribution lines on poles which happen to use insulated cables instead of the usual …

Remove rendering of power=cable features

---

project.mml

Fixes #4030 
I used 768000 for POIs, which is about 12 tiles, and 4000000, which is about 64 tiles for cases like countries where we want to show larger objects.

way_area conditions for all ST_PointOnSurface layers

---

.travis.yml

9.3 and 9.4 are EOL, so we don't need to do this check anymore.

Remove Postgres 9.3 tests

---

.travis.yml

I kept node back on 10 because [node-gdal doesn't support node v12](https://github.com/naturalatlas/node-gdal/issues/258).

Move Travis to Ubuntu bionic

---

.travis.yml

We no longer use `world_boundaries` but there was a reference to it left in Travis

Remove left-over reference to world_boundaries in Travis

---

scripts/lua/test.lua

This recovers some tests from #4052 that are still worth adding.

Add z_order tests

---

openstreetmap-carto.lua

The usage of some tags has fallen to close to zero, so we can remove them from the deleted list.

Remove tags from deleted that are no longer common in the DB

---

openstreetmap-carto.lua
scripts/lua/test.lua

Fixes #4055
Fixes part of #3579 
Follow-up to #4055 and #3579 
@jeisenbe Could you do rendering tests of this? All I've done is the code, unit tests, and checked it doesn't crash osm2pgsql.

Add z-order for roads under construction

---

.github/workflows/ci.yml

GitHub actions are generally faster to run than Travis. There's been some reports of network problems in the chef and Vespucci repos, but I haven't encountered any, and we're relying on different network resources than they are.
Because this is new, I'm leaving Travis in place in parallel.
This only adds actions that don't require CartoCSS or a database.

Add Github Actions in parallel to Travis

---

style/water.mss

Partial Fix for #3273 
Revert of #2952
- Remove >1 pixel way_area filtering for low zoom water
- Clean up code to simplify rendering of water areas. Now waterway=dock and landuse=basin will be the same as the other features.
There is still a 1 pixel limit in the SQL select which is probably necessary for z0 to z6 at least, but I would like to consider changing this in the future. See related discussion in #1604 and #754, however. Since the SQL code currently allows rendering down to 1 pixel without significant performance issues, this change should be a good first step. 
Filtering out some water areas at lower zoom, as done currently since v4.6.0, shows fewer lakes and rivers at low zoom level, without significantly improving performance. The 32 …

Remove way_area filtering for low zoom water and simplify code

---

style/amenity-points.mss

Related to #4002, #1745 and PR #1884
- This PR, similar to closed PR #1884, moves amenity=atm and amenity=post_box to z18, though in this case they are currently rendered only at z19, while previously they were rendered at z17. 
- Also emergency phones are moved back to z18 from z19. Previously they had been rendered at z17
This is an attempt to compromise. While these features were moved from z17 to z19 without consensus, rather than attempting to move them back to z17 we can use z18.
In rural areas these features should be shown at z17, while in some very large cities (e.g. Warsaw) there may be many icons in one screenshot at that zoom level due to the high density of features in capital cities.

Move small amenities to z18

---

project.mml

- Remove duplicate selection of natural = cave_entrance, peak, volcano and saddle
- The features `natural=cave_entrance`, `natural=peak`, `natural=volcano` and `natural=saddle` are always mapped as nodes, so they should not be selected when mapped as areas
- They are selected in the previous line when way_area is null. It appears that this was accidentally duplicated when text-poly, text-point, amenity-points etc were merged into one layer.
We could consider still rendering `natural=cave_entrance` on areas. JOSM allows it, but this is only done 1% of the time. However, I'm keeping it simple and just removing this bug now. If someone is in favor of rendering `natural=cave_entrance` areas, that can be done in a separate PR.
Test rendering with links to …

Remove duplicate selection of cave_entrance, peak, volcano and saddle

---

style/landcover.mss

- Change quarry outline to 10% darkened quarry color rather than `gray`
- This makes the outline significantly lighter, and clearly different than a barrier
Currently the quarry outline looks similar to a fence or wall on untagged land. This makes it hard to tell if a quarry is surrounded by a wall or fence, or not.
I also tested `darken(@quarry, 15%)` and `darken(@quarry, 20%)` but these look too similar to the linear barrier rendering, while the current commit uses `darken(@quarry, 10%)` and this works well.
This should also make it easier to adapt the style or change the quarry color in the future (though it is always a good idea to adjust the darken percentage if the fill color is lighter or darker than before)
z16 Slate quarries in Wales - current …

Change quarry outline to 10% darkened quarry color

---

project.mml

Fixes #2849
- Remove unused `VALUES` join from roads-text-name
This table is no long used, instead the `z_order` function is used to select the order of rendering, so it can be removed.
Rendering is unchanged.

Remove unused `VALUES` join from roads-text-name

---

project.mml

Fixes #2735
- Remove unneeded explicit `ELSE NULL` from case statements in project.mml
These statements are not needed, because "NULL" is the default when none of the cases are true.
In #2735 there was agreement that these explicit NULL statements are not helpful
Rendering appears to be unchanged.

Remove unneeded `ELSE NULL` from case statements

---

project.mml

Standardize ORDER BY to use CASE expressions
Fixes partially #2850 
- Remove prio table from amenity-low-priority and move CASE statement to ORDER BY
- Simplify CASE statements in power-towers, aeroways, placenames-medium
(Does not address the rather complex priorty expressing in turning-circle-casing
Also, "score" is still used for peaks and waterfalls in amenity-points)
Test rendering is unchanged.

Standardize ORDER BY to use CASE expressions

---

project.mml
style/amenity-points.mss
style/landcover.mss

Fixes #3871
Fixes #3405
- Remove rendering of power=sub_station - this tag has been replaced by power=substation
- Remove rendering of power=station - this tag has been replaced by power=plant
- Render the `@power` fill color for `power=plant`, same as with `power=substation`
Currently we still render the old tags power=sub_station and power=station, but the new tags power=substation and power=plant are many times more common now: 
power=sub_station is much less popular than power=substation ([300k](https://taginfo.openstreetmap.org//search?q=power%3Dsub_station) > [13k](https://taginfo.openstreetmap.org//search?q=power%3Dsubstation))
power=station has dropped steadily ([3k](https://taginfo.openstreetmap.org//search?q=power%3Dstation)) vs …

Remove power=sub_station/station rendering, add power=plant fill color

---

Dockerfile.import

Recent builds of the Dockerfile.import failed because they couldn't
download the key for the osmadmins PPA.  Specifying hkp and port 80
fixes this.
Fixes #3999
This commit makes no changes to rendering.
Note: This works on my machine in different parts of a corporate network. I was not able to test it more widely, but I expect other networks may be more open and may not have had the original issue.

Update keyserver URL for osmadmins PPA

---

project.mml
style/roads.mss

Fixes #4050
Fixes #4019 
- Change bridge-text way_pixels minimum limit to 125 (previously 62.5) and maximum to 768000
- This doubles the minimum area in pixels from the current limit (equivalent to 1/2 zoom level), and increases the max pixel area limit to match other features, to prevent double-tagged features from showing a different text label style at low zoom.
- A higher limit of 187.5 pixels (2 zoom levels sooner than other area features) was also tested, but this excludes some mid-sized bridges. 
Chicago before z15:
After 125 way_pixel limit:
Bridge with landuse=railway before - https://www.openstreetmap.org/way/124882971
z18 (same)
z19 before
z19 after

Change bridge-text way_pixels minimum and maximum

---

style/amenity-points.mss

The symbol used for tactile_model is the same as that used for a map, which is misleading
Fixes #4021
- Remove `information=tactile_model` rendering
The symbol used for `tactile_model` is the same as that used for a map, which is misleading

Remove information=tactile_model rendering

---

project.mml
style/amenity-points.mss
style/water-features.mss

Fixes #4011
- Move `natural=spring` icon back to amenity-points layer, delete current `springs` layer
- Previously springs were rendered below water-lines. This is not longer the case, so springs can be rendered with other symbols again
- Springs now render above paths and highways, like other point symbols.
- This change should slightly improve performance, and springs will no longer render with priority to placenames such as hamlets and villages.
z14 Before
z14 After - place label now seen (upper left)
z15 before
z15 after
z16 before
z16 after
- Shinto place of worship, place name, and funicular station now all show with priority over the springs.

Move natural=spring back to amenity-points layer

---

project.mml
style/aerialways.mss

Fixes #640
Related to #3180 and #3179
- Add rendering of man_made=pipeline ways from z14 when tagged with location=overground, =overhead, =surface, or =outdoor, or with documented bridge=* values.
- Add different renderings for substance=water, substance=oil and substance=gas from z17:
- - gas `#c1c1c1` Lch(78,0,0) 
- - oil `#d7bd93` Lch(78,25,83), 
- - water in `@water-color` (currently `#aad3df`)
There are several "substances" related to heat, like "steam", "hot water" and "heat" but no consensus yet, and no other substances are common yet.
- Add text label for named pipelines from z17
- Change aerialway minimum-distance to margin and repeat-distance (The property minimum-distance is deprecated and cannot be used with the new properties margin and …

Add rendering for man_made=pipeline ways

---

project.mml
style/landcover.mss

Fixes #1490
- Add sports_centre (`@stadium`, =`@leisure` currently) fill color for `leisure=water_park` polygons
- According to the wiki, water parks should be mapped as an area; [taginfo confirms](https://taginfo.openstreetmap.org/tags/?key=leisure&value=water_park) that over 75% are mapped in this way.
- The current rendering is identical to the rendering of `leisure=swimming_area` and `leisure=sports_centre` + `sport=swimming`, except that the area of the feature is not shown
- The previous discussion in #3748 showed that the tag leisure=water_park is not only used for large theme-park-like tourist attractions, but also for smaller local recreational areas with 1 or 2 pools, plus water slides, therefore rendering the same as zoos and theme parks is not appropriate.
**Piscine de …

Add sports_centre (@stadium) fill color for leisure=water_park areas

---

project.mml
style/addressing.mss

Fixes #3988
Render addr:flats similar to addr:unit.
Accounting for combinations with addr:housenumber, addr:unit, addr:housename.
- haven't had a chance to figure this out.

Render addr:flats

---

project.mml
style/admin.mss
style/placenames.mss

**Part of #4004 potentially**
**Fixes #310**
**Fixes #3698**
**Partially addresses #3678**
**Partially addresses #4016**
- Change line rendering for admin boundaries: thinner and more consistent steps in most cases
- Adds central dark line for admin_level=2,3,4 at mid and high zoom levels
- Use lower opacity for the admin_level=2,3,4 wide line, but high opacity for thinner, minor boundaries
- Render admin_level=5 from z8 (3 zoom levels sooner) - makes it possible to add central label
- Render admin_level=6 from z10 (1 zoom level sooner) - possible to add central text label
- Render admin_level=7 from z11 (1 zoom level sooner)
- Render admin_level=10 from z14 (1 zoom level later)
- Change admin boundaries color to be less saturated - final color selection is still a work in progress, and …

Rework admin boundaries and show admin_level=5/6/7 sooner, level=10 later

---

project.mml
style/roads.mss

Fixes #3995
Fixes #1967
Removes the rendering of highway=residential area=yes and highway=unclassified area=yes polygons. In #3995 these were established to commonly be a tagging mistake.

Remove rendering of residential, unclassified, cycleway, footway, path highway areas

---

project.mml
style/landcover.mss

- Change wetland pattern initial zoom back to z10
- Change landcover-area-symbols intial zoom back to z9
https://www.openstreetmap.org/#map=9/53.0313/-3.1421
Before z9
After z9
Before z8
After z8
Before z7
After z7
https://www.openstreetmap.org/#map=9/56.5125/26.4606
Before z9
After z9
Before z8
After z8

Change wetland pattern initial zoom to z10 again

---

project.mml
style/amenity-points.mss
style/placenames.mss

Fixes  #4043
- Removes rendering of `place=square` areas from roads_area_text_name and moves rendering from placenames to amenity-points like place=locality, since the text label is only rendered at z17 and above. 
- This change improves the rendering priority system, since now place=square features will not block icons which are rendered at z15 and z16. 
- The text style is slightly adjusted to match `place=locality` and `place=neighborhood` features
This makes place=square rendering consistent with `place=locality`, and more similar to `place=neighborhood` and `place=quarter`, with the rendering starting at a fixed zoom level.
Currently, very large place=square areas will render sooner than z17, and very small features will ony render from z18. Now …

Render place=square in amenity-points layer with placenames style from z17

---

project.mml

Fixes #3179
- exclude `tunnel=flooded` for waterways
https://www.openstreetmap.org/way/369442787
Before
After

Remove the rendering of waterways with tunnel=flooded

---

style/landcover.mss

- Renders `rock_overlay.png` pattern from z13 only, instead of z5, for `natural=bare_rock`
- This is the same level when the similar features `natural=scree` and `natural=shingle` are first distinguished from `natural=bare_rock` by a pattern.
- At mid and low zoom levels the great majority of bare_rock areas are too small for the pattern to be clearly seen, but the pattern adds noise and makes it harder to interprete the outline of these areas. For this reason, the pattern is not shown for scree or shingle before z13 (similarly, scrub, forest and other patterns are not shown before z13).
- Currently the only very large areas of bare_rock are coarsely-mapped desert areas, which really consist of a mix of sand, scree, bare_rock, heath, grass, etc, and our showing the pattern early gives …

Render bare_rock pattern from z13, same as shingle and scree

---

project.mml
style/admin.mss

Needed prior to #3656
- Stop rendering boundary=protected_area with protect_class = 7,  protect_class = 24, and  protect_class = 97, 98, or 99
- Move leisure=nature_reserve selection after boundary=aboriginal_lands in `amenity-points`, to match `text-point-low-zoom` layer. 
- The tag `boundary=protected_area` is mostly tagged with protect_class = 1a, 1b, 2, 3, 4, 5, 6 which match the IUCN categories for "Strict Nature Reserve (IUCN Category 1a)", "Wilderness" (IUCN 1b), "National Park" (2), "Natural Monument or Natural Feature" (3), " " (4), "Protected Landscape or Seascape" (5), "Area with sustainable use of natural resources (6). 
- Sometimes these IUCN categories, from the Internation Union of Conservation Naturalists, are used with boundary=national_park or leisure=nature_reserve as …

Remove rendering of protect_class = 7, 24, 97, 98, 99 boundary=protected_area features

---

style/admin.mss

Fixes a mistake in PR #4100
- Add back admin_level=3, =4, =5 admin-text rendering along border lines from z11
The rendering of `admin-text` labels for these zoom levels was accidentally removed in PR#4100
- Boundary of admin_level=3 and admin_level=4 areas in Papua New Guinea
- https://www.openstreetmap.org/#map=11/-4.9966/143.9676
Before
After

Restore admin-text rendering for admin_level 3 to 5

---

project.mml
style/aerialways.mss
style/amenity-points.mss

Fixes #4105 and part of #4104
- Move `aerialways`layer text labels to `text-line` layer
- Move leisure=track and attraction=water_slide name labels from `amenity-line` to `text-line`
- Add leisure=slipway name label on lines in `text-line`
Currently the `aerialway` and `man_made=pipeline` features in the `aerialways` layer have their name label text rendered in the same layer. This means that another pipeline, or aerialway, or a road bridge can render on top of the text, and the text is rendered at higher priority. 
The same problem occurs for `leisure=track` and `attraction=water_slide` features, which are rendered in the `amenity=line` layer as lines, along with their name labels. 
Also, I noticed that `leisure=slipway` only has a label when mapped as a node, not when mapped as a line, …

Move aerialways and amenity-line layers text labels to text-line layer

---

.travis.yml

At the moment there is only version 10 which has been released back in 2018. This project should also be able to build with a modern version of NodeJS.
- Build against NodeJS 14 as well as NodeJS 10
Older versions can be removed in the future.

Travis: Build with NodeJS 10 & 14

---

style/roads.mss

- fixes the rendering of highway=secondary_link so that the casing becomes properly visible
https://www.openstreetmap.org/way/30071699
Before
After

fix rendering of highway=secondary_link at z12

---

.travis.yml

- Also build the Carto configuration against Mapnik 3.0.22 for improved diagnostics from new Mapnik versions

Travis: build against Mapnik 3.0.22

---

INSTALL.md
indexes.sql
indexes.yml
project.mml
scripts/indexes.py

Using an index for ST_PointOnSurface queries speeds up the queries
substantially by avoiding work for when the geometries are in the
bounding box but the labeling point isn't.
The impact is substantial for large geometries like administrative
areas that have a lot of matches.
For these indexes to be reliably used, the plain way && !BBOX!
condition needs to be removed from the WHERE clause, making
the index required instead of optional.
I tested this by building the new indexes on my database and browsing in Kosmtik while watching query times. Any queries which were unable to use the indexes would have stood out because I have a full planet database.

Use custom indexes to speed up ST_PointOnSurface queries

---

external-data.yml

The Natural Earth website has frequent problems with going offline
while the CDN is much more stable.
Fixes #4304

Switch from Natural Earth to its CDN

---

Dockerfile.db
docker-compose.yml
scripts/tune-postgis.sh

For local development, the Dockerfiles are used to set up a development environment. 
The database is created with the Dockerfile.db image, which is based on the image `mdillon/postgis` (https://hub.docker.com/r/mdillon/postgis/). This base image has not been updated for 2 years. Moreover, the Dockerhub link links to the official PostGIS image `postgis/postgis` (https://github.com/postgis/docker-postgis).
This PR updates the base image for the Dockerfile.db. The official image of PostgreSQL 10 with PostGIS 2.5 is used. The alpine version is used which results in a smaller image to download.
Using this base image will allow updating to more modern Postgres versions as well (see the full list in https://registry.hub.docker.com/r/postgis/postgis/tags).  In the future, newer PostgreSQL and …

Update DB dockerfile to use the postgis image

---

style/amenity-points.mss
symbols/amenity/parking_subtle.svg

For `amenity=parking` of the type `parking=street_side` (street-side parking in bays and other demarcated parking areas) and `parking=lane` (parking on a lane alongside a street), the amenity icon is replaced with a smaller one that is shown from `z18` onwards.
With the introduction and formal acceptance of `parking=street_side`, mappers now have a way of indicating that a mapped parking amenity is a parking bay/area on the side of a street. This tag gives renderers a chance to solve the problem of these parts of the street layout from cluttering the map with large blue **P**'s that are better suited for larger parking lots.
This commit introduces a smaller **P** icon that is pixel aligned to match the crispness of the existing generic parking **P**.
Fixes #4262.
-----
No **P** for …

De-emphasize parking=street_side

---

style/stations.mss

Fixes #4389
- Begin rendering text for `railway=station` + `station=subway` at z>=15.
- [Chicago](https://www.openstreetmap.org/#map=14/41.8793/-87.6298)
- [Philadelphia](https://www.openstreetmap.org/#map=14/39.9482/-75.1672)
- [New York City](https://www.openstreetmap.org/#map=14/40.7178/-73.9888)

Make text for subway stations render at z>=15

---

symbols/advertising_column.svg

Side-to-side shape connections can lead to artifacts on some zoom levels.
I didn't create an issue since the fix is pretty small.
- Fix `advertising_column.svg` shape.
Before (you can see pale white line between `tip` and `top` shapes)
After

Fix advertising column shape

---

scripts/get-external-data.py

Fixes #4447
Tested against psycopg2 versions 2.8.6 and 2.9.1
The calls to `self._conn.commit()` should be superfluous in version 2.9.1 of psycopg2 but are still needed in older versions.

Updated to work with pyscopg2 version 2.9.1

---

external-data.yml

Fixes #4461
Changes proposed in this pull request: The link to the `ne_110m_admin_0_boundary_lines_land.zip` dataset is down due to some issues with hosting. [According to the Natural Earth Vector maintainer](https://github.com/nvkelso/natural-earth-vector/issues/581#issuecomment-913988101), you should now use the URLs for S3. The URL and formating of the URL to the new dataset should look like this and appears to be the same file from before: https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip

Fix URL for natural earth vector dataset.

---

style/landcover.mss

This is very minor.
`landcover.mss` defines an image filter for high zoom levels that has no effect.
For a moment I thought it could be a cause of color artifacts with SVG images (which was not the case).
This commit just removes the filter.

Remove hsla-filter that has no effect

---

style/admin.mss

Fixes #4113 
PR #4113 removed `protect_class` rendering for various values of that key, including `protect_class=24`.  However, it appears that one of the selectors was inadvertently missed.  This PR removes this code which is no longer needed.

Cleanup of missed protect_class=24 selector

---

docker-compose.yml

Set platform:linux/amd64 in docker-compose.yml to allow running with docker on new Apple machines with ARM64 processors.
Without explicitly setting this all docker compose commands including `docker compose up` and `docker compose build kosmtik` fail due to a lack of prebuilt binaries for arm64.
A native image would be more performant but this workaround allows at least allows development on new Apple machines.
Fixes #4538
- Explicitly set platform: linux/amd64 in docker-compose.yml
Before
After

Allow building on ARM64 machines by setting platform: linux/amd64

---

style/amenity-points.mss

The colour of the icon (purple) and the label (brown) don't match.
This commit makes the label purple to match most other `shop=*` tags.
Fixes #2658
-----
_This is one of two ways to solve this. The other colour choice is shown in #4536. These two PR's are mutually exclusive._
_Either one is probably better than:_ ![nope](https://user-images.githubusercontent.com/683699/164528484-f6b6ff94-59d9-45a2-b479-b0a8c6370cf9.png)
-----

Fix shop=car_repair label/icon colour mismatch (purple)

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
DOCKER.md
INSTALL.md
README.md
RELEASES.md

Fixes minor issues with URLs. See commit descriptions for additional notes. furthermore, see #2341 ).
Fixes #4253, though this PR is not focused on changing links in comment lines; can be done seperately (usually unmaintained).
See also
- #2291 (review onboarding in general)
- #2341 (improve workflow link)
- #4323 (improve alternatives)
- /pull/4520 (for Debian update)

Upgrade URLs

---

project.mml
style/water.mss

The SQL query of `water-lines-casing` was a subset of the one for `water-lines`, so it is easy to turn it into an attachment to that layer. This removes one small query.
I have checked the generated Mapnik XML, the styles are in the right order now part of `water-lines`. No visual changes.

Make water-lines-casing an attachment of water-lines

---

Dockerfile.import
INSTALL.md
scripts/get-external-data.py

This allows to recreate the database objects without the need
to redownload all the (not so small) files.
Additionally it outputs stderr of `ogr2ogr` on error (which was collected but not displayed).
Motivation:
I got hit by https://github.com/OSGeo/gdal/issues/1692 and every time I re-ran the get-external-data.py script it tried to download ~600 MB of data (water-polygons-split-3857.zip).

get-external-data.py: store downloaded archives for further use

---

scripts/get-external-data.py

As mentioned in #4153, here is the change.
> To eventually support last_modified with local files, too, as requests-file does not return the modification date at all.
> 
> Note it is not there yet, but I may implement in an extra commit this weekend if you'd like to see it.

get-external-data.py: Support last modified for local files (file://)

---

symbols/barrier/gate.svg

Fixes #4599
#4457 removed the fill from symbols/barrier/gate.svg, which was correct, but there wasn't a marker-fill for this icon in the MSS. This PR adds that.
With PR:
master:
cc @pitdicker

Use barrier icon for gate fill

---

INSTALL.md

PostgreSQL JIT cripples Kosmtik, and slows down rendering of some zooms.
Fixes #4095

Recommend disabling JIT

---

project.mml

While testing I noticed that on zoom 15, the turning circle query is one of the slowest. This change reduces the duration from 20ms to to 1.2ms. The query times were several seconds with cold caches, but that is difficult to benchmark and reproduce.
No rendering changes.

Use indexes for turning circle queries

---

style/amenity-points.mss

#2736
Concerns:
#1753
#2789
- Change natural=tree and natural=tree_row color from 'green' to the same color as forest
- Change the trunk color of tree node to the same as the forest svg overlay
- Add back trees up to z16 given the lower visibility
#2736 is closed as integrated in #1753, however no work as been done on the latest for 3 years. This pull request at least solve the outstanding tree colors, I doubt the original #00ff00 was of particular cartographic significance.
The transparency of the canopy has been kept, I guess in urban areas some will be attached to this transparency. #1753 is slightly improved, but not solved. Switching layer order could solve while keeping transparency.
I decided to add back the trees up to zoom 16, this was …

Single tree and tree_row colors as forest

---

style/amenity-points.mss

#3759 + previous PRs changed the text-points feature=shop_mall into feature=shop shop=mall. This was done incorrectly in one place where the [feature='shop'] condition was not added, leading to having to check for shop=mall on everything else in the layer, even if it didn't have feature=shop.
This change brings compilation time from 9s to 6.5s and the text-point layer from 2.3s to 1.1s. The total XML decreases from 46670 to 45404 lines.
ref #1941

Require feature check when checking for mall

---

.github/issue_template.md
CODE_OF_CONDUCT.md

Fixes #4552
This proposes to explicitly state that revealing identifying information about a user against their wishes is unwelcome behavior on the project.

Explicitly state that revealing a user's identifying information is unwelcome behavior

---

project.mml

Fixes #4270 
-` OR (amenity = 'shelter' AND tags->shelter_type NOT IN (public_transport, picnic_shelter))`

Public transport shelter should not be labeled with elevation

---

amenity-points.mss
project.mml
water.mss

Fixes #3634 and #3705
Reverts #3438 and #3144
Related to discussion of `way_area` based name label rendering in #3284 and #2700, also see #2702
- Stop using `way_area` to set zoom level and text size for natural=bay and natural=strait text labels
- Render name labels for straits and bays at z14 and above
- Do not render text labels for lakes, reservoirs or docks before z5
- Since #3438 and #3144, natural=strait and natural=bay have been rendered identically to lakes (natural=water and landuse=reservoir) when mapped as an area (closed way or multipolygon relation). Depending on the `way_area`, they will render as soon as z0 in theory, and in practice there is currently a bay rendered on z3. 
- This led to issue #3634, which recommends that natural area labels should not be shown at z4 and …

Render name labels of bays and straits from z14 only, lakes from z5 only

---

scripts/get-external-data.py

It has been brought to my attention in #4626 that I forgot to implement "table" part of `--no-update` help entry
> Don't download newer data than what is locally available (either in cache or table). Overridden by --force

Fix get-external-data.py ignoring populated table when --no-update is set

---

.gitignore
INSTALL.md
scripts/docker-startup.sh
scripts/get-fonts.sh
style/fonts.mss

Fixes #4602
Fixes #4490
Fixes #4520
Fixes #4610
This moves to downloading a copy of the fonts locally, allowing more recent versions to be used, guarantee coverage, and eliminate fallback fonts for old systems. In addition the CJK font is re-ordered with the Arabic font to stop overwriting the design of commonly used signs in other fonts.
By having a more recent copy, it allows the number of scripts with bold support to be significantly improved.
The total download size is 98MB

Use local copy of fonts

---

project.mml

Fixes #4638
- The PR #3750 has changed the rendering of _labels_ for big water areas. I didn’t read all the PR comments, but I suppose removing the rendering of the _areas themselves_ was not intentional?? If so, this PR restores the rendering of water bodies on low zoom levels.

Restore broken rendering of big water areas on low zoom levels

---

project.mml

By splitting MPs into polygons, taking the largest, and finding a point in 4326 we get better points for placing labels. 4326 does distort the placement, but it does so in a way that results in better results for most countries.
When monitoring for slow queries, this query does not take significant time compared to other layers. I have some upcoming work that will improve the other queries, as some of them are quite slow on low zoom.
I am making this change for countries only because
- splitting and calculating true area is only different from what st_pointonsurface does if there is a significant north/south difference in the different polygons that make up a MP. In practice, this means only countries are impacted.
- The difference for ST_PointOnSurface between 4326 and 3857 is only …

Improve country label placement by splitting

---

project.mml

Fixes #4566 
- Adds elevation rendering for `tourism = wilderness_hut`
https://www.openstreetmap.org/way/985409968#map=19/48.49545/-121.20517
**Before**
**After**

Add elevation rendering to tourism=wilderness_hut

---

project.mml

This way `mapnik` does not have to make expensive queries at XML loading time just to find the layer's projection. This helps a lot shortening feedback loops while modifying the style and viewing the result in f.i. `kosmtik`.

Add SRID to postgis datasources

---

indexes.sql
indexes.yml

One of the slowest queries at zoom 5 is for the text-poly-low-zoom
layer. This index speeds it up, and similar queries up substantially.
No rendering changes.
This index brings a text_poly_low_zoom query down from 120s-31s warm and 6.5s hot to 825ms hot, and improves the experience when developing low zooms.
Index build time on my system is 6:35, and index size is 31MB.

Add an index for names at low zoom

---

style/amenity-points.mss

Fixes #4619
- Remove  name rendering of `information = board`
https://www.openstreetmap.org/node/8423226477
**Before**
**After**
This is my first pull request here, so please forgive me if my method of removing the name is not the preferred way :)

Remove name rendering for information=board

---

style/roads.mss

Avoid noise because of patterns on narrow roads
Fixes #4657 
- Access restriction dashing and unpaved pattern are removed on very narrow road signatures

Avoid noise because of patterns on narrow roads

---

style/roads.mss

Fixes #4656
Better visibility for access restrictions, particularly on unpaved roads.
Before:
After:
Before:
After:

Better visibility for access restrictions

---

.gitattributes

- YAML highlighting on GitHub webpage for CartoCSS MML files
It is possible to [force a specific syntax highlighting](https://github.com/github/linguist/blob/master/docs/overrides.md) for specific file types on the GitHub web page. So we can make `*.mml` files, which are currently not highlighted in our repository, get YAML highlighting: `project.mml`
Note that this PR will not have an immediate effect. [Only after the _next_ commit that touches the MML file, the syntax highlighting will be available.](https://webapps.stackexchange.com/questions/31654/force-github-syntax-highlighting-language-on-source-files#comment139871_108676) (I've verified this in my fork before making this PR.)

YAML highlighting on GitHub webpage for CartoCSS MML files

---

scripts/get-fonts.sh
style/fonts.mss

Fixes #4653
Adds fallback fonts and simplifies the font groups.
- Treat Noto Sans Arabic like all other Sans fonts. Until now, it had a special treatment because it could redefine some Latin characters; therefore, it was placed behind. However, this is apparently something that happened in Noto Nashk Arabic (which we used in the past). Since a few years, we are using yet Noto Sans Arabic, which does not have this problem. Also, Arabic is not the only script for which Noto provides particular styles: Hebrew for instance has the Noto Rashi style, so Arabic is not special in this sense either.
- Simpifies the font subgroups to only three subgroups.
- Solves #4653 by choosing Noto Sans Adlam Unjoined. This choise is because Noto recommends the Unjoined …

Rework font fallbacks

---

style/amenity-points.mss

Fixes #4571
https://www.openstreetmap.org/node/4508663884#map=17/50.09751/8.52788
Before:
After:
https://www.openstreetmap.org/node/287007387#map=18/41.63605/2.29384
Before:
After:
https://www.openstreetmap.org/node/4191051281#map=18/37.48069/-122.16901
Before:
After:
https://www.openstreetmap.org/node/9048858681#map=17/-10.82673/40.50762
Before:
After:

Make text transparent exclusivly when also corresponding icon is made transparent

---

project.mml

Fixes #4518
- Define feature order in piers-poly and piers-line for consistent rendering
Test rendering with links to the example places: https://www.openstreetmap.org/#map=19/47.59530/-122.38722
Before: Inconsistent rendering across renderer runs
After: Defined order:

Define feature order in piers-poly and piers-line for consistent rendering

---

project.mml

Fixes #4682
- move the "tourism-boundary" between "power-line" and "protected-areas" as the function and rendering of protected-areas and tourism-boundary are very similar.
[Cedar Point](https://www.openstreetmap.org/relation/11491811)
Before
z16
z19
After
z16
z19

fix: move tourism-boundary above the road layers

---

Dockerfile.import

As discussed on #4677, the Dockerfile import returns this error:
```
import_1 | scripts/get-fonts.sh: 127: scripts/get-fonts.sh: unzip: not found
openstreetmap-carto_import_1 exited with code 127
```
- Adds `unzip` to `Dockerfile.import`
Fixes #4677

Adds unzip to Dockerfile import

---

project.mml
style/amenity-points.mss

Fixes #4568
Before (`access=foo` is interpreted as restricted):
After (`access=foo` is ignored):
This removes the only limited catch-all interpretation on secondary tags in this style (that is the only case where we render all values with a certain key in a special styling variant except for some specific values -  `yes` and `permissive` in this case).  Beyond the problematic mapper feedback this creates a special difficulty when analyzing which tags the style interprets, because it interprets an indefinite number of access values, but not all.
The list of values to be interpreted as restricted is based on the values commonly used on POI features.  See [here](https://taginfo.openstreetmap.org/keys/access?filter=nodes#values) for a more extensive list of values but note that most of these …

Remove limited catch-all for access restricted POI styling

---

CONTRIBUTING.md

Fixes #4678
- Document available syntax highlighting to make it easier for people to contribute to this style. With KF 5.100 (release next month?) [we will also have](https://invent.kde.org/frameworks/syntax-highlighting/-/merge_requests/373) in KDE support for PostgreSQL highlighting with YAML files and in general support for PostGIS within PostgreSQL.
Test rendering with links to t
- No rendering changes.

Document syntax highlighting

---

scripts/change-fonts-cjk.sh

- When building an instance for those who use **particular** characters (here, for example, Korean, Chinese, etc.), this script allows a user to automatically download the proper Noto Font, and edit `style/fonts.mss` from "Noto Sans CJK JP" to "Noto Sans CJK KR", "Noto Sans CJK SC", "Noto Sans CJK TC", or "Noto Sans CJK HK". In the case of those who don't want to change the settings (i.e. want to remain "Noto Sans CJK JP"), just do not execute the script. #2208 
- It may be helpful #4547 ...?
- Only in the case of executing the script, some glyphs of Han scripts changed to forms familiar to those who use specific characters.

Add a bash script to allow a user to change the CJK font conveniently

---

.github/workflows/ci.yml

This avoids a failure if the archives and image version are far enough apart that it's pointing at missing files.
Fixes #4745

Update apt before installing libxml

---

scripts/indexes.py

Fix osm2pgsql index statement creation
Currently, indexes.py creates syntactically wrong `CREATE INDEX` statements for osm2pgsql indexes (using the `--osm2pgsql` option). This is because the target field for the index is specified as `None` (should be `'way'`):
``` SQL
CREATE INDEX planet_osm_point_index ON planet_osm_point USING GIST (None);
```
Additionally, osm2pgsql creates _unnamed_ indexes and so lets the database chooses a meaningful name, which results in `<table_name>_way_idx`. Since re-indexing won't work with unnamed indexes, indexes.py must use a defined index name. However, I recommend using `'way_idx'` as the index name for osm2pgsql indexes (instead of `'index'`) in order to be in line with osm2pgsql.
``` SQL
CREATE INDEX planet_osm_point_way_idx ON planet_osm_point USING …
```

Fix osm2pgsql index statement creation

---

DOCKER.md

This PR updates documentation only, to provide the command that a user can invoke to log into psql using Docker.

Add instructions for logging into the postgres database using Docker

---

openstreetmap-carto.lua
scripts/lua/test.lua

Remove "virtual" border lines on the antimeridian by excluding all features tagged as closure segment.
Fixes #3504
Remove virtual borders on the antimeridian by making use of the enhanced capabilities of osm2pgsql 'flex output' and associated LUA configuration.
Before
[#3504 (comment)](https://github.com/gravitystorm/openstreetmap-carto/issues/3504#issue-379292094)
After
[#3504 (comment)](https://github.com/gravitystorm/openstreetmap-carto/issues/3504#issuecomment-1268260068)

Remove virtual border lines on the antimeridian

---

style/stations.mss

Fixes #4758 
- Change the color of the ref label from transportation-icon to transportation-text
Before
After
As mentioned in the issue, the difference is quite subtle.

fix color of ref label for subway entrance

---

project.mml
style/golf.mss

Fixes #4804 
Changes proposed in this pull request: Removes amenity-points rendering for golf_hole at all levels
- 
Hi zoom (https://www.openstreetmap.org/node/7674311131)
Lower zoom
Keeps pins (https://www.openstreetmap.org/node/6287232319#map=16/50.8542/0.4474)

Removes amenity-points rendering for golf_hole

---

openstreetmap-carto.lua

Moves creation of dictionaries storing admin_level for stage 2 processing of ways from the 'select_relation_members' function to the 'process_relation' function.
- 
Before
After

Potential fix for the issue raised in https://github.com/gravitystorm/openstreetmap-carto/pull/4431#pullrequestreview-1547693270

---

project.mml

Fixes #4008
- Restored rendering for railway=platform + covered=yes
https://www.openstreetmap.org/way/160042477 (left before, right after)

Restored rendering for railway=platform + covered=yes

---

style/amenity-points.mss

Fixes #4767
Remove unreached code in amenity-points.mss. `landuse=farm` is incorrect tagging and is not rendered anyway (not selected by SQL query for text-point layer)
N/A

Remove unused code in amenity-points.mss

---

README.md

The Geofabric fork of OSM Bright is still maintained and it has updated installation instructions that works.

Update OSM Bright link to Geofabric's maintained fork in README.md

---

scripts/get-fonts.sh

By using more reliable mirror, fixes network & certificate issues with osdn.net which has been going on for month, despite reporting the problem to them (no one even acknowledged /replied to the reported issue) .
I've verified that SHA256 sum is the same:
```
571cd4a09ae7da0c642d640fc2442c050aa450ebb0587a95cdd097d41a9c9572  hanazono-20170904.zip
```
<details>
<summary>certificate issues and speed comparison</summary>
```
new:
% wget https://mirrors.dotsrc.org/osdn/hanazono-font/68253/hanazono-20170904.zip
--2023-10-18 18:32:07--  https://mirrors.dotsrc.org/osdn/hanazono-font/68253/hanazono-20170904.zip
Resolving mirrors.dotsrc.org (mirrors.dotsrc.org)... 130.225.254.116, 2001:878:346::116
Connecting to mirrors.dotsrc.org (mirrors.dotsrc.org)|130.225.254.116|:443... connected.
HTTP request …
```

Use more reliable OSDN mirror

---

style/landcover.mss

Fixes #4479 
Change proposed in this pull request:
- Update `@pitch` from `#aae0cb` to `#88e0be`
Golf course with water hazards
https://www.openstreetmap.org/#map=15/41.5966/-93.6898
z15
z16
z17
Park with pitches and pool
https://www.openstreetmap.org/#map=15/41.5731/-93.7213
z15
z16
z17
School with pitches and sports center, nearby wooded area
https://www.openstreetmap.org/#map=15/41.5982/-93.7211
z15
z16
z17
Comparison with the rest of the colors in this style

Update pitch color to be less blue

---

style/tourism.mss

Fixes #4881
This PR has no new features but a bugfix:
- `highway=track` is fixed and again rendered like it is in the current release
- `roller_coaster=track` has no visual changes
`highway=track` is rendered like it is a roller coast track
`highway=track` is rendered correctly again
`roller_coaster=track` is rendered
`roller_coaster=track` is still rendered the same way, no visual changes

Fix rendering of highway=track that was broken in PR #4666

---

project.mml
style/roads.mss

These changes fix some issues with mini-roundabouts (as well as turning-circles) and add rendering for them on trunk roads.
Mini-roundabouts on trunk roads:
Casing on primary roads:
Casing on secondary roads:
Fill on tertiary roads:
Fill on unclassified roads:
Fixes #4380
Fixes #4781

Mini-roundabouts: fixes and trunk road support

---

style/water.mss

Merging of #3750 substantially changed the functionality of the PR compared to the reviewed version.  It also resulted in [hard to understand code](https://github.com/gravitystorm/openstreetmap-carto/blob/aef9179ca4ed40d8f901cd087c01d15533ea0ebb/style/water.mss#L287-L327).
Current de facto rendering can be seen on
https://imagico.de/map/styleinfo/#style=osmcarto&section=tags&key=natural&value=bay
This change implements what @jeisenbe intended in #3750 (i.e. label all natural=bay/strait from z14 independent of how they are mapped).  It also makes the code easier to understand by separating the labeling of water features with a blue fill (like natural=water) from the rendering of water features with label only rendering (natural=bay/strait).

fix merge errors in #3750 (bay/strait labeling)

---

project.mml

Fixes #4898
Restore rendering of reef name removed in #3712. mss code still present, just fixing SQL query.
[Black Middens](https://www.openstreetmap.org/#map=16/55.01298/-1.42160&layers=N) at Z16
Before
After
(Modified render chain hence different typeface, but otherwise identical to standard tile server)

Restore reef name rendering

---

project.mml
style/amenity-points.mss

Fixes #4854 
`barrier=jersey_barrier` on node is rendered as `barrier=block/log` .
`barrier=jersey_barrier` on way is rendered as default barrier, i.e. same as wall, fence.
There doesn't seem any value in introducing a distinct signature for jersey barrier as a way; the point is that the blocks form a continuous barrier. Although personally there doesn't seem much point in even distinguishing a jersey barrier used as a block, from an "ordinary" block, there would be even less point in rendering them differently.
[Node](https://www.openstreetmap.org/#map=18/54.95838/-1.65994)
Current
After
[Way](https://www.openstreetmap.org/#map=18/54.85075/-1.56567)
(Example of barrier between carriageways is not the …

Render barrier=jersey_barrier

---

CONTRIBUTING.md
style/buildings.mss
style/landcover.mss

Fixes NO issue, just cosmetic change
- Use single quoting for String constants
- tested with `carto`; the generated `project.xml` files before and after are identical

Use common Single Quotes for Strings

---

style/amenity-points.mss
style/roads.mss

Fixes: no officially reported issue
- column names in the style files are usually not quoted or double quoted there needed
- tested with `carto`; the generated `project.xml` files before and after are identical

Use common Double Quotes for Columns

---

INSTALL.md

Tracks the change introduced in https://github.com/gravitystorm/openstreetmap-carto/commit/57f503757fe6022f71d554edcf7d02a7514b39be#diff-c9dbabc2d7d239ba319fd6a54c552cf65b8d0b6120a23d04480031b6a25b996e.
- Fix `generate_road_colours.py` reference in `INSTALL.md`

Fix `generate_road_colours.py` reference in `INSTALL.md`

---

project.mml
style/amenity-points.mss

Fixes #4726
**Changes proposed in this pull request**:
As discussed in #5041:
Move `leisure=track` from `amenity-line` (late in layer stack) to new layer between `tunnels` and `landuse-overlay`.
Optimisation of layer ordering from end of road fill to roller coaster.
Move `attraction=water_slide` from `amenity-line` to new layer between `aeroways` and roller coaster.
[Also tweak to `highway=ford` SQL query to simplify hstore query]
[Link](https://www.openstreetmap.org/#map=18/54.833971/-1.603862):
Before
After
[Ford as linear way](https://www.openstreetmap.org/#map=19/54.797344/-1.540874)
[attraction=water_slide](https://www.openstreetmap.org/#map=18/54.295969/-0.412698)
Notes:
The git diff for `project.mml` is not easy to untangle. Here is …

Move leisure=track and attraction=water_slide

---

functions.sql
style/roads.mss

Fixes #5024 
Fixes #4998 
**Changes proposed in this pull request**:
- Render "restricted" access (e.g. `access=destination`) on `highway=motorway/trunk/primary` (currently only `access=no` shown)
- Add access rendering for `highway=pedestrian` using white as contrasting colour.
Note that a tweak to `functions.sql` is needed to allow `highway=pedestrian` to support "restricted" access marking. 
**Test rendering**:
"restricted" access on major highways is not expected to be valid tagging. The purpose of the PR is to highlight potentially incorrect tagging.
Illustrations are taken from a hacked legend rendering, with `access=destination` on all highways.
Note that the increased "coverage" of access tags needs to be weighed against a 7% increase in lines of XML. This is a result of all the …

Additional access marking

---

INSTALL.md
scripts/docker-startup.sh
scripts/get-fonts.py
scripts/get-fonts.sh

After recent comments / mentions on my earlier PR #4893 and seeing https://github.com/switch2osm/switch2osm/pull/278 , I'm proposing a smaller change
This PR:
- adds get-fonts.py , a Python script using the same source as the current get-fonts.sh ; we can recommend this method for current installs and future PRs / maintenance
- uses working URLs for CJK and Noto Emoji fonts
- comments that get-fonts.sh is deprecated, but leaves it in the repo in case to minimize changes
- replaces no fonts (I want to upgrade Noto Arabic, but can save this for future changes to the Python script)

Replace current font download with Python script

---

style/amenity-points.mss

Fixes #4575
There was agreement in the discussion of #4575  that the current rendering of the `operator` tag on ATMs was unsatisfactory: adding visual clutter for map users, and not providing useful feedback for mappers. Overall, removing the labelling seemed the best option.
[Example where decluttering is helpful](https://www.openstreetmap.org/#map=19/54.776899/-1.575763):
Before
After
Note helpful de-duplication of bank vs ATM names, in particular when the bank name is now visible (HSBC UK in bottom right)

Remove operator label on ATM

---

openstreetmap-carto-flex.lua

I checked all keys that are in the planet file at least 1 million times and added some uninteresting keys (usually ids from imports) to the list.
Removed a few that are either not in the database any more or where there are only a few objects left with that key.
See #5027 first bullet point

Update list of ignored keys and key prefixes

---

.dockerignore
DOCKER.md
Dockerfile
Dockerfile.db
Dockerfile.import
docker-compose.yml
scripts/docker-startup.sh
scripts/get-external-data.py
scripts/get-fonts.sh

Fixes #5031
Fixes #5005
Requires #4893, or any other solution for #5043.
The Docker setup is a quick and easy way to get an Openstreetmap-carto dev environment running, so it’s probably worth keeping it in a working state. This PR updates the startup script to take recent changes into account, such as #4978. It also updates the base images to more recent versions.
With this PR alone, setting up the containers fails because fonts cannot be downloaded. Applying #4893 allows testing the whole setup.

Adapt Docker setup to latest changes
